# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

WIRE_SCHEMAS_PART_3: dict[str, tuple[Any, dict[str, tuple[str, str | None]]]] = {
    "ServerConfigData": (
        None,
        {
            "messengers": ("messengers", None),
            "langs": ("langs", "ServerConfigDataLangsItem"),
            "lang": ("lang", None),
            "update": ("update", None),
            "needs_restart": ("needs_restart", None),
            "version": ("version", None),
        },
    ),
    "ServerConfigDataLangsItem": (
        None,
        {
            "code": ("code", None),
            "name": ("name", None),
        },
    ),
    "DashboardChartLinkClicksItem": (
        None,
        {
            "count": ("count", None),
            "date": ("date", None),
        },
    ),
    "DashboardChartCampaignViewsItem": (
        None,
        {
            "count": ("count", None),
            "date": ("date", None),
        },
    ),
    "DashboardCountData": (
        None,
        {
            "subscribers": ("subscribers", "DashboardCountDataSubscribers"),
            "lists": ("lists", "DashboardCountDataLists"),
            "campaigns": ("campaigns", "DashboardCountDataCampaigns"),
            "messages": ("messages", None),
        },
    ),
    "DashboardCountDataSubscribers": (
        None,
        {
            "total": ("total", None),
            "blocklisted": ("blocklisted", None),
            "orphans": ("orphans", None),
        },
    ),
    "DashboardCountDataLists": (
        None,
        {
            "total": ("total", None),
            "private": ("private", None),
            "public": ("public", None),
            "optin_single": ("optin_single", None),
            "optin_double": ("optin_double", None),
        },
    ),
    "DashboardCountDataCampaigns": (
        None,
        {
            "total": ("total", None),
            "by_status": ("by_status", "DashboardCountDataCampaignsByStatus"),
        },
    ),
    "DashboardCountDataCampaignsByStatus": (
        None,
        {
            "draft": ("draft", None),
        },
    ),
    "SubscriberListsItem": (
        None,
        {
            "subscription_status": ("subscription_status", None),
            "id": ("id", None),
            "uuid": ("uuid", None),
            "name": ("name", None),
            "type": ("type", None),
            "tags": ("tags", None),
            "created_at": ("created_at", None),
            "updated_at": ("updated_at", None),
        },
    ),
    "BounceResultsItem": (
        None,
        {
            "id": ("id", None),
            "type": ("type", None),
            "source": ("source", None),
            "meta": ("meta", None),
            "created_at": ("created_at", None),
            "email": ("email", None),
            "subscriber_uuid": ("subscriber_uuid", None),
            "subscriber_id": ("subscriber_id", None),
            "campaign": ("campaign", "BounceResultsItemCampaign"),
            "campaign_uuid": ("campaign_uuid", None),
            "total": ("total", None),
        },
    ),
    "BounceResultsItemCampaign": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
        },
    ),
    "ImportStatusData": (
        None,
        {
            "name": ("name", None),
            "total": ("total", None),
            "imported": ("imported", None),
            "status": ("status", None),
        },
    ),
    "CampaignListsItem": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
        },
    ),
    "CampaignContentRequestListsItem": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
        },
    ),
    "CampaignRequestSendAt": (
        None,
        {
            "headers": ("headers", None),
            "template_id": ("template_id", None),
        },
    ),
    "GetSubscribersResponseData": (
        None,
        {
            "results": ("results", "Subscriber"),
            "query": ("query", None),
            "total": ("total", None),
            "per_page": ("per_page", None),
            "page": ("page", None),
        },
    ),
    "GetBouncesResponseData": (
        None,
        {
            "results": ("results", "Bounce"),
            "query": ("query", None),
            "total": ("total", None),
            "per_page": ("per_page", None),
            "page": ("page", None),
        },
    ),
    "GetListsResponseData": (
        None,
        {
            "results": ("results", "ListModel"),
            "total": ("total", None),
            "per_page": ("per_page", None),
            "page": ("page", None),
        },
    ),
    "GetCampaignsResponseData": (
        None,
        {
            "results": ("results", "Campaign"),
            "query": ("query", None),
            "total": ("total", None),
            "per_page": ("per_page", None),
            "page": ("page", None),
        },
    ),
    "DeleteGCSubscribersResponseData": (
        None,
        {
            "count": ("count", None),
        },
    ),
    "DeleteUnconfirmedSubscriptionsResponseData": (
        None,
        {
            "count": ("count", None),
        },
    ),
}
