# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import ManageSubscriberListsByQueryResponse
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def manage_subscriber_lists_by_query_text(
    _client_config: ClientConfig,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListsByQueryResponse:
    """Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk adds/removes/unsubscribes subscribers from one or more lists based on an
    arbitrary SQL expression.
    """

    _resp = await sdk_request(
        "PUT",
        "/subscribers/query/lists",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
        content_type="text/plain",
        operation_id="manage_subscriber_lists_by_query_text",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListsByQueryResponse"),
        ManageSubscriberListsByQueryResponse,
    )


def manage_subscriber_lists_by_query_text_sync(
    _client_config: ClientConfig,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListsByQueryResponse:
    """Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk adds/removes/unsubscribes subscribers from one or more lists based on an
    arbitrary SQL expression.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/subscribers/query/lists",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
        content_type="text/plain",
        operation_id="manage_subscriber_lists_by_query_text",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListsByQueryResponse"),
        ManageSubscriberListsByQueryResponse,
    )


__all__ = [
    "manage_subscriber_lists_by_query_text",
    "manage_subscriber_lists_by_query_text_sync",
]
