# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from listmonk_unofficial_sdk.types import (
    CreateSubscriberResponse,
    DeleteSubscriberByIdResponse,
    DeleteSubscriberByListResponse,
    GetSubscriberByIdResponse,
    GetSubscribersResponse,
    UpdateSubscriberByIdResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_subscribers(
    _client_config: ClientConfig,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    query: str | NotGiven = NOT_GIVEN,
    order_by: Literal["name", "status", "created_at", "updated_at"] | str | NotGiven = NOT_GIVEN,
    order: Literal["ASC", "DESC"] | str | NotGiven = NOT_GIVEN,
    subscription_status: str | NotGiven = NOT_GIVEN,
    list_id: list[int] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetSubscribersResponse:
    """Lists subscribers, with options to filter and sort the results. Use `query` to
    filter with an SQL expression, `list_id` to filter by lists, and `order_by` and
    `order` to control sorting. Use `page` and `per_page` to paginate the results.

    returns all subscribers.

    Args:
        page: Page number for paginated results.
        per_page: Number of items per page. Use an integer for specific page size or 'all' to
            retrieve all results
        query: query subscribers with an SQL expression.
        order_by: Result sorting field. Options are name, status, created_at, updated_at
        order: ASC|DESC Sort by ascending or descending order.
        subscription_status: Subscription status to filter by if there are one or more list_ids.
        list_id: ID of lists to filter by. Repeat in the query for multiple values.
    """

    _resp = await sdk_request(
        "GET",
        "/subscribers",
        params=serialize_query(
            [
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("query", query, "form", True),
                ("order_by", order_by, "form", True),
                ("order", order, "form", True),
                ("subscription_status", subscription_status, "form", True),
                ("list_id", list_id, "form", True),
            ]
        ),
        operation_id="get_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSubscribersResponse"), GetSubscribersResponse
    )


def get_subscribers_sync(
    _client_config: ClientConfig,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    query: str | NotGiven = NOT_GIVEN,
    order_by: Literal["name", "status", "created_at", "updated_at"] | str | NotGiven = NOT_GIVEN,
    order: Literal["ASC", "DESC"] | str | NotGiven = NOT_GIVEN,
    subscription_status: str | NotGiven = NOT_GIVEN,
    list_id: list[int] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetSubscribersResponse:
    """Lists subscribers, with options to filter and sort the results. Use `query` to
    filter with an SQL expression, `list_id` to filter by lists, and `order_by` and
    `order` to control sorting. Use `page` and `per_page` to paginate the results.

    returns all subscribers.

    Args:
        page: Page number for paginated results.
        per_page: Number of items per page. Use an integer for specific page size or 'all' to
            retrieve all results
        query: query subscribers with an SQL expression.
        order_by: Result sorting field. Options are name, status, created_at, updated_at
        order: ASC|DESC Sort by ascending or descending order.
        subscription_status: Subscription status to filter by if there are one or more list_ids.
        list_id: ID of lists to filter by. Repeat in the query for multiple values.
    """

    _resp = sdk_request_sync(
        "GET",
        "/subscribers",
        params=serialize_query(
            [
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("query", query, "form", True),
                ("order_by", order_by, "form", True),
                ("order", order, "form", True),
                ("subscription_status", subscription_status, "form", True),
                ("list_id", list_id, "form", True),
            ]
        ),
        operation_id="get_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSubscribersResponse"), GetSubscribersResponse
    )


async def create_subscriber(
    _client_config: ClientConfig,
    email: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    status: str | NotGiven = NOT_GIVEN,
    lists: list[int] | NotGiven = NOT_GIVEN,
    list_uuids: list[str] | NotGiven = NOT_GIVEN,
    preconfirm_subscriptions: bool | NotGiven = NOT_GIVEN,
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateSubscriberResponse:
    """Creates a subscriber from the supplied subscriber details. The request body may be
    omitted, and no fields are required by the schema; include values such as `email`,
    `name`, or `lists` to set subscriber data.

    handles creation of new subscriber

    Args:
        email: Optional `string` value serialized in the `email` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        status: Optional `string` value serialized in the `status` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        list_uuids: Optional array value serialized in the `list_uuids` wire field.
        preconfirm_subscriptions: Optional `boolean` value serialized in the `preconfirm_subscriptions` wire
            field.
        attribs: Optional object value serialized in the `attribs` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/subscribers",
        json=omit_unset(
            {
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "status": (NOT_GIVEN if status is NOT_GIVEN else to_wire(status, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[int]")),
                "list_uuids": (
                    NOT_GIVEN if list_uuids is NOT_GIVEN else to_wire(list_uuids, "list[str]")
                ),
                "preconfirm_subscriptions": (
                    NOT_GIVEN
                    if preconfirm_subscriptions is NOT_GIVEN
                    else to_wire(preconfirm_subscriptions, "bool")
                ),
                "attribs": (
                    NOT_GIVEN if attribs is NOT_GIVEN else to_wire(attribs, "dict[str, Any]")
                ),
            }
        ),
        operation_id="create_subscriber",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateSubscriberResponse"), CreateSubscriberResponse
    )


def create_subscriber_sync(
    _client_config: ClientConfig,
    email: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    status: str | NotGiven = NOT_GIVEN,
    lists: list[int] | NotGiven = NOT_GIVEN,
    list_uuids: list[str] | NotGiven = NOT_GIVEN,
    preconfirm_subscriptions: bool | NotGiven = NOT_GIVEN,
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateSubscriberResponse:
    """Creates a subscriber from the supplied subscriber details. The request body may be
    omitted, and no fields are required by the schema; include values such as `email`,
    `name`, or `lists` to set subscriber data.

    handles creation of new subscriber

    Args:
        email: Optional `string` value serialized in the `email` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        status: Optional `string` value serialized in the `status` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        list_uuids: Optional array value serialized in the `list_uuids` wire field.
        preconfirm_subscriptions: Optional `boolean` value serialized in the `preconfirm_subscriptions` wire
            field.
        attribs: Optional object value serialized in the `attribs` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/subscribers",
        json=omit_unset(
            {
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "status": (NOT_GIVEN if status is NOT_GIVEN else to_wire(status, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[int]")),
                "list_uuids": (
                    NOT_GIVEN if list_uuids is NOT_GIVEN else to_wire(list_uuids, "list[str]")
                ),
                "preconfirm_subscriptions": (
                    NOT_GIVEN
                    if preconfirm_subscriptions is NOT_GIVEN
                    else to_wire(preconfirm_subscriptions, "bool")
                ),
                "attribs": (
                    NOT_GIVEN if attribs is NOT_GIVEN else to_wire(attribs, "dict[str, Any]")
                ),
            }
        ),
        operation_id="create_subscriber",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateSubscriberResponse"), CreateSubscriberResponse
    )


async def delete_subscriber_by_list(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByListResponse:
    """Deletes one or more subscribers identified by the `id` query parameter. Supply the
    subscriber ID or IDs as a string, with each ID identifying a subscriber to delete.

    handles subscribers deletion

    Args:
        id: subscriber id/s to be deleted
    """

    _resp = await sdk_request(
        "DELETE",
        "/subscribers",
        params=serialize_query([("id", id, "form", True)]),
        operation_id="delete_subscriber_by_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByListResponse"),
        DeleteSubscriberByListResponse,
    )


def delete_subscriber_by_list_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByListResponse:
    """Deletes one or more subscribers identified by the `id` query parameter. Supply the
    subscriber ID or IDs as a string, with each ID identifying a subscriber to delete.

    handles subscribers deletion

    Args:
        id: subscriber id/s to be deleted
    """

    _resp = sdk_request_sync(
        "DELETE",
        "/subscribers",
        params=serialize_query([("id", id, "form", True)]),
        operation_id="delete_subscriber_by_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByListResponse"),
        DeleteSubscriberByListResponse,
    )


async def get_subscriber_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetSubscriberByIdResponse:
    """Retrieves a subscriber by its identifier. Use the `id` path parameter to select the
    subscriber whose details you want to view.

    handles the retrieval of a single subscriber by ID.

    Args:
        id: The id value of the subscriber you want to get.
    """

    _resp = await sdk_request(
        "GET",
        f"/subscribers/{encode_path_segment(id)}",
        operation_id="get_subscriber_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSubscriberByIdResponse"), GetSubscriberByIdResponse
    )


def get_subscriber_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetSubscriberByIdResponse:
    """Retrieves a subscriber by its identifier. Use the `id` path parameter to select the
    subscriber whose details you want to view.

    handles the retrieval of a single subscriber by ID.

    Args:
        id: The id value of the subscriber you want to get.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/subscribers/{encode_path_segment(id)}",
        operation_id="get_subscriber_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSubscriberByIdResponse"), GetSubscriberByIdResponse
    )


async def update_subscriber_by_id(
    _client_config: ClientConfig,
    id: int,
    email: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    status: str | NotGiven = NOT_GIVEN,
    lists: list[int] | NotGiven = NOT_GIVEN,
    list_uuids: list[str] | NotGiven = NOT_GIVEN,
    preconfirm_subscriptions: bool | NotGiven = NOT_GIVEN,
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateSubscriberByIdResponse:
    """Replaces subscriber data for the subscriber identified by the path parameter. The
    request body may be omitted, and the schema does not require any fields; supply the
    subscriber properties you want included in the update.

    modify subscriber data

    Args:
        id: The id of subscriber to update
        email: Optional `string` value serialized in the `email` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        status: Optional `string` value serialized in the `status` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        list_uuids: Optional array value serialized in the `list_uuids` wire field.
        preconfirm_subscriptions: Optional `boolean` value serialized in the `preconfirm_subscriptions` wire
            field.
        attribs: Optional object value serialized in the `attribs` wire field.
    """

    _resp = await sdk_request(
        "PUT",
        f"/subscribers/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "status": (NOT_GIVEN if status is NOT_GIVEN else to_wire(status, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[int]")),
                "list_uuids": (
                    NOT_GIVEN if list_uuids is NOT_GIVEN else to_wire(list_uuids, "list[str]")
                ),
                "preconfirm_subscriptions": (
                    NOT_GIVEN
                    if preconfirm_subscriptions is NOT_GIVEN
                    else to_wire(preconfirm_subscriptions, "bool")
                ),
                "attribs": (
                    NOT_GIVEN if attribs is NOT_GIVEN else to_wire(attribs, "dict[str, Any]")
                ),
            }
        ),
        operation_id="update_subscriber_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateSubscriberByIdResponse"),
        UpdateSubscriberByIdResponse,
    )


def update_subscriber_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    email: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    status: str | NotGiven = NOT_GIVEN,
    lists: list[int] | NotGiven = NOT_GIVEN,
    list_uuids: list[str] | NotGiven = NOT_GIVEN,
    preconfirm_subscriptions: bool | NotGiven = NOT_GIVEN,
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateSubscriberByIdResponse:
    """Replaces subscriber data for the subscriber identified by the path parameter. The
    request body may be omitted, and the schema does not require any fields; supply the
    subscriber properties you want included in the update.

    modify subscriber data

    Args:
        id: The id of subscriber to update
        email: Optional `string` value serialized in the `email` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        status: Optional `string` value serialized in the `status` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        list_uuids: Optional array value serialized in the `list_uuids` wire field.
        preconfirm_subscriptions: Optional `boolean` value serialized in the `preconfirm_subscriptions` wire
            field.
        attribs: Optional object value serialized in the `attribs` wire field.
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/subscribers/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "status": (NOT_GIVEN if status is NOT_GIVEN else to_wire(status, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[int]")),
                "list_uuids": (
                    NOT_GIVEN if list_uuids is NOT_GIVEN else to_wire(list_uuids, "list[str]")
                ),
                "preconfirm_subscriptions": (
                    NOT_GIVEN
                    if preconfirm_subscriptions is NOT_GIVEN
                    else to_wire(preconfirm_subscriptions, "bool")
                ),
                "attribs": (
                    NOT_GIVEN if attribs is NOT_GIVEN else to_wire(attribs, "dict[str, Any]")
                ),
            }
        ),
        operation_id="update_subscriber_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateSubscriberByIdResponse"),
        UpdateSubscriberByIdResponse,
    )


async def delete_subscriber_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByIdResponse:
    """Deletes a subscriber identified by its path parameter. Use the subscriber's integer
    `id` to select the record to remove.

    handles subscriber deletion based on id

    Args:
        id: The id value of the subscriber you want to get.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/subscribers/{encode_path_segment(id)}",
        operation_id="delete_subscriber_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByIdResponse"),
        DeleteSubscriberByIdResponse,
    )


def delete_subscriber_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByIdResponse:
    """Deletes a subscriber identified by its path parameter. Use the subscriber's integer
    `id` to select the record to remove.

    handles subscriber deletion based on id

    Args:
        id: The id value of the subscriber you want to get.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/subscribers/{encode_path_segment(id)}",
        operation_id="delete_subscriber_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByIdResponse"),
        DeleteSubscriberByIdResponse,
    )


__all__ = [
    "create_subscriber",
    "create_subscriber_sync",
    "delete_subscriber_by_id",
    "delete_subscriber_by_id_sync",
    "delete_subscriber_by_list",
    "delete_subscriber_by_list_sync",
    "get_subscriber_by_id",
    "get_subscriber_by_id_sync",
    "get_subscribers",
    "get_subscribers_sync",
    "update_subscriber_by_id",
    "update_subscriber_by_id_sync",
]
