# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    GetSubscriberBouncesByIdResponse,
    ManageBlocklistBySubscriberListResponse,
    ManageBlocklistSubscribersByIdResponse,
    ManageSubscriberListByIdResponse,
    ManageSubscriberListsResponse,
    SubscriberData,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def manage_subscriber_lists(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListsResponse:
    """Manages subscriber membership across lists by adding, removing, or unsubscribing
    subscribers. Supply `action` and the subscriber or list selectors that define which
    records to modify; `action` must be `add`, `remove`, or `unsubscribe`.

    handles bulk addition or removal of subscribers

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = await sdk_request(
        "PUT",
        "/subscribers/lists",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_subscriber_lists",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListsResponse"),
        ManageSubscriberListsResponse,
    )


def manage_subscriber_lists_sync(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListsResponse:
    """Manages subscriber membership across lists by adding, removing, or unsubscribing
    subscribers. Supply `action` and the subscriber or list selectors that define which
    records to modify; `action` must be `add`, `remove`, or `unsubscribe`.

    handles bulk addition or removal of subscribers

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/subscribers/lists",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_subscriber_lists",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListsResponse"),
        ManageSubscriberListsResponse,
    )


async def manage_subscriber_list_by_id(
    _client_config: ClientConfig,
    id: int,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListByIdResponse:
    """Manages subscriber membership in a specified list by adding, removing, or
    unsubscribing subscribers. Use the `id` path parameter to select the list and
    provide the subscriber selectors and `action` in the request body.

    handles bulk addition or removal of subscribers for a specified list id

    Args:
        id: The id of list you want to update
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = await sdk_request(
        "PUT",
        f"/subscribers/lists/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_subscriber_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListByIdResponse"),
        ManageSubscriberListByIdResponse,
    )


def manage_subscriber_list_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListByIdResponse:
    """Manages subscriber membership in a specified list by adding, removing, or
    unsubscribing subscribers. Use the `id` path parameter to select the list and
    provide the subscriber selectors and `action` in the request body.

    handles bulk addition or removal of subscribers for a specified list id

    Args:
        id: The id of list you want to update
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/subscribers/lists/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_subscriber_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListByIdResponse"),
        ManageSubscriberListByIdResponse,
    )


async def manage_blocklist_by_subscriber_list(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageBlocklistBySubscriberListResponse:
    """Manages subscribers on the blocklist using subscriber selectors and list settings.
    Provide `action` to specify whether to add, remove, or unsubscribe the selected
    subscribers.

    handles blocklisting of subscriber list

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = await sdk_request(
        "PUT",
        "/subscribers/blocklist",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_blocklist_by_subscriber_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageBlocklistBySubscriberListResponse"),
        ManageBlocklistBySubscriberListResponse,
    )


def manage_blocklist_by_subscriber_list_sync(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageBlocklistBySubscriberListResponse:
    """Manages subscribers on the blocklist using subscriber selectors and list settings.
    Provide `action` to specify whether to add, remove, or unsubscribe the selected
    subscribers.

    handles blocklisting of subscriber list

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/subscribers/blocklist",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_blocklist_by_subscriber_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageBlocklistBySubscriberListResponse"),
        ManageBlocklistBySubscriberListResponse,
    )


async def manage_blocklist_subscribers_by_id(
    _client_config: ClientConfig,
    id: int,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageBlocklistSubscribersByIdResponse:
    """Manages the blocklist for the subscriber identified by the path parameter. Use the
    `id` path parameter to select the subscriber and provide the action and any
    additional selectors in the request body.

    handles the blocklisting of one or more subscribers.

    Args:
        id: The id value of the subscriber you want to blocklist.
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = await sdk_request(
        "PUT",
        f"/subscribers/{encode_path_segment(id)}/blocklist",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_blocklist_subscribers_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageBlocklistSubscribersByIdResponse"),
        ManageBlocklistSubscribersByIdResponse,
    )


def manage_blocklist_subscribers_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageBlocklistSubscribersByIdResponse:
    """Manages the blocklist for the subscriber identified by the path parameter. Use the
    `id` path parameter to select the subscriber and provide the action and any
    additional selectors in the request body.

    handles the blocklisting of one or more subscribers.

    Args:
        id: The id value of the subscriber you want to blocklist.
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/subscribers/{encode_path_segment(id)}/blocklist",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_blocklist_subscribers_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageBlocklistSubscribersByIdResponse"),
        ManageBlocklistSubscribersByIdResponse,
    )


async def export_subscriber_data_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> SubscriberData:
    """Retrieves a subscriber's profile and related activity data for export. Supply the
    subscriber's numeric `id` to retrieve profile details, subscriptions, campaign
    views, and link clicks.

    retrieves a subscriber's profile

    Args:
        id: The id value of subscriber profile you want to export
    """

    _resp = await sdk_request(
        "GET",
        f"/subscribers/{encode_path_segment(id)}/export",
        operation_id="export_subscriber_data_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SubscriberData"), SubscriberData
    )


def export_subscriber_data_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> SubscriberData:
    """Retrieves a subscriber's profile and related activity data for export. Supply the
    subscriber's numeric `id` to retrieve profile details, subscriptions, campaign
    views, and link clicks.

    retrieves a subscriber's profile

    Args:
        id: The id value of subscriber profile you want to export
    """

    _resp = sdk_request_sync(
        "GET",
        f"/subscribers/{encode_path_segment(id)}/export",
        operation_id="export_subscriber_data_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SubscriberData"), SubscriberData
    )


async def get_subscriber_bounces_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetSubscriberBouncesByIdResponse:
    """Retrieves bounce records associated with a specific subscriber. Supply the
    subscriber's numeric `id` to look up the records for that subscriber.

    retrieves a subscriber's bounce records

    Args:
        id: subscriber id
    """

    _resp = await sdk_request(
        "GET",
        f"/subscribers/{encode_path_segment(id)}/bounces",
        operation_id="get_subscriber_bounces_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSubscriberBouncesByIdResponse"),
        GetSubscriberBouncesByIdResponse,
    )


def get_subscriber_bounces_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetSubscriberBouncesByIdResponse:
    """Retrieves bounce records associated with a specific subscriber. Supply the
    subscriber's numeric `id` to look up the records for that subscriber.

    retrieves a subscriber's bounce records

    Args:
        id: subscriber id
    """

    _resp = sdk_request_sync(
        "GET",
        f"/subscribers/{encode_path_segment(id)}/bounces",
        operation_id="get_subscriber_bounces_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSubscriberBouncesByIdResponse"),
        GetSubscriberBouncesByIdResponse,
    )


__all__ = [
    "export_subscriber_data_by_id",
    "export_subscriber_data_by_id_sync",
    "get_subscriber_bounces_by_id",
    "get_subscriber_bounces_by_id_sync",
    "manage_blocklist_by_subscriber_list",
    "manage_blocklist_by_subscriber_list_sync",
    "manage_blocklist_subscribers_by_id",
    "manage_blocklist_subscribers_by_id_sync",
    "manage_subscriber_list_by_id",
    "manage_subscriber_list_by_id_sync",
    "manage_subscriber_lists",
    "manage_subscriber_lists_sync",
]
