# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    BlocklistSubscribersQueryResponse,
    DeleteSubscriberBouncesByIdResponse,
    DeleteSubscriberByQueryResponse,
    ManageSubscriberListsByQueryResponse,
    SubscriberSendOptinByIdResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def delete_subscriber_bounces_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberBouncesByIdResponse:
    """Deletes the bounce records associated with a specific subscriber. Supply the
    subscriber's numeric `id` to identify whose bounce records to delete.

    deletes a subscriber's bounce records

    Args:
        id: subscriber id
    """

    _resp = await sdk_request(
        "DELETE",
        f"/subscribers/{encode_path_segment(id)}/bounces",
        operation_id="delete_subscriber_bounces_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberBouncesByIdResponse"),
        DeleteSubscriberBouncesByIdResponse,
    )


def delete_subscriber_bounces_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberBouncesByIdResponse:
    """Deletes the bounce records associated with a specific subscriber. Supply the
    subscriber's numeric `id` to identify whose bounce records to delete.

    deletes a subscriber's bounce records

    Args:
        id: subscriber id
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/subscribers/{encode_path_segment(id)}/bounces",
        operation_id="delete_subscriber_bounces_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberBouncesByIdResponse"),
        DeleteSubscriberBouncesByIdResponse,
    )


async def subscriber_send_optin_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> SubscriberSendOptinByIdResponse:
    """Sends an opt-in confirmation email to a subscriber. Supply the subscriber's numeric
    `id` to identify the recipient of the confirmation email.

    sends an optin confirmation e-mail to a subscriber.

    Args:
        id: sends an optin confirmation e-mail to a subscriber
    """

    _resp = await sdk_request(
        "POST",
        f"/subscribers/{encode_path_segment(id)}/optin",
        operation_id="subscriber_send_optin_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SubscriberSendOptinByIdResponse"),
        SubscriberSendOptinByIdResponse,
    )


def subscriber_send_optin_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> SubscriberSendOptinByIdResponse:
    """Sends an opt-in confirmation email to a subscriber. Supply the subscriber's numeric
    `id` to identify the recipient of the confirmation email.

    sends an optin confirmation e-mail to a subscriber.

    Args:
        id: sends an optin confirmation e-mail to a subscriber
    """

    _resp = sdk_request_sync(
        "POST",
        f"/subscribers/{encode_path_segment(id)}/optin",
        operation_id="subscriber_send_optin_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SubscriberSendOptinByIdResponse"),
        SubscriberSendOptinByIdResponse,
    )


async def delete_subscriber_by_query(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByQueryResponse:
    """Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide
    the expression as plain text or use a JSON body to specify `query`, `ids`, and any
    applicable `action`, `target_list_ids`, or `status` filters.

    bulk deletes based on an arbitrary SQL expression.

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = await sdk_request(
        "POST",
        "/subscribers/query/delete",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="delete_subscriber_by_query",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByQueryResponse"),
        DeleteSubscriberByQueryResponse,
    )


def delete_subscriber_by_query_sync(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByQueryResponse:
    """Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide
    the expression as plain text or use a JSON body to specify `query`, `ids`, and any
    applicable `action`, `target_list_ids`, or `status` filters.

    bulk deletes based on an arbitrary SQL expression.

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = sdk_request_sync(
        "POST",
        "/subscribers/query/delete",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="delete_subscriber_by_query",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByQueryResponse"),
        DeleteSubscriberByQueryResponse,
    )


async def delete_subscriber_by_query_text(
    _client_config: ClientConfig,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByQueryResponse:
    """Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide
    the expression as plain text or use a JSON body to specify `query`, `ids`, and any
    applicable `action`, `target_list_ids`, or `status` filters.

    bulk deletes based on an arbitrary SQL expression.
    """

    _resp = await sdk_request(
        "POST",
        "/subscribers/query/delete",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
        content_type="text/plain",
        operation_id="delete_subscriber_by_query_text",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByQueryResponse"),
        DeleteSubscriberByQueryResponse,
    )


def delete_subscriber_by_query_text_sync(
    _client_config: ClientConfig,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteSubscriberByQueryResponse:
    """Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide
    the expression as plain text or use a JSON body to specify `query`, `ids`, and any
    applicable `action`, `target_list_ids`, or `status` filters.

    bulk deletes based on an arbitrary SQL expression.
    """

    _resp = sdk_request_sync(
        "POST",
        "/subscribers/query/delete",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
        content_type="text/plain",
        operation_id="delete_subscriber_by_query_text",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteSubscriberByQueryResponse"),
        DeleteSubscriberByQueryResponse,
    )


async def blocklist_subscribers_query(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BlocklistSubscribersQueryResponse:
    """Adds or removes subscribers from the blocklist based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk blocklists subscribers based on an arbitrary SQL expression.

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = await sdk_request(
        "PUT",
        "/subscribers/query/blocklist",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="blocklist_subscribers_query",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BlocklistSubscribersQueryResponse"),
        BlocklistSubscribersQueryResponse,
    )


def blocklist_subscribers_query_sync(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BlocklistSubscribersQueryResponse:
    """Adds or removes subscribers from the blocklist based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk blocklists subscribers based on an arbitrary SQL expression.

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/subscribers/query/blocklist",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="blocklist_subscribers_query",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BlocklistSubscribersQueryResponse"),
        BlocklistSubscribersQueryResponse,
    )


async def blocklist_subscribers_query_text(
    _client_config: ClientConfig,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BlocklistSubscribersQueryResponse:
    """Adds or removes subscribers from the blocklist based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk blocklists subscribers based on an arbitrary SQL expression.
    """

    _resp = await sdk_request(
        "PUT",
        "/subscribers/query/blocklist",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
        content_type="text/plain",
        operation_id="blocklist_subscribers_query_text",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BlocklistSubscribersQueryResponse"),
        BlocklistSubscribersQueryResponse,
    )


def blocklist_subscribers_query_text_sync(
    _client_config: ClientConfig,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BlocklistSubscribersQueryResponse:
    """Adds or removes subscribers from the blocklist based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk blocklists subscribers based on an arbitrary SQL expression.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/subscribers/query/blocklist",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
        content_type="text/plain",
        operation_id="blocklist_subscribers_query_text",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BlocklistSubscribersQueryResponse"),
        BlocklistSubscribersQueryResponse,
    )


async def manage_subscriber_lists_by_query(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListsByQueryResponse:
    """Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk adds/removes/unsubscribes subscribers from one or more lists based on an
    arbitrary SQL expression.

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = await sdk_request(
        "PUT",
        "/subscribers/query/lists",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_subscriber_lists_by_query",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListsByQueryResponse"),
        ManageSubscriberListsByQueryResponse,
    )


def manage_subscriber_lists_by_query_sync(
    _client_config: ClientConfig,
    query: str | NotGiven = NOT_GIVEN,
    ids: list[int] | NotGiven = NOT_GIVEN,
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN,
    target_list_ids: int | NotGiven = NOT_GIVEN,
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ManageSubscriberListsByQueryResponse:
    """Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or
    subscriber identifiers. Provide the expression as plain text or use a JSON body to
    specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status`
    filters.

    bulk adds/removes/unsubscribes subscribers from one or more lists based on an
    arbitrary SQL expression.

    Args:
        query: Optional `string` value serialized in the `query` wire field.
        ids: The ids of the subscribers to be modified.
        action: Whether to add, remove, or unsubscribe the users.
        target_list_ids: The ids of the lists to be modified.
        status: confirmed, unconfirmed, or unsubscribed status.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/subscribers/query/lists",
        json=omit_unset(
            {
                "query": (NOT_GIVEN if query is NOT_GIVEN else to_wire(query, "str")),
                "ids": (NOT_GIVEN if ids is NOT_GIVEN else to_wire(ids, "list[int]")),
                "action": (
                    NOT_GIVEN
                    if action is NOT_GIVEN
                    else to_wire(action, 'Literal["add", "remove", "unsubscribe"] | str')
                ),
                "target_list_ids": (
                    NOT_GIVEN if target_list_ids is NOT_GIVEN else to_wire(target_list_ids, "int")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["confirmed", "unconfirmed", "unsubscribed"] | str'
                    )
                ),
            }
        ),
        operation_id="manage_subscriber_lists_by_query",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ManageSubscriberListsByQueryResponse"),
        ManageSubscriberListsByQueryResponse,
    )


__all__ = [
    "blocklist_subscribers_query",
    "blocklist_subscribers_query_sync",
    "blocklist_subscribers_query_text",
    "blocklist_subscribers_query_text_sync",
    "delete_subscriber_bounces_by_id",
    "delete_subscriber_bounces_by_id_sync",
    "delete_subscriber_by_query",
    "delete_subscriber_by_query_sync",
    "delete_subscriber_by_query_text",
    "delete_subscriber_by_query_text_sync",
    "manage_subscriber_lists_by_query",
    "manage_subscriber_lists_by_query_sync",
    "subscriber_send_optin_by_id",
    "subscriber_send_optin_by_id_sync",
]
