# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    ClientConfig,
    RequestOptions,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import ReloadAppResponse
from listmonk_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def reload_app(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ReloadAppResponse:
    """Restarts the application. Use this operation to reload the application process and
    its configuration.

    restarts the app
    """

    _resp = await sdk_request(
        "POST",
        "/admin/reload",
        operation_id="reload_app",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ReloadAppResponse"), ReloadAppResponse
    )


def reload_app_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ReloadAppResponse:
    """Restarts the application. Use this operation to reload the application process and
    its configuration.

    restarts the app
    """

    _resp = sdk_request_sync(
        "POST",
        "/admin/reload",
        operation_id="reload_app",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ReloadAppResponse"), ReloadAppResponse
    )


__all__ = [
    "reload_app",
    "reload_app_sync",
]
