# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from listmonk_unofficial_sdk.types import (
    DeleteBounceByIdResponse,
    DeleteBouncesResponse,
    GetBounceByIdResponse,
    GetBouncesResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_bounces(
    _client_config: ClientConfig,
    campaign_id: int | NotGiven = NOT_GIVEN,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    source: str | NotGiven = NOT_GIVEN,
    order_by: Literal["email", "campaign_name", "source", "created_at"]
    | str
    | NotGiven = NOT_GIVEN,
    order: Literal["asc", "desc"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetBouncesResponse:
    """Lists bounce records, optionally filtered by campaign or source and sorted by a
    selected field. Use `page` and `per_page` to paginate the results; set `per_page` to
    `all` to retrieve all results without pagination.

    handles retrieval of bounce records.

    Args:
        campaign_id: Numeric identifier for retrieving bounce records associated with a specific
            campaign
        page: Page number for paginated results. Start from 1 for the first page
        per_page: Number of items per page. Use an integer for specific page size or 'all' to
            retrieve all results
        source: Filter bounce records by their source of origin
        order_by: Specifies the field by which to sort the bounce records. Available options are
            'email', 'campaign_name', 'source', and 'created_at'
        order: Determines the sort order of results. Use 'asc' for ascending or 'desc' for
            descending order
    """

    _resp = await sdk_request(
        "GET",
        "/bounces",
        params=serialize_query(
            [
                ("campaign_id", campaign_id, "form", True),
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("source", source, "form", True),
                ("order_by", order_by, "form", True),
                ("order", order, "form", True),
            ]
        ),
        operation_id="get_bounces",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetBouncesResponse"), GetBouncesResponse
    )


def get_bounces_sync(
    _client_config: ClientConfig,
    campaign_id: int | NotGiven = NOT_GIVEN,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    source: str | NotGiven = NOT_GIVEN,
    order_by: Literal["email", "campaign_name", "source", "created_at"]
    | str
    | NotGiven = NOT_GIVEN,
    order: Literal["asc", "desc"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetBouncesResponse:
    """Lists bounce records, optionally filtered by campaign or source and sorted by a
    selected field. Use `page` and `per_page` to paginate the results; set `per_page` to
    `all` to retrieve all results without pagination.

    handles retrieval of bounce records.

    Args:
        campaign_id: Numeric identifier for retrieving bounce records associated with a specific
            campaign
        page: Page number for paginated results. Start from 1 for the first page
        per_page: Number of items per page. Use an integer for specific page size or 'all' to
            retrieve all results
        source: Filter bounce records by their source of origin
        order_by: Specifies the field by which to sort the bounce records. Available options are
            'email', 'campaign_name', 'source', and 'created_at'
        order: Determines the sort order of results. Use 'asc' for ascending or 'desc' for
            descending order
    """

    _resp = sdk_request_sync(
        "GET",
        "/bounces",
        params=serialize_query(
            [
                ("campaign_id", campaign_id, "form", True),
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("source", source, "form", True),
                ("order_by", order_by, "form", True),
                ("order", order, "form", True),
            ]
        ),
        operation_id="get_bounces",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetBouncesResponse"), GetBouncesResponse
    )


async def delete_bounces(
    _client_config: ClientConfig,
    all: bool | NotGiven = NOT_GIVEN,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteBouncesResponse:
    """Deletes bounce records selected by a deletion flag or bounce identifiers. Use `all`
    to indicate bulk deletion or `id` to provide the bounce identifiers to delete.

    handles deletion of bounce records.

    Args:
        all: flag for multiple bounce record deletion
        id: list of bounce ids to delete
    """

    _resp = await sdk_request(
        "DELETE",
        "/bounces",
        params=serialize_query([("all", all, "form", True), ("id", id, "form", True)]),
        operation_id="delete_bounces",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteBouncesResponse"), DeleteBouncesResponse
    )


def delete_bounces_sync(
    _client_config: ClientConfig,
    all: bool | NotGiven = NOT_GIVEN,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteBouncesResponse:
    """Deletes bounce records selected by a deletion flag or bounce identifiers. Use `all`
    to indicate bulk deletion or `id` to provide the bounce identifiers to delete.

    handles deletion of bounce records.

    Args:
        all: flag for multiple bounce record deletion
        id: list of bounce ids to delete
    """

    _resp = sdk_request_sync(
        "DELETE",
        "/bounces",
        params=serialize_query([("all", all, "form", True), ("id", id, "form", True)]),
        operation_id="delete_bounces",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteBouncesResponse"), DeleteBouncesResponse
    )


async def get_bounce_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetBounceByIdResponse:
    """Retrieves a bounce record by its identifier. Supply the record's numeric `id` to
    look up the bounce you want to retrieve.

    handles retrieval of bounce record by id

    Args:
        id: The id value of the bounce you want to retreive.
    """

    _resp = await sdk_request(
        "GET",
        f"/bounces/{encode_path_segment(id)}",
        operation_id="get_bounce_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetBounceByIdResponse"), GetBounceByIdResponse
    )


def get_bounce_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetBounceByIdResponse:
    """Retrieves a bounce record by its identifier. Supply the record's numeric `id` to
    look up the bounce you want to retrieve.

    handles retrieval of bounce record by id

    Args:
        id: The id value of the bounce you want to retreive.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/bounces/{encode_path_segment(id)}",
        operation_id="get_bounce_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetBounceByIdResponse"), GetBounceByIdResponse
    )


async def delete_bounce_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteBounceByIdResponse:
    """Deletes a single bounce identified by its ID in the URI. Supply the integer `id` of
    the bounce you want to remove.

    handles bounce deletion, either a single one (ID in the URI), or a list.

    Args:
        id: The id value of the bounce you want to delete.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/bounces/{encode_path_segment(id)}",
        operation_id="delete_bounce_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteBounceByIdResponse"), DeleteBounceByIdResponse
    )


def delete_bounce_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteBounceByIdResponse:
    """Deletes a single bounce identified by its ID in the URI. Supply the integer `id` of
    the bounce you want to remove.

    handles bounce deletion, either a single one (ID in the URI), or a list.

    Args:
        id: The id value of the bounce you want to delete.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/bounces/{encode_path_segment(id)}",
        operation_id="delete_bounce_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteBounceByIdResponse"), DeleteBounceByIdResponse
    )


__all__ = [
    "delete_bounce_by_id",
    "delete_bounce_by_id_sync",
    "delete_bounces",
    "delete_bounces_sync",
    "get_bounce_by_id",
    "get_bounce_by_id_sync",
    "get_bounces",
    "get_bounces_sync",
]
