# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    UploadFile,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    GetImportSubscriberLogsResponse,
    GetImportSubscribersResponse,
    ImportSubscribersResponse,
    StopImportSubscribersResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_import_subscribers(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetImportSubscribersResponse:
    """Retrieves the current status of subscriber imports. Use this endpoint to check the
    import status without submitting an import request.

    returns import status.
    """

    _resp = await sdk_request(
        "GET",
        "/import/subscribers",
        operation_id="get_import_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetImportSubscribersResponse"),
        GetImportSubscribersResponse,
    )


def get_import_subscribers_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetImportSubscribersResponse:
    """Retrieves the current status of subscriber imports. Use this endpoint to check the
    import status without submitting an import request.

    returns import status.
    """

    _resp = sdk_request_sync(
        "GET",
        "/import/subscribers",
        operation_id="get_import_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetImportSubscribersResponse"),
        GetImportSubscribersResponse,
    )


async def import_subscribers(
    _client_config: ClientConfig,
    params: str | NotGiven = NOT_GIVEN,
    file: UploadFile | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ImportSubscribersResponse:
    """Uploads and imports a ZIP file containing one or more CSV files of subscribers. Send
    the upload as `multipart/form-data`; `params` can contain import settings as a JSON
    string. Use GET /import/subscribers to retrieve import status.

    handles the uploading and bulk importing of a ZIP file of one or more CSV files.

    Args:
        params: JSON string containing import parameters for more detail
            https://listmonk.app/docs/apis/import/#params-json-string
        file: File for upload.
    """

    _resp = await sdk_request(
        "POST",
        "/import/subscribers",
        json=omit_unset(
            {
                "params": (NOT_GIVEN if params is NOT_GIVEN else to_wire(params, "str")),
                "file": file,
            }
        ),
        content_type="multipart/form-data",
        operation_id="import_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ImportSubscribersResponse"), ImportSubscribersResponse
    )


def import_subscribers_sync(
    _client_config: ClientConfig,
    params: str | NotGiven = NOT_GIVEN,
    file: UploadFile | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ImportSubscribersResponse:
    """Uploads and imports a ZIP file containing one or more CSV files of subscribers. Send
    the upload as `multipart/form-data`; `params` can contain import settings as a JSON
    string. Use GET /import/subscribers to retrieve import status.

    handles the uploading and bulk importing of a ZIP file of one or more CSV files.

    Args:
        params: JSON string containing import parameters for more detail
            https://listmonk.app/docs/apis/import/#params-json-string
        file: File for upload.
    """

    _resp = sdk_request_sync(
        "POST",
        "/import/subscribers",
        json=omit_unset(
            {
                "params": (NOT_GIVEN if params is NOT_GIVEN else to_wire(params, "str")),
                "file": file,
            }
        ),
        content_type="multipart/form-data",
        operation_id="import_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ImportSubscribersResponse"), ImportSubscribersResponse
    )


async def stop_import_subscribers(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> StopImportSubscribersResponse:
    """Sends a stop signal to the subscriber importer. Use this endpoint to request that an
    ongoing import stop.

    sends a stop signal to the importer.
    """

    _resp = await sdk_request(
        "DELETE",
        "/import/subscribers",
        operation_id="stop_import_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "StopImportSubscribersResponse"),
        StopImportSubscribersResponse,
    )


def stop_import_subscribers_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> StopImportSubscribersResponse:
    """Sends a stop signal to the subscriber importer. Use this endpoint to request that an
    ongoing import stop.

    sends a stop signal to the importer.
    """

    _resp = sdk_request_sync(
        "DELETE",
        "/import/subscribers",
        operation_id="stop_import_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "StopImportSubscribersResponse"),
        StopImportSubscribersResponse,
    )


async def get_import_subscriber_logs(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetImportSubscriberLogsResponse:
    """Retrieves logs from an ongoing subscriber import. Use this endpoint to inspect
    import activity while the import is running.

    returns import logs from an ongoing import
    """

    _resp = await sdk_request(
        "GET",
        "/import/subscribers/logs",
        operation_id="get_import_subscriber_logs",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetImportSubscriberLogsResponse"),
        GetImportSubscriberLogsResponse,
    )


def get_import_subscriber_logs_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetImportSubscriberLogsResponse:
    """Retrieves logs from an ongoing subscriber import. Use this endpoint to inspect
    import activity while the import is running.

    returns import logs from an ongoing import
    """

    _resp = sdk_request_sync(
        "GET",
        "/import/subscribers/logs",
        operation_id="get_import_subscriber_logs",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetImportSubscriberLogsResponse"),
        GetImportSubscriberLogsResponse,
    )


__all__ = [
    "get_import_subscriber_logs",
    "get_import_subscriber_logs_sync",
    "get_import_subscribers",
    "get_import_subscribers_sync",
    "import_subscribers",
    "import_subscribers_sync",
    "stop_import_subscribers",
    "stop_import_subscribers_sync",
]
