# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from listmonk_unofficial_sdk.types import (
    CreateListResponse,
    DeleteListByIdResponse,
    GetListByIdResponse,
    GetListsResponse,
    UpdateListByIdResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_lists(
    _client_config: ClientConfig,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    query: str | NotGiven = NOT_GIVEN,
    order_by: Literal["name", "status", "created_at", "updated_at"] | str | NotGiven = NOT_GIVEN,
    order: Literal["ASC", "DESC"] | str | NotGiven = NOT_GIVEN,
    minimal: bool | NotGiven = NOT_GIVEN,
    tag: list[str] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetListsResponse:
    """Lists mailing lists with metadata such as subscriber counts. Use `query` to search
    by list name, `tag` to filter by tags, and `order_by` and `order` to control
    sorting. Use `page` and `per_page` to paginate the results.

    retrieves lists with additional metadata like subscriber counts. This may be slow.

    Args:
        page: total number of pages
        per_page: number of items per page
        query: Optional string to search a list by name.
        order_by: Field to sort results by. name|status|created_at|updated_at
        order: ASC|DESC Sort by ascending or descending order.
        minimal: When set to true, returns response without body content
        tag: Tags to filter lists. Repeat in the query for multiple values.
    """

    _resp = await sdk_request(
        "GET",
        "/lists",
        params=serialize_query(
            [
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("query", query, "form", True),
                ("order_by", order_by, "form", True),
                ("order", order, "form", True),
                ("minimal", minimal, "form", True),
                ("tag", tag, "form", True),
            ]
        ),
        operation_id="get_lists",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetListsResponse"), GetListsResponse
    )


def get_lists_sync(
    _client_config: ClientConfig,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    query: str | NotGiven = NOT_GIVEN,
    order_by: Literal["name", "status", "created_at", "updated_at"] | str | NotGiven = NOT_GIVEN,
    order: Literal["ASC", "DESC"] | str | NotGiven = NOT_GIVEN,
    minimal: bool | NotGiven = NOT_GIVEN,
    tag: list[str] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetListsResponse:
    """Lists mailing lists with metadata such as subscriber counts. Use `query` to search
    by list name, `tag` to filter by tags, and `order_by` and `order` to control
    sorting. Use `page` and `per_page` to paginate the results.

    retrieves lists with additional metadata like subscriber counts. This may be slow.

    Args:
        page: total number of pages
        per_page: number of items per page
        query: Optional string to search a list by name.
        order_by: Field to sort results by. name|status|created_at|updated_at
        order: ASC|DESC Sort by ascending or descending order.
        minimal: When set to true, returns response without body content
        tag: Tags to filter lists. Repeat in the query for multiple values.
    """

    _resp = sdk_request_sync(
        "GET",
        "/lists",
        params=serialize_query(
            [
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("query", query, "form", True),
                ("order_by", order_by, "form", True),
                ("order", order, "form", True),
                ("minimal", minimal, "form", True),
                ("tag", tag, "form", True),
            ]
        ),
        operation_id="get_lists",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetListsResponse"), GetListsResponse
    )


async def create_list(
    _client_config: ClientConfig,
    name: str | NotGiven = NOT_GIVEN,
    type: Literal["public", "private"] | str | NotGiven = NOT_GIVEN,
    optin: Literal["single", "double"] | str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    description: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateListResponse:
    """Creates a mailing list from the supplied list details. Provide `name`, `type`,
    `optin`, `tags`, or `description` as needed; `type` and `optin` have defined
    accepted values. The response includes the created list and its metadata.

    handles list creation

    Args:
        name: Optional `string` value serialized in the `name` wire field.
        type: Optional enumerated value serialized in the `type` wire field.
        optin: Optional enumerated value serialized in the `optin` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        description: Optional `string` value serialized in the `description` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/lists",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["public", "private"] | str')
                ),
                "optin": (
                    NOT_GIVEN
                    if optin is NOT_GIVEN
                    else to_wire(optin, 'Literal["single", "double"] | str')
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
            }
        ),
        operation_id="create_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateListResponse"), CreateListResponse
    )


def create_list_sync(
    _client_config: ClientConfig,
    name: str | NotGiven = NOT_GIVEN,
    type: Literal["public", "private"] | str | NotGiven = NOT_GIVEN,
    optin: Literal["single", "double"] | str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    description: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateListResponse:
    """Creates a mailing list from the supplied list details. Provide `name`, `type`,
    `optin`, `tags`, or `description` as needed; `type` and `optin` have defined
    accepted values. The response includes the created list and its metadata.

    handles list creation

    Args:
        name: Optional `string` value serialized in the `name` wire field.
        type: Optional enumerated value serialized in the `type` wire field.
        optin: Optional enumerated value serialized in the `optin` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        description: Optional `string` value serialized in the `description` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/lists",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["public", "private"] | str')
                ),
                "optin": (
                    NOT_GIVEN
                    if optin is NOT_GIVEN
                    else to_wire(optin, 'Literal["single", "double"] | str')
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
            }
        ),
        operation_id="create_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateListResponse"), CreateListResponse
    )


async def get_list_by_id(
    _client_config: ClientConfig,
    list_id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetListByIdResponse:
    """Retrieves a mailing list with metadata such as its subscriber count. Supply the
    list's integer `list_id` to identify the list to retrieve.

    retrieves lists with additional metadata like subscriber counts. This may be slow.

    Args:
        list_id: The id value of the list you want to retreive.
    """

    _resp = await sdk_request(
        "GET",
        f"/lists/{encode_path_segment(list_id)}",
        operation_id="get_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetListByIdResponse"), GetListByIdResponse
    )


def get_list_by_id_sync(
    _client_config: ClientConfig,
    list_id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetListByIdResponse:
    """Retrieves a mailing list with metadata such as its subscriber count. Supply the
    list's integer `list_id` to identify the list to retrieve.

    retrieves lists with additional metadata like subscriber counts. This may be slow.

    Args:
        list_id: The id value of the list you want to retreive.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/lists/{encode_path_segment(list_id)}",
        operation_id="get_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetListByIdResponse"), GetListByIdResponse
    )


async def update_list_by_id(
    _client_config: ClientConfig,
    list_id: int,
    id: int | NotGiven = NOT_GIVEN,
    created_at: str | NotGiven = NOT_GIVEN,
    updated_at: str | NotGiven = NOT_GIVEN,
    uuid: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    optin: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    subscriber_count: int | NotGiven = NOT_GIVEN,
    description: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateListByIdResponse:
    """Replaces the supplied fields on a mailing list identified by its ID. The request
    body can include list settings, tags, and metadata; all body fields are optional in
    the schema.

    handles list modification

    Args:
        list_id: The id value of the list you want to update
        id: Optional `integer` value serialized in the `id` wire field.
        created_at: Optional `string` value serialized in the `created_at` wire field.
        updated_at: Optional `string` value serialized in the `updated_at` wire field.
        uuid: Optional `string` value serialized in the `uuid` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        optin: Optional `string` value serialized in the `optin` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        subscriber_count: Optional `integer` value serialized in the `subscriber_count` wire field.
        description: Optional `string` value serialized in the `description` wire field.
    """

    _resp = await sdk_request(
        "PUT",
        f"/lists/{encode_path_segment(list_id)}",
        json=omit_unset(
            {
                "id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "int")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "str")
                ),
                "updated_at": (
                    NOT_GIVEN if updated_at is NOT_GIVEN else to_wire(updated_at, "str")
                ),
                "uuid": (NOT_GIVEN if uuid is NOT_GIVEN else to_wire(uuid, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "optin": (NOT_GIVEN if optin is NOT_GIVEN else to_wire(optin, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "subscriber_count": (
                    NOT_GIVEN if subscriber_count is NOT_GIVEN else to_wire(subscriber_count, "int")
                ),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
            }
        ),
        operation_id="update_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateListByIdResponse"), UpdateListByIdResponse
    )


def update_list_by_id_sync(
    _client_config: ClientConfig,
    list_id: int,
    id: int | NotGiven = NOT_GIVEN,
    created_at: str | NotGiven = NOT_GIVEN,
    updated_at: str | NotGiven = NOT_GIVEN,
    uuid: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    optin: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    subscriber_count: int | NotGiven = NOT_GIVEN,
    description: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateListByIdResponse:
    """Replaces the supplied fields on a mailing list identified by its ID. The request
    body can include list settings, tags, and metadata; all body fields are optional in
    the schema.

    handles list modification

    Args:
        list_id: The id value of the list you want to update
        id: Optional `integer` value serialized in the `id` wire field.
        created_at: Optional `string` value serialized in the `created_at` wire field.
        updated_at: Optional `string` value serialized in the `updated_at` wire field.
        uuid: Optional `string` value serialized in the `uuid` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        optin: Optional `string` value serialized in the `optin` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        subscriber_count: Optional `integer` value serialized in the `subscriber_count` wire field.
        description: Optional `string` value serialized in the `description` wire field.
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/lists/{encode_path_segment(list_id)}",
        json=omit_unset(
            {
                "id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "int")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "str")
                ),
                "updated_at": (
                    NOT_GIVEN if updated_at is NOT_GIVEN else to_wire(updated_at, "str")
                ),
                "uuid": (NOT_GIVEN if uuid is NOT_GIVEN else to_wire(uuid, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "optin": (NOT_GIVEN if optin is NOT_GIVEN else to_wire(optin, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "subscriber_count": (
                    NOT_GIVEN if subscriber_count is NOT_GIVEN else to_wire(subscriber_count, "int")
                ),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
            }
        ),
        operation_id="update_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateListByIdResponse"), UpdateListByIdResponse
    )


async def delete_list_by_id(
    _client_config: ClientConfig,
    list_id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteListByIdResponse:
    """Deletes a mailing list identified by its ID in the URI. Supply the list's integer
    `list_id` to specify which list to remove.

    handles list deletion, either a single one (ID in the URI), or a list.

    Args:
        list_id: The id value of the lists you want to delete.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/lists/{encode_path_segment(list_id)}",
        operation_id="delete_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteListByIdResponse"), DeleteListByIdResponse
    )


def delete_list_by_id_sync(
    _client_config: ClientConfig,
    list_id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteListByIdResponse:
    """Deletes a mailing list identified by its ID in the URI. Supply the list's integer
    `list_id` to specify which list to remove.

    handles list deletion, either a single one (ID in the URI), or a list.

    Args:
        list_id: The id value of the lists you want to delete.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/lists/{encode_path_segment(list_id)}",
        operation_id="delete_list_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteListByIdResponse"), DeleteListByIdResponse
    )


__all__ = [
    "create_list",
    "create_list_sync",
    "delete_list_by_id",
    "delete_list_by_id_sync",
    "get_list_by_id",
    "get_list_by_id_sync",
    "get_lists",
    "get_lists_sync",
    "update_list_by_id",
    "update_list_by_id_sync",
]
