# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    ClientConfig,
    RequestOptions,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import GetLogsResponse
from listmonk_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_logs(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetLogsResponse:
    """Lists log entries currently stored in the log buffer. Use this endpoint to retrieve
    the buffered entries as an array of strings.

    returns the log entries stored in the log buffer
    """

    _resp = await sdk_request(
        "GET",
        "/logs",
        operation_id="get_logs",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetLogsResponse"), GetLogsResponse
    )


def get_logs_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetLogsResponse:
    """Lists log entries currently stored in the log buffer. Use this endpoint to retrieve
    the buffered entries as an array of strings.

    returns the log entries stored in the log buffer
    """

    _resp = sdk_request_sync(
        "GET",
        "/logs",
        operation_id="get_logs",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetLogsResponse"), GetLogsResponse
    )


__all__ = [
    "get_logs",
    "get_logs_sync",
]
