# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    DeleteCampaignAnalyticsByTypeResponse,
    DeleteGCSubscribersResponse,
    DeleteUnconfirmedSubscriptionsResponse,
)
from listmonk_unofficial_sdk.validation import validate_date
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def delete_gc_subscribers(
    _client_config: ClientConfig,
    type: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteGCSubscribersResponse:
    """Deletes orphaned or blocklisted subscribers through garbage collection. Specify the
    subscriber category to collect with the `type` path parameter.

    garbage collects (deletes) orphaned or blocklisted subscribers.

    Args:
        type: type of GC collected subscribers
    """

    _resp = await sdk_request(
        "DELETE",
        f"/maintenance/subscribers/{encode_path_segment(type)}",
        operation_id="delete_gc_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteGCSubscribersResponse"),
        DeleteGCSubscribersResponse,
    )


def delete_gc_subscribers_sync(
    _client_config: ClientConfig,
    type: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteGCSubscribersResponse:
    """Deletes orphaned or blocklisted subscribers through garbage collection. Specify the
    subscriber category to collect with the `type` path parameter.

    garbage collects (deletes) orphaned or blocklisted subscribers.

    Args:
        type: type of GC collected subscribers
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/maintenance/subscribers/{encode_path_segment(type)}",
        operation_id="delete_gc_subscribers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteGCSubscribersResponse"),
        DeleteGCSubscribersResponse,
    )


async def delete_campaign_analytics_by_type(
    _client_config: ClientConfig,
    type: str,
    before_date: datetime.date | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteCampaignAnalyticsByTypeResponse:
    """Deletes campaign analytics of the specified type. Use `before_date` to set the date
    cutoff for the analytics to remove.

    garbage collects (deletes) campaign analytics.

    Args:
        type: type of GC collected subscribers
    """

    if not isinstance(before_date, NotGiven) and before_date is not None:
        validate_date("before_date", before_date)

    _resp = await sdk_request(
        "DELETE",
        f"/maintenance/analytics/{encode_path_segment(type)}",
        json=omit_unset(
            {
                "before_date": (
                    NOT_GIVEN if before_date is NOT_GIVEN else to_wire(before_date, "datetime.date")
                ),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="delete_campaign_analytics_by_type",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteCampaignAnalyticsByTypeResponse"),
        DeleteCampaignAnalyticsByTypeResponse,
    )


def delete_campaign_analytics_by_type_sync(
    _client_config: ClientConfig,
    type: str,
    before_date: datetime.date | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteCampaignAnalyticsByTypeResponse:
    """Deletes campaign analytics of the specified type. Use `before_date` to set the date
    cutoff for the analytics to remove.

    garbage collects (deletes) campaign analytics.

    Args:
        type: type of GC collected subscribers
    """

    if not isinstance(before_date, NotGiven) and before_date is not None:
        validate_date("before_date", before_date)

    _resp = sdk_request_sync(
        "DELETE",
        f"/maintenance/analytics/{encode_path_segment(type)}",
        json=omit_unset(
            {
                "before_date": (
                    NOT_GIVEN if before_date is NOT_GIVEN else to_wire(before_date, "datetime.date")
                ),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="delete_campaign_analytics_by_type",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteCampaignAnalyticsByTypeResponse"),
        DeleteCampaignAnalyticsByTypeResponse,
    )


async def delete_unconfirmed_subscriptions(
    _client_config: ClientConfig,
    before_date: datetime.date | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteUnconfirmedSubscriptionsResponse:
    """Deletes unconfirmed subscriptions through garbage collection. Use `before_date` to
    set the cutoff date for the subscriptions to remove.

    garbage collects (deletes) orphaned or blocklisted subscribers.
    """

    if not isinstance(before_date, NotGiven) and before_date is not None:
        validate_date("before_date", before_date)

    _resp = await sdk_request(
        "DELETE",
        "/maintenance/subscriptions/unconfirmed",
        json=omit_unset(
            {
                "before_date": (
                    NOT_GIVEN if before_date is NOT_GIVEN else to_wire(before_date, "datetime.date")
                ),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="delete_unconfirmed_subscriptions",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteUnconfirmedSubscriptionsResponse"),
        DeleteUnconfirmedSubscriptionsResponse,
    )


def delete_unconfirmed_subscriptions_sync(
    _client_config: ClientConfig,
    before_date: datetime.date | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteUnconfirmedSubscriptionsResponse:
    """Deletes unconfirmed subscriptions through garbage collection. Use `before_date` to
    set the cutoff date for the subscriptions to remove.

    garbage collects (deletes) orphaned or blocklisted subscribers.
    """

    if not isinstance(before_date, NotGiven) and before_date is not None:
        validate_date("before_date", before_date)

    _resp = sdk_request_sync(
        "DELETE",
        "/maintenance/subscriptions/unconfirmed",
        json=omit_unset(
            {
                "before_date": (
                    NOT_GIVEN if before_date is NOT_GIVEN else to_wire(before_date, "datetime.date")
                ),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="delete_unconfirmed_subscriptions",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteUnconfirmedSubscriptionsResponse"),
        DeleteUnconfirmedSubscriptionsResponse,
    )


__all__ = [
    "delete_campaign_analytics_by_type",
    "delete_campaign_analytics_by_type_sync",
    "delete_gc_subscribers",
    "delete_gc_subscribers_sync",
    "delete_unconfirmed_subscriptions",
    "delete_unconfirmed_subscriptions_sync",
]
