# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    DeleteMediaByIdResponse,
    GetMediaByIdResponse,
    GetMediaResponse,
    UploadMediaResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_media(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetMediaResponse:
    """Lists uploaded media. Use this endpoint to retrieve the available media records and
    their file details.

    handles retrieval of uploaded media.
    """

    _resp = await sdk_request(
        "GET",
        "/media",
        operation_id="get_media",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetMediaResponse"), GetMediaResponse
    )


def get_media_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetMediaResponse:
    """Lists uploaded media. Use this endpoint to retrieve the available media records and
    their file details.

    handles retrieval of uploaded media.
    """

    _resp = sdk_request_sync(
        "GET",
        "/media",
        operation_id="get_media",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetMediaResponse"), GetMediaResponse
    )


async def upload_media(
    _client_config: ClientConfig,
    body: bytes | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UploadMediaResponse:
    """Uploads a media file. Send the file as a binary value using `multipart/form-data`;
    the request body schema does not define additional metadata fields.

    handles media file uploads.
    """

    _resp = await sdk_request(
        "POST",
        "/media",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "bytes")),
        content_type="multipart/form-data",
        operation_id="upload_media",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UploadMediaResponse"), UploadMediaResponse
    )


def upload_media_sync(
    _client_config: ClientConfig,
    body: bytes | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UploadMediaResponse:
    """Uploads a media file. Send the file as a binary value using `multipart/form-data`;
    the request body schema does not define additional metadata fields.

    handles media file uploads.
    """

    _resp = sdk_request_sync(
        "POST",
        "/media",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "bytes")),
        content_type="multipart/form-data",
        operation_id="upload_media",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UploadMediaResponse"), UploadMediaResponse
    )


async def get_media_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetMediaByIdResponse:
    """Retrieves an uploaded media record by its identifier. Use the media identifier to
    access the record's file details and URLs.

    handles retrieval of uploaded media.

    Args:
        id: media file id
    """

    _resp = await sdk_request(
        "GET",
        f"/media/{encode_path_segment(id)}",
        operation_id="get_media_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetMediaByIdResponse"), GetMediaByIdResponse
    )


def get_media_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> GetMediaByIdResponse:
    """Retrieves an uploaded media record by its identifier. Use the media identifier to
    access the record's file details and URLs.

    handles retrieval of uploaded media.

    Args:
        id: media file id
    """

    _resp = sdk_request_sync(
        "GET",
        f"/media/{encode_path_segment(id)}",
        operation_id="get_media_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetMediaByIdResponse"), GetMediaByIdResponse
    )


async def delete_media_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteMediaByIdResponse:
    """Deletes an uploaded media record. Supply the media identifier for the record you
    want to remove.

    handles deletion of uploaded media.

    Args:
        id: The id value of the list you want to delete.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/media/{encode_path_segment(id)}",
        operation_id="delete_media_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteMediaByIdResponse"), DeleteMediaByIdResponse
    )


def delete_media_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteMediaByIdResponse:
    """Deletes an uploaded media record. Supply the media identifier for the record you
    want to remove.

    handles deletion of uploaded media.

    Args:
        id: The id value of the list you want to delete.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/media/{encode_path_segment(id)}",
        operation_id="delete_media_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteMediaByIdResponse"), DeleteMediaByIdResponse
    )


__all__ = [
    "delete_media_by_id",
    "delete_media_by_id_sync",
    "get_media",
    "get_media_by_id",
    "get_media_by_id_sync",
    "get_media_sync",
    "upload_media",
    "upload_media_sync",
]
