# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    ClientConfig,
    RequestOptions,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    GetDashboardChartsResponse,
    GetDashboardCountsResponse,
    GetHealthCheckResponse,
    GetI18nLangResponse,
    GetServerConfigResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_health_check(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetHealthCheckResponse:
    """Returns the service health-check result. Use the boolean `data` value to determine
    whether the service is responding.

    healthcheck endpoint
    """

    _resp = await sdk_request(
        "GET",
        "/health",
        operation_id="get_health_check",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetHealthCheckResponse"), GetHealthCheckResponse
    )


def get_health_check_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetHealthCheckResponse:
    """Returns the service health-check result. Use the boolean `data` value to determine
    whether the service is responding.

    healthcheck endpoint
    """

    _resp = sdk_request_sync(
        "GET",
        "/health",
        operation_id="get_health_check",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetHealthCheckResponse"), GetHealthCheckResponse
    )


async def get_server_config(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetServerConfigResponse:
    """Returns the general server configuration. Use this endpoint to retrieve the
    configuration object exposed by the server.

    returns general server config.
    """

    _resp = await sdk_request(
        "GET",
        "/config",
        operation_id="get_server_config",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetServerConfigResponse"), GetServerConfigResponse
    )


def get_server_config_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetServerConfigResponse:
    """Returns the general server configuration. Use this endpoint to retrieve the
    configuration object exposed by the server.

    returns general server config.
    """

    _resp = sdk_request_sync(
        "GET",
        "/config",
        operation_id="get_server_config",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetServerConfigResponse"), GetServerConfigResponse
    )


async def get_i18n_lang(
    _client_config: ClientConfig,
    lang: str,
    *,
    request_options: RequestOptions | None = None,
) -> GetI18nLangResponse:
    """Returns the JSON language pack for the requested language code. Supply `lang` to
    select the language pack to retrieve.

    returns the JSON language pack given the language code

    Args:
        lang: JSON language pack required
    """

    _resp = await sdk_request(
        "GET",
        f"/lang/{encode_path_segment(lang)}",
        operation_id="get_i18n_lang",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetI18nLangResponse"), GetI18nLangResponse
    )


def get_i18n_lang_sync(
    _client_config: ClientConfig,
    lang: str,
    *,
    request_options: RequestOptions | None = None,
) -> GetI18nLangResponse:
    """Returns the JSON language pack for the requested language code. Supply `lang` to
    select the language pack to retrieve.

    returns the JSON language pack given the language code

    Args:
        lang: JSON language pack required
    """

    _resp = sdk_request_sync(
        "GET",
        f"/lang/{encode_path_segment(lang)}",
        operation_id="get_i18n_lang",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetI18nLangResponse"), GetI18nLangResponse
    )


async def get_dashboard_charts(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetDashboardChartsResponse:
    """Returns chart data points for the dashboard. Use the `link_clicks` and
    `campaign_views` data to render the corresponding dashboard charts.

    returns chart data points to render on the dashboard.
    """

    _resp = await sdk_request(
        "GET",
        "/dashboard/charts",
        operation_id="get_dashboard_charts",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetDashboardChartsResponse"),
        GetDashboardChartsResponse,
    )


def get_dashboard_charts_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetDashboardChartsResponse:
    """Returns chart data points for the dashboard. Use the `link_clicks` and
    `campaign_views` data to render the corresponding dashboard charts.

    returns chart data points to render on the dashboard.
    """

    _resp = sdk_request_sync(
        "GET",
        "/dashboard/charts",
        operation_id="get_dashboard_charts",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetDashboardChartsResponse"),
        GetDashboardChartsResponse,
    )


async def get_dashboard_counts(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetDashboardCountsResponse:
    """Returns statistics counts for the dashboard. Use the returned counts to display
    summary statistics in the dashboard.

    returns stats counts to show on the dashboard
    """

    _resp = await sdk_request(
        "GET",
        "/dashboard/counts",
        operation_id="get_dashboard_counts",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetDashboardCountsResponse"),
        GetDashboardCountsResponse,
    )


def get_dashboard_counts_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetDashboardCountsResponse:
    """Returns statistics counts for the dashboard. Use the returned counts to display
    summary statistics in the dashboard.

    returns stats counts to show on the dashboard
    """

    _resp = sdk_request_sync(
        "GET",
        "/dashboard/counts",
        operation_id="get_dashboard_counts",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetDashboardCountsResponse"),
        GetDashboardCountsResponse,
    )


__all__ = [
    "get_dashboard_charts",
    "get_dashboard_charts_sync",
    "get_dashboard_counts",
    "get_dashboard_counts_sync",
    "get_health_check",
    "get_health_check_sync",
    "get_i18n_lang",
    "get_i18n_lang_sync",
    "get_server_config",
    "get_server_config_sync",
]
