# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import HandlePublicSubscriptionResponse
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_public_lists(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> list[dict[str, Any]]:
    """Lists the public mailing lists with their minimal identifying fields. Use this
    endpoint to retrieve each list's `uuid` and `name` for display or subscription
    workflows.

    returns the list of public lists with minimal fields
    """

    _resp = await sdk_request(
        "GET",
        "/public/lists",
        operation_id="get_public_lists",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, list[dict[str, Any]])


def get_public_lists_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> list[dict[str, Any]]:
    """Lists the public mailing lists with their minimal identifying fields. Use this
    endpoint to retrieve each list's `uuid` and `name` for display or subscription
    workflows.

    returns the list of public lists with minimal fields
    """

    _resp = sdk_request_sync(
        "GET",
        "/public/lists",
        operation_id="get_public_lists",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, list[dict[str, Any]])


async def handle_public_subscription(
    _client_config: ClientConfig,
    name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    list_uuids: list[str] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> HandlePublicSubscriptionResponse:
    """Submits a subscription request through the public API. Include `email` and
    optionally `name` and `list_uuids` in the request body; the schema does not mark any
    fields as required. A 200 response indicates whether opt-in is required in
    `has_optin`.

    handles subscription requests coming from public API calls.
    """

    _resp = await sdk_request(
        "POST",
        "/public/subscription",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "list_uuids": (
                    NOT_GIVEN if list_uuids is NOT_GIVEN else to_wire(list_uuids, "list[str]")
                ),
            }
        ),
        operation_id="handle_public_subscription",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "HandlePublicSubscriptionResponse"),
        HandlePublicSubscriptionResponse,
    )


def handle_public_subscription_sync(
    _client_config: ClientConfig,
    name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    list_uuids: list[str] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> HandlePublicSubscriptionResponse:
    """Submits a subscription request through the public API. Include `email` and
    optionally `name` and `list_uuids` in the request body; the schema does not mark any
    fields as required. A 200 response indicates whether opt-in is required in
    `has_optin`.

    handles subscription requests coming from public API calls.
    """

    _resp = sdk_request_sync(
        "POST",
        "/public/subscription",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "list_uuids": (
                    NOT_GIVEN if list_uuids is NOT_GIVEN else to_wire(list_uuids, "list[str]")
                ),
            }
        ),
        operation_id="handle_public_subscription",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "HandlePublicSubscriptionResponse"),
        HandlePublicSubscriptionResponse,
    )


__all__ = [
    "get_public_lists",
    "get_public_lists_sync",
    "handle_public_subscription",
    "handle_public_subscription_sync",
]
