# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import TransactWithSubscriberResponse
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def transact_with_subscriber(
    _client_config: ClientConfig,
    subscriber_email: str | NotGiven = NOT_GIVEN,
    subscriber_id: int | NotGiven = NOT_GIVEN,
    template_id: int | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    data: dict[str, Any] | NotGiven = NOT_GIVEN,
    headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TransactWithSubscriberResponse:
    """Sends a transactional message to a subscriber. Use `subscriber_email` or
    `subscriber_id` to identify the recipient, and provide message content or a
    `template_id` as needed.

    send message to a subscriber

    Args:
        subscriber_email: Optional `string` value serialized in the `subscriber_email` wire field.
        subscriber_id: Optional `integer` value serialized in the `subscriber_id` wire field.
        template_id: Optional `integer` value serialized in the `template_id` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        data: Optional object value serialized in the `data` wire field.
        headers: Optional array value serialized in the `headers` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/tx",
        json=omit_unset(
            {
                "subscriber_email": (
                    NOT_GIVEN if subscriber_email is NOT_GIVEN else to_wire(subscriber_email, "str")
                ),
                "subscriber_id": (
                    NOT_GIVEN if subscriber_id is NOT_GIVEN else to_wire(subscriber_id, "int")
                ),
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "data": (NOT_GIVEN if data is NOT_GIVEN else to_wire(data, "dict[str, Any]")),
                "headers": (
                    NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[dict[str, Any]]")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
            }
        ),
        operation_id="transact_with_subscriber",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TransactWithSubscriberResponse"),
        TransactWithSubscriberResponse,
    )


def transact_with_subscriber_sync(
    _client_config: ClientConfig,
    subscriber_email: str | NotGiven = NOT_GIVEN,
    subscriber_id: int | NotGiven = NOT_GIVEN,
    template_id: int | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    data: dict[str, Any] | NotGiven = NOT_GIVEN,
    headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TransactWithSubscriberResponse:
    """Sends a transactional message to a subscriber. Use `subscriber_email` or
    `subscriber_id` to identify the recipient, and provide message content or a
    `template_id` as needed.

    send message to a subscriber

    Args:
        subscriber_email: Optional `string` value serialized in the `subscriber_email` wire field.
        subscriber_id: Optional `integer` value serialized in the `subscriber_id` wire field.
        template_id: Optional `integer` value serialized in the `template_id` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        data: Optional object value serialized in the `data` wire field.
        headers: Optional array value serialized in the `headers` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/tx",
        json=omit_unset(
            {
                "subscriber_email": (
                    NOT_GIVEN if subscriber_email is NOT_GIVEN else to_wire(subscriber_email, "str")
                ),
                "subscriber_id": (
                    NOT_GIVEN if subscriber_id is NOT_GIVEN else to_wire(subscriber_id, "int")
                ),
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "data": (NOT_GIVEN if data is NOT_GIVEN else to_wire(data, "dict[str, Any]")),
                "headers": (
                    NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[dict[str, Any]]")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
            }
        ),
        operation_id="transact_with_subscriber",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TransactWithSubscriberResponse"),
        TransactWithSubscriberResponse,
    )


__all__ = [
    "transact_with_subscriber",
    "transact_with_subscriber_sync",
]
