# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from ._part001 import get_settings, get_settings_sync, update_settings, update_settings_sync
from ._part002 import test_smtp_settings, test_smtp_settings_sync

__all__ = [
    "get_settings",
    "get_settings_sync",
    "test_smtp_settings",
    "test_smtp_settings_sync",
    "update_settings",
    "update_settings_sync",
]
