# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    GetSettingsResponse,
    MailBoxBounces,
    SMTPSettings,
    UpdateSettingsResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_settings(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetSettingsResponse:
    """Returns the settings stored in the database. Use this endpoint to retrieve the
    server's current configuration settings.

    returns settings from DB
    """

    _resp = await sdk_request(
        "GET",
        "/settings",
        operation_id="get_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSettingsResponse"), GetSettingsResponse
    )


def get_settings_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetSettingsResponse:
    """Returns the settings stored in the database. Use this endpoint to retrieve the
    server's current configuration settings.

    returns settings from DB
    """

    _resp = sdk_request_sync(
        "GET",
        "/settings",
        operation_id="get_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetSettingsResponse"), GetSettingsResponse
    )


async def update_settings(
    _client_config: ClientConfig,
    app_site_name: str | NotGiven = NOT_GIVEN,
    app_root_url: str | NotGiven = NOT_GIVEN,
    app_logo_url: str | NotGiven = NOT_GIVEN,
    app_favicon_url: str | NotGiven = NOT_GIVEN,
    app_from_email: str | NotGiven = NOT_GIVEN,
    app_notify_emails: list[str] | NotGiven = NOT_GIVEN,
    app_enable_public_subscription_page: bool | NotGiven = NOT_GIVEN,
    app_enable_public_archive: bool | NotGiven = NOT_GIVEN,
    app_send_optin_confirmation: bool | NotGiven = NOT_GIVEN,
    app_check_updates: bool | NotGiven = NOT_GIVEN,
    app_lang: str | NotGiven = NOT_GIVEN,
    app_batch_size: int | NotGiven = NOT_GIVEN,
    app_concurrency: int | NotGiven = NOT_GIVEN,
    app_max_send_errors: int | NotGiven = NOT_GIVEN,
    app_message_rate: int | NotGiven = NOT_GIVEN,
    app_message_sliding_window: bool | NotGiven = NOT_GIVEN,
    app_message_sliding_window_duration: str | NotGiven = NOT_GIVEN,
    app_message_sliding_window_rate: int | NotGiven = NOT_GIVEN,
    privacy_individual_tracking: bool | NotGiven = NOT_GIVEN,
    privacy_unsubscribe_header: bool | NotGiven = NOT_GIVEN,
    privacy_allow_blocklist: bool | NotGiven = NOT_GIVEN,
    privacy_allow_preferences: bool | NotGiven = NOT_GIVEN,
    privacy_allow_export: bool | NotGiven = NOT_GIVEN,
    privacy_allow_wipe: bool | NotGiven = NOT_GIVEN,
    privacy_exportable: list[str] | NotGiven = NOT_GIVEN,
    privacy_domain_blocklist: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    upload_provider: str | NotGiven = NOT_GIVEN,
    upload_filesystem_upload_path: str | NotGiven = NOT_GIVEN,
    upload_filesystem_upload_uri: str | NotGiven = NOT_GIVEN,
    upload_s3_url: str | NotGiven = NOT_GIVEN,
    upload_s3_public_url: str | NotGiven = NOT_GIVEN,
    upload_s3_aws_access_key_id: str | NotGiven = NOT_GIVEN,
    upload_s3_aws_default_region: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket_domain: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket_path: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket_type: str | NotGiven = NOT_GIVEN,
    upload_s3_expiry: str | NotGiven = NOT_GIVEN,
    smtp: list[SMTPSettings] | NotGiven = NOT_GIVEN,
    messengers: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    bounce_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_webhooks_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_count: int | NotGiven = NOT_GIVEN,
    bounce_action: str | NotGiven = NOT_GIVEN,
    bounce_ses_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_azure_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_azure_shared_secret: str | NotGiven = NOT_GIVEN,
    bounce_azure_shared_secret_header: str | NotGiven = NOT_GIVEN,
    bounce_sendgrid_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_sendgrid_key: str | NotGiven = NOT_GIVEN,
    bounce_forwardemail_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_forwardemail_key: str | NotGiven = NOT_GIVEN,
    bounce_postmark_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_postmark_username: str | NotGiven = NOT_GIVEN,
    bounce_postmark_password: str | NotGiven = NOT_GIVEN,
    bounce_mailboxes: list[MailBoxBounces] | NotGiven = NOT_GIVEN,
    appearance_admin_custom_css: str | NotGiven = NOT_GIVEN,
    appearance_admin_custom_js: str | NotGiven = NOT_GIVEN,
    appearance_public_custom_css: str | NotGiven = NOT_GIVEN,
    appearance_public_custom_js: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateSettingsResponse:
    """Updates settings stored in the database. Supply the settings fields you want to
    update; each listed field is optional.

    returns updated settings from the DB.

    Args:
        app_site_name: Optional `string` value serialized in the `app.site_name` wire field.
        app_root_url: Optional `string` value serialized in the `app.root_url` wire field.
        app_logo_url: Optional `string` value serialized in the `app.logo_url` wire field.
        app_favicon_url: Optional `string` value serialized in the `app.favicon_url` wire field.
        app_from_email: Optional `string` value serialized in the `app.from_email` wire field.
        app_notify_emails: Optional array value serialized in the `app.notify_emails` wire field.
        app_enable_public_subscription_page: Optional `boolean` value serialized in the `app.enable_public_subscription_page`
            wire field.
        app_enable_public_archive: Optional `boolean` value serialized in the `app.enable_public_archive` wire
            field.
        app_send_optin_confirmation: Optional `boolean` value serialized in the `app.send_optin_confirmation` wire
            field.
        app_check_updates: Optional `boolean` value serialized in the `app.check_updates` wire field.
        app_lang: Optional `string` value serialized in the `app.lang` wire field.
        app_batch_size: Optional `integer` value serialized in the `app.batch_size` wire field.
        app_concurrency: Optional `integer` value serialized in the `app.concurrency` wire field.
        app_max_send_errors: Optional `integer` value serialized in the `app.max_send_errors` wire field.
        app_message_rate: Optional `integer` value serialized in the `app.message_rate` wire field.
        app_message_sliding_window: Optional `boolean` value serialized in the `app.message_sliding_window` wire
            field.
        app_message_sliding_window_duration: Optional `string` value serialized in the `app.message_sliding_window_duration`
            wire field.
        app_message_sliding_window_rate: Optional `integer` value serialized in the `app.message_sliding_window_rate`
            wire field.
        privacy_individual_tracking: Optional `boolean` value serialized in the `privacy.individual_tracking` wire
            field.
        privacy_unsubscribe_header: Optional `boolean` value serialized in the `privacy.unsubscribe_header` wire
            field.
        privacy_allow_blocklist: Optional `boolean` value serialized in the `privacy.allow_blocklist` wire field.
        privacy_allow_preferences: Optional `boolean` value serialized in the `privacy.allow_preferences` wire
            field.
        privacy_allow_export: Optional `boolean` value serialized in the `privacy.allow_export` wire field.
        privacy_allow_wipe: Optional `boolean` value serialized in the `privacy.allow_wipe` wire field.
        privacy_exportable: Optional array value serialized in the `privacy.exportable` wire field.
        privacy_domain_blocklist: Optional array value serialized in the `privacy.domain_blocklist` wire field.
        upload_provider: Optional `string` value serialized in the `upload.provider` wire field.
        upload_filesystem_upload_path: Optional `string` value serialized in the `upload.filesystem.upload_path` wire
            field.
        upload_filesystem_upload_uri: Optional `string` value serialized in the `upload.filesystem.upload_uri` wire
            field.
        upload_s3_url: Optional `string` value serialized in the `upload.s3.url` wire field.
        upload_s3_public_url: Optional `string` value serialized in the `upload.s3.public_url` wire field.
        upload_s3_aws_access_key_id: Optional `string` value serialized in the `upload.s3.aws_access_key_id` wire
            field.
        upload_s3_aws_default_region: Optional `string` value serialized in the `upload.s3.aws_default_region` wire
            field.
        upload_s3_bucket: Optional `string` value serialized in the `upload.s3.bucket` wire field.
        upload_s3_bucket_domain: Optional `string` value serialized in the `upload.s3.bucket_domain` wire field.
        upload_s3_bucket_path: Optional `string` value serialized in the `upload.s3.bucket_path` wire field.
        upload_s3_bucket_type: Optional `string` value serialized in the `upload.s3.bucket_type` wire field.
        upload_s3_expiry: Optional `string` value serialized in the `upload.s3.expiry` wire field.
        smtp: Optional array value serialized in the `smtp` wire field.
        messengers: Optional array value serialized in the `messengers` wire field.
        bounce_enabled: Optional `boolean` value serialized in the `bounce.enabled` wire field.
        bounce_webhooks_enabled: Optional `boolean` value serialized in the `bounce.webhooks_enabled` wire field.
        bounce_count: Optional `integer` value serialized in the `bounce.count` wire field.
        bounce_action: Optional `string` value serialized in the `bounce.action` wire field.
        bounce_ses_enabled: Optional `boolean` value serialized in the `bounce.ses_enabled` wire field.
        bounce_azure_enabled: Optional `boolean` value serialized in the `bounce.azure.enabled` wire field.
        bounce_azure_shared_secret: Optional `string` value serialized in the `bounce.azure.shared_secret` wire
            field.
        bounce_azure_shared_secret_header: Optional `string` value serialized in the `bounce.azure.shared_secret_header`
            wire field.
        bounce_sendgrid_enabled: Optional `boolean` value serialized in the `bounce.sendgrid_enabled` wire field.
        bounce_sendgrid_key: Optional `string` value serialized in the `bounce.sendgrid_key` wire field.
        bounce_forwardemail_enabled: Optional `boolean` value serialized in the `bounce.forwardemail_enabled` wire
            field.
        bounce_forwardemail_key: Optional `string` value serialized in the `bounce.forwardemail_key` wire field.
        bounce_postmark_enabled: Optional `boolean` value serialized in the `bounce.postmark_enabled` wire field.
        bounce_postmark_username: Optional `string` value serialized in the `bounce.postmark_username` wire field.
        bounce_postmark_password: Optional `string` value serialized in the `bounce.postmark_password` wire field.
        bounce_mailboxes: Optional array value serialized in the `bounce.mailboxes` wire field.
        appearance_admin_custom_css: Optional `string` value serialized in the `appearance.admin.custom_css` wire
            field.
        appearance_admin_custom_js: Optional `string` value serialized in the `appearance.admin.custom_js` wire
            field.
        appearance_public_custom_css: Optional `string` value serialized in the `appearance.public.custom_css` wire
            field.
        appearance_public_custom_js: Optional `string` value serialized in the `appearance.public.custom_js` wire
            field.
    """

    _resp = await sdk_request(
        "PUT",
        "/settings",
        json=omit_unset(
            {
                "app.site_name": (
                    NOT_GIVEN if app_site_name is NOT_GIVEN else to_wire(app_site_name, "str")
                ),
                "app.root_url": (
                    NOT_GIVEN if app_root_url is NOT_GIVEN else to_wire(app_root_url, "str")
                ),
                "app.logo_url": (
                    NOT_GIVEN if app_logo_url is NOT_GIVEN else to_wire(app_logo_url, "str")
                ),
                "app.favicon_url": (
                    NOT_GIVEN if app_favicon_url is NOT_GIVEN else to_wire(app_favicon_url, "str")
                ),
                "app.from_email": (
                    NOT_GIVEN if app_from_email is NOT_GIVEN else to_wire(app_from_email, "str")
                ),
                "app.notify_emails": (
                    NOT_GIVEN
                    if app_notify_emails is NOT_GIVEN
                    else to_wire(app_notify_emails, "list[str]")
                ),
                "app.enable_public_subscription_page": (
                    NOT_GIVEN
                    if app_enable_public_subscription_page is NOT_GIVEN
                    else to_wire(app_enable_public_subscription_page, "bool")
                ),
                "app.enable_public_archive": (
                    NOT_GIVEN
                    if app_enable_public_archive is NOT_GIVEN
                    else to_wire(app_enable_public_archive, "bool")
                ),
                "app.send_optin_confirmation": (
                    NOT_GIVEN
                    if app_send_optin_confirmation is NOT_GIVEN
                    else to_wire(app_send_optin_confirmation, "bool")
                ),
                "app.check_updates": (
                    NOT_GIVEN
                    if app_check_updates is NOT_GIVEN
                    else to_wire(app_check_updates, "bool")
                ),
                "app.lang": (NOT_GIVEN if app_lang is NOT_GIVEN else to_wire(app_lang, "str")),
                "app.batch_size": (
                    NOT_GIVEN if app_batch_size is NOT_GIVEN else to_wire(app_batch_size, "int")
                ),
                "app.concurrency": (
                    NOT_GIVEN if app_concurrency is NOT_GIVEN else to_wire(app_concurrency, "int")
                ),
                "app.max_send_errors": (
                    NOT_GIVEN
                    if app_max_send_errors is NOT_GIVEN
                    else to_wire(app_max_send_errors, "int")
                ),
                "app.message_rate": (
                    NOT_GIVEN if app_message_rate is NOT_GIVEN else to_wire(app_message_rate, "int")
                ),
                "app.message_sliding_window": (
                    NOT_GIVEN
                    if app_message_sliding_window is NOT_GIVEN
                    else to_wire(app_message_sliding_window, "bool")
                ),
                "app.message_sliding_window_duration": (
                    NOT_GIVEN
                    if app_message_sliding_window_duration is NOT_GIVEN
                    else to_wire(app_message_sliding_window_duration, "str")
                ),
                "app.message_sliding_window_rate": (
                    NOT_GIVEN
                    if app_message_sliding_window_rate is NOT_GIVEN
                    else to_wire(app_message_sliding_window_rate, "int")
                ),
                "privacy.individual_tracking": (
                    NOT_GIVEN
                    if privacy_individual_tracking is NOT_GIVEN
                    else to_wire(privacy_individual_tracking, "bool")
                ),
                "privacy.unsubscribe_header": (
                    NOT_GIVEN
                    if privacy_unsubscribe_header is NOT_GIVEN
                    else to_wire(privacy_unsubscribe_header, "bool")
                ),
                "privacy.allow_blocklist": (
                    NOT_GIVEN
                    if privacy_allow_blocklist is NOT_GIVEN
                    else to_wire(privacy_allow_blocklist, "bool")
                ),
                "privacy.allow_preferences": (
                    NOT_GIVEN
                    if privacy_allow_preferences is NOT_GIVEN
                    else to_wire(privacy_allow_preferences, "bool")
                ),
                "privacy.allow_export": (
                    NOT_GIVEN
                    if privacy_allow_export is NOT_GIVEN
                    else to_wire(privacy_allow_export, "bool")
                ),
                "privacy.allow_wipe": (
                    NOT_GIVEN
                    if privacy_allow_wipe is NOT_GIVEN
                    else to_wire(privacy_allow_wipe, "bool")
                ),
                "privacy.exportable": (
                    NOT_GIVEN
                    if privacy_exportable is NOT_GIVEN
                    else to_wire(privacy_exportable, "list[str]")
                ),
                "privacy.domain_blocklist": (
                    NOT_GIVEN
                    if privacy_domain_blocklist is NOT_GIVEN
                    else to_wire(privacy_domain_blocklist, "list[dict[str, Any]]")
                ),
                "upload.provider": (
                    NOT_GIVEN if upload_provider is NOT_GIVEN else to_wire(upload_provider, "str")
                ),
                "upload.filesystem.upload_path": (
                    NOT_GIVEN
                    if upload_filesystem_upload_path is NOT_GIVEN
                    else to_wire(upload_filesystem_upload_path, "str")
                ),
                "upload.filesystem.upload_uri": (
                    NOT_GIVEN
                    if upload_filesystem_upload_uri is NOT_GIVEN
                    else to_wire(upload_filesystem_upload_uri, "str")
                ),
                "upload.s3.url": (
                    NOT_GIVEN if upload_s3_url is NOT_GIVEN else to_wire(upload_s3_url, "str")
                ),
                "upload.s3.public_url": (
                    NOT_GIVEN
                    if upload_s3_public_url is NOT_GIVEN
                    else to_wire(upload_s3_public_url, "str")
                ),
                "upload.s3.aws_access_key_id": (
                    NOT_GIVEN
                    if upload_s3_aws_access_key_id is NOT_GIVEN
                    else to_wire(upload_s3_aws_access_key_id, "str")
                ),
                "upload.s3.aws_default_region": (
                    NOT_GIVEN
                    if upload_s3_aws_default_region is NOT_GIVEN
                    else to_wire(upload_s3_aws_default_region, "str")
                ),
                "upload.s3.bucket": (
                    NOT_GIVEN if upload_s3_bucket is NOT_GIVEN else to_wire(upload_s3_bucket, "str")
                ),
                "upload.s3.bucket_domain": (
                    NOT_GIVEN
                    if upload_s3_bucket_domain is NOT_GIVEN
                    else to_wire(upload_s3_bucket_domain, "str")
                ),
                "upload.s3.bucket_path": (
                    NOT_GIVEN
                    if upload_s3_bucket_path is NOT_GIVEN
                    else to_wire(upload_s3_bucket_path, "str")
                ),
                "upload.s3.bucket_type": (
                    NOT_GIVEN
                    if upload_s3_bucket_type is NOT_GIVEN
                    else to_wire(upload_s3_bucket_type, "str")
                ),
                "upload.s3.expiry": (
                    NOT_GIVEN if upload_s3_expiry is NOT_GIVEN else to_wire(upload_s3_expiry, "str")
                ),
                "smtp": (NOT_GIVEN if smtp is NOT_GIVEN else to_wire(smtp, "SMTPSettings")),
                "messengers": (
                    NOT_GIVEN
                    if messengers is NOT_GIVEN
                    else to_wire(messengers, "list[dict[str, Any]]")
                ),
                "bounce.enabled": (
                    NOT_GIVEN if bounce_enabled is NOT_GIVEN else to_wire(bounce_enabled, "bool")
                ),
                "bounce.webhooks_enabled": (
                    NOT_GIVEN
                    if bounce_webhooks_enabled is NOT_GIVEN
                    else to_wire(bounce_webhooks_enabled, "bool")
                ),
                "bounce.count": (
                    NOT_GIVEN if bounce_count is NOT_GIVEN else to_wire(bounce_count, "int")
                ),
                "bounce.action": (
                    NOT_GIVEN if bounce_action is NOT_GIVEN else to_wire(bounce_action, "str")
                ),
                "bounce.ses_enabled": (
                    NOT_GIVEN
                    if bounce_ses_enabled is NOT_GIVEN
                    else to_wire(bounce_ses_enabled, "bool")
                ),
                "bounce.azure.enabled": (
                    NOT_GIVEN
                    if bounce_azure_enabled is NOT_GIVEN
                    else to_wire(bounce_azure_enabled, "bool")
                ),
                "bounce.azure.shared_secret": (
                    NOT_GIVEN
                    if bounce_azure_shared_secret is NOT_GIVEN
                    else to_wire(bounce_azure_shared_secret, "str")
                ),
                "bounce.azure.shared_secret_header": (
                    NOT_GIVEN
                    if bounce_azure_shared_secret_header is NOT_GIVEN
                    else to_wire(bounce_azure_shared_secret_header, "str")
                ),
                "bounce.sendgrid_enabled": (
                    NOT_GIVEN
                    if bounce_sendgrid_enabled is NOT_GIVEN
                    else to_wire(bounce_sendgrid_enabled, "bool")
                ),
                "bounce.sendgrid_key": (
                    NOT_GIVEN
                    if bounce_sendgrid_key is NOT_GIVEN
                    else to_wire(bounce_sendgrid_key, "str")
                ),
                "bounce.forwardemail_enabled": (
                    NOT_GIVEN
                    if bounce_forwardemail_enabled is NOT_GIVEN
                    else to_wire(bounce_forwardemail_enabled, "bool")
                ),
                "bounce.forwardemail_key": (
                    NOT_GIVEN
                    if bounce_forwardemail_key is NOT_GIVEN
                    else to_wire(bounce_forwardemail_key, "str")
                ),
                "bounce.postmark_enabled": (
                    NOT_GIVEN
                    if bounce_postmark_enabled is NOT_GIVEN
                    else to_wire(bounce_postmark_enabled, "bool")
                ),
                "bounce.postmark_username": (
                    NOT_GIVEN
                    if bounce_postmark_username is NOT_GIVEN
                    else to_wire(bounce_postmark_username, "str")
                ),
                "bounce.postmark_password": (
                    NOT_GIVEN
                    if bounce_postmark_password is NOT_GIVEN
                    else to_wire(bounce_postmark_password, "str")
                ),
                "bounce.mailboxes": (
                    NOT_GIVEN
                    if bounce_mailboxes is NOT_GIVEN
                    else to_wire(bounce_mailboxes, "MailBoxBounces")
                ),
                "appearance.admin.custom_css": (
                    NOT_GIVEN
                    if appearance_admin_custom_css is NOT_GIVEN
                    else to_wire(appearance_admin_custom_css, "str")
                ),
                "appearance.admin.custom_js": (
                    NOT_GIVEN
                    if appearance_admin_custom_js is NOT_GIVEN
                    else to_wire(appearance_admin_custom_js, "str")
                ),
                "appearance.public.custom_css": (
                    NOT_GIVEN
                    if appearance_public_custom_css is NOT_GIVEN
                    else to_wire(appearance_public_custom_css, "str")
                ),
                "appearance.public.custom_js": (
                    NOT_GIVEN
                    if appearance_public_custom_js is NOT_GIVEN
                    else to_wire(appearance_public_custom_js, "str")
                ),
            }
        ),
        operation_id="update_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateSettingsResponse"), UpdateSettingsResponse
    )


def update_settings_sync(
    _client_config: ClientConfig,
    app_site_name: str | NotGiven = NOT_GIVEN,
    app_root_url: str | NotGiven = NOT_GIVEN,
    app_logo_url: str | NotGiven = NOT_GIVEN,
    app_favicon_url: str | NotGiven = NOT_GIVEN,
    app_from_email: str | NotGiven = NOT_GIVEN,
    app_notify_emails: list[str] | NotGiven = NOT_GIVEN,
    app_enable_public_subscription_page: bool | NotGiven = NOT_GIVEN,
    app_enable_public_archive: bool | NotGiven = NOT_GIVEN,
    app_send_optin_confirmation: bool | NotGiven = NOT_GIVEN,
    app_check_updates: bool | NotGiven = NOT_GIVEN,
    app_lang: str | NotGiven = NOT_GIVEN,
    app_batch_size: int | NotGiven = NOT_GIVEN,
    app_concurrency: int | NotGiven = NOT_GIVEN,
    app_max_send_errors: int | NotGiven = NOT_GIVEN,
    app_message_rate: int | NotGiven = NOT_GIVEN,
    app_message_sliding_window: bool | NotGiven = NOT_GIVEN,
    app_message_sliding_window_duration: str | NotGiven = NOT_GIVEN,
    app_message_sliding_window_rate: int | NotGiven = NOT_GIVEN,
    privacy_individual_tracking: bool | NotGiven = NOT_GIVEN,
    privacy_unsubscribe_header: bool | NotGiven = NOT_GIVEN,
    privacy_allow_blocklist: bool | NotGiven = NOT_GIVEN,
    privacy_allow_preferences: bool | NotGiven = NOT_GIVEN,
    privacy_allow_export: bool | NotGiven = NOT_GIVEN,
    privacy_allow_wipe: bool | NotGiven = NOT_GIVEN,
    privacy_exportable: list[str] | NotGiven = NOT_GIVEN,
    privacy_domain_blocklist: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    upload_provider: str | NotGiven = NOT_GIVEN,
    upload_filesystem_upload_path: str | NotGiven = NOT_GIVEN,
    upload_filesystem_upload_uri: str | NotGiven = NOT_GIVEN,
    upload_s3_url: str | NotGiven = NOT_GIVEN,
    upload_s3_public_url: str | NotGiven = NOT_GIVEN,
    upload_s3_aws_access_key_id: str | NotGiven = NOT_GIVEN,
    upload_s3_aws_default_region: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket_domain: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket_path: str | NotGiven = NOT_GIVEN,
    upload_s3_bucket_type: str | NotGiven = NOT_GIVEN,
    upload_s3_expiry: str | NotGiven = NOT_GIVEN,
    smtp: list[SMTPSettings] | NotGiven = NOT_GIVEN,
    messengers: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    bounce_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_webhooks_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_count: int | NotGiven = NOT_GIVEN,
    bounce_action: str | NotGiven = NOT_GIVEN,
    bounce_ses_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_azure_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_azure_shared_secret: str | NotGiven = NOT_GIVEN,
    bounce_azure_shared_secret_header: str | NotGiven = NOT_GIVEN,
    bounce_sendgrid_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_sendgrid_key: str | NotGiven = NOT_GIVEN,
    bounce_forwardemail_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_forwardemail_key: str | NotGiven = NOT_GIVEN,
    bounce_postmark_enabled: bool | NotGiven = NOT_GIVEN,
    bounce_postmark_username: str | NotGiven = NOT_GIVEN,
    bounce_postmark_password: str | NotGiven = NOT_GIVEN,
    bounce_mailboxes: list[MailBoxBounces] | NotGiven = NOT_GIVEN,
    appearance_admin_custom_css: str | NotGiven = NOT_GIVEN,
    appearance_admin_custom_js: str | NotGiven = NOT_GIVEN,
    appearance_public_custom_css: str | NotGiven = NOT_GIVEN,
    appearance_public_custom_js: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateSettingsResponse:
    """Updates settings stored in the database. Supply the settings fields you want to
    update; each listed field is optional.

    returns updated settings from the DB.

    Args:
        app_site_name: Optional `string` value serialized in the `app.site_name` wire field.
        app_root_url: Optional `string` value serialized in the `app.root_url` wire field.
        app_logo_url: Optional `string` value serialized in the `app.logo_url` wire field.
        app_favicon_url: Optional `string` value serialized in the `app.favicon_url` wire field.
        app_from_email: Optional `string` value serialized in the `app.from_email` wire field.
        app_notify_emails: Optional array value serialized in the `app.notify_emails` wire field.
        app_enable_public_subscription_page: Optional `boolean` value serialized in the `app.enable_public_subscription_page`
            wire field.
        app_enable_public_archive: Optional `boolean` value serialized in the `app.enable_public_archive` wire
            field.
        app_send_optin_confirmation: Optional `boolean` value serialized in the `app.send_optin_confirmation` wire
            field.
        app_check_updates: Optional `boolean` value serialized in the `app.check_updates` wire field.
        app_lang: Optional `string` value serialized in the `app.lang` wire field.
        app_batch_size: Optional `integer` value serialized in the `app.batch_size` wire field.
        app_concurrency: Optional `integer` value serialized in the `app.concurrency` wire field.
        app_max_send_errors: Optional `integer` value serialized in the `app.max_send_errors` wire field.
        app_message_rate: Optional `integer` value serialized in the `app.message_rate` wire field.
        app_message_sliding_window: Optional `boolean` value serialized in the `app.message_sliding_window` wire
            field.
        app_message_sliding_window_duration: Optional `string` value serialized in the `app.message_sliding_window_duration`
            wire field.
        app_message_sliding_window_rate: Optional `integer` value serialized in the `app.message_sliding_window_rate`
            wire field.
        privacy_individual_tracking: Optional `boolean` value serialized in the `privacy.individual_tracking` wire
            field.
        privacy_unsubscribe_header: Optional `boolean` value serialized in the `privacy.unsubscribe_header` wire
            field.
        privacy_allow_blocklist: Optional `boolean` value serialized in the `privacy.allow_blocklist` wire field.
        privacy_allow_preferences: Optional `boolean` value serialized in the `privacy.allow_preferences` wire
            field.
        privacy_allow_export: Optional `boolean` value serialized in the `privacy.allow_export` wire field.
        privacy_allow_wipe: Optional `boolean` value serialized in the `privacy.allow_wipe` wire field.
        privacy_exportable: Optional array value serialized in the `privacy.exportable` wire field.
        privacy_domain_blocklist: Optional array value serialized in the `privacy.domain_blocklist` wire field.
        upload_provider: Optional `string` value serialized in the `upload.provider` wire field.
        upload_filesystem_upload_path: Optional `string` value serialized in the `upload.filesystem.upload_path` wire
            field.
        upload_filesystem_upload_uri: Optional `string` value serialized in the `upload.filesystem.upload_uri` wire
            field.
        upload_s3_url: Optional `string` value serialized in the `upload.s3.url` wire field.
        upload_s3_public_url: Optional `string` value serialized in the `upload.s3.public_url` wire field.
        upload_s3_aws_access_key_id: Optional `string` value serialized in the `upload.s3.aws_access_key_id` wire
            field.
        upload_s3_aws_default_region: Optional `string` value serialized in the `upload.s3.aws_default_region` wire
            field.
        upload_s3_bucket: Optional `string` value serialized in the `upload.s3.bucket` wire field.
        upload_s3_bucket_domain: Optional `string` value serialized in the `upload.s3.bucket_domain` wire field.
        upload_s3_bucket_path: Optional `string` value serialized in the `upload.s3.bucket_path` wire field.
        upload_s3_bucket_type: Optional `string` value serialized in the `upload.s3.bucket_type` wire field.
        upload_s3_expiry: Optional `string` value serialized in the `upload.s3.expiry` wire field.
        smtp: Optional array value serialized in the `smtp` wire field.
        messengers: Optional array value serialized in the `messengers` wire field.
        bounce_enabled: Optional `boolean` value serialized in the `bounce.enabled` wire field.
        bounce_webhooks_enabled: Optional `boolean` value serialized in the `bounce.webhooks_enabled` wire field.
        bounce_count: Optional `integer` value serialized in the `bounce.count` wire field.
        bounce_action: Optional `string` value serialized in the `bounce.action` wire field.
        bounce_ses_enabled: Optional `boolean` value serialized in the `bounce.ses_enabled` wire field.
        bounce_azure_enabled: Optional `boolean` value serialized in the `bounce.azure.enabled` wire field.
        bounce_azure_shared_secret: Optional `string` value serialized in the `bounce.azure.shared_secret` wire
            field.
        bounce_azure_shared_secret_header: Optional `string` value serialized in the `bounce.azure.shared_secret_header`
            wire field.
        bounce_sendgrid_enabled: Optional `boolean` value serialized in the `bounce.sendgrid_enabled` wire field.
        bounce_sendgrid_key: Optional `string` value serialized in the `bounce.sendgrid_key` wire field.
        bounce_forwardemail_enabled: Optional `boolean` value serialized in the `bounce.forwardemail_enabled` wire
            field.
        bounce_forwardemail_key: Optional `string` value serialized in the `bounce.forwardemail_key` wire field.
        bounce_postmark_enabled: Optional `boolean` value serialized in the `bounce.postmark_enabled` wire field.
        bounce_postmark_username: Optional `string` value serialized in the `bounce.postmark_username` wire field.
        bounce_postmark_password: Optional `string` value serialized in the `bounce.postmark_password` wire field.
        bounce_mailboxes: Optional array value serialized in the `bounce.mailboxes` wire field.
        appearance_admin_custom_css: Optional `string` value serialized in the `appearance.admin.custom_css` wire
            field.
        appearance_admin_custom_js: Optional `string` value serialized in the `appearance.admin.custom_js` wire
            field.
        appearance_public_custom_css: Optional `string` value serialized in the `appearance.public.custom_css` wire
            field.
        appearance_public_custom_js: Optional `string` value serialized in the `appearance.public.custom_js` wire
            field.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/settings",
        json=omit_unset(
            {
                "app.site_name": (
                    NOT_GIVEN if app_site_name is NOT_GIVEN else to_wire(app_site_name, "str")
                ),
                "app.root_url": (
                    NOT_GIVEN if app_root_url is NOT_GIVEN else to_wire(app_root_url, "str")
                ),
                "app.logo_url": (
                    NOT_GIVEN if app_logo_url is NOT_GIVEN else to_wire(app_logo_url, "str")
                ),
                "app.favicon_url": (
                    NOT_GIVEN if app_favicon_url is NOT_GIVEN else to_wire(app_favicon_url, "str")
                ),
                "app.from_email": (
                    NOT_GIVEN if app_from_email is NOT_GIVEN else to_wire(app_from_email, "str")
                ),
                "app.notify_emails": (
                    NOT_GIVEN
                    if app_notify_emails is NOT_GIVEN
                    else to_wire(app_notify_emails, "list[str]")
                ),
                "app.enable_public_subscription_page": (
                    NOT_GIVEN
                    if app_enable_public_subscription_page is NOT_GIVEN
                    else to_wire(app_enable_public_subscription_page, "bool")
                ),
                "app.enable_public_archive": (
                    NOT_GIVEN
                    if app_enable_public_archive is NOT_GIVEN
                    else to_wire(app_enable_public_archive, "bool")
                ),
                "app.send_optin_confirmation": (
                    NOT_GIVEN
                    if app_send_optin_confirmation is NOT_GIVEN
                    else to_wire(app_send_optin_confirmation, "bool")
                ),
                "app.check_updates": (
                    NOT_GIVEN
                    if app_check_updates is NOT_GIVEN
                    else to_wire(app_check_updates, "bool")
                ),
                "app.lang": (NOT_GIVEN if app_lang is NOT_GIVEN else to_wire(app_lang, "str")),
                "app.batch_size": (
                    NOT_GIVEN if app_batch_size is NOT_GIVEN else to_wire(app_batch_size, "int")
                ),
                "app.concurrency": (
                    NOT_GIVEN if app_concurrency is NOT_GIVEN else to_wire(app_concurrency, "int")
                ),
                "app.max_send_errors": (
                    NOT_GIVEN
                    if app_max_send_errors is NOT_GIVEN
                    else to_wire(app_max_send_errors, "int")
                ),
                "app.message_rate": (
                    NOT_GIVEN if app_message_rate is NOT_GIVEN else to_wire(app_message_rate, "int")
                ),
                "app.message_sliding_window": (
                    NOT_GIVEN
                    if app_message_sliding_window is NOT_GIVEN
                    else to_wire(app_message_sliding_window, "bool")
                ),
                "app.message_sliding_window_duration": (
                    NOT_GIVEN
                    if app_message_sliding_window_duration is NOT_GIVEN
                    else to_wire(app_message_sliding_window_duration, "str")
                ),
                "app.message_sliding_window_rate": (
                    NOT_GIVEN
                    if app_message_sliding_window_rate is NOT_GIVEN
                    else to_wire(app_message_sliding_window_rate, "int")
                ),
                "privacy.individual_tracking": (
                    NOT_GIVEN
                    if privacy_individual_tracking is NOT_GIVEN
                    else to_wire(privacy_individual_tracking, "bool")
                ),
                "privacy.unsubscribe_header": (
                    NOT_GIVEN
                    if privacy_unsubscribe_header is NOT_GIVEN
                    else to_wire(privacy_unsubscribe_header, "bool")
                ),
                "privacy.allow_blocklist": (
                    NOT_GIVEN
                    if privacy_allow_blocklist is NOT_GIVEN
                    else to_wire(privacy_allow_blocklist, "bool")
                ),
                "privacy.allow_preferences": (
                    NOT_GIVEN
                    if privacy_allow_preferences is NOT_GIVEN
                    else to_wire(privacy_allow_preferences, "bool")
                ),
                "privacy.allow_export": (
                    NOT_GIVEN
                    if privacy_allow_export is NOT_GIVEN
                    else to_wire(privacy_allow_export, "bool")
                ),
                "privacy.allow_wipe": (
                    NOT_GIVEN
                    if privacy_allow_wipe is NOT_GIVEN
                    else to_wire(privacy_allow_wipe, "bool")
                ),
                "privacy.exportable": (
                    NOT_GIVEN
                    if privacy_exportable is NOT_GIVEN
                    else to_wire(privacy_exportable, "list[str]")
                ),
                "privacy.domain_blocklist": (
                    NOT_GIVEN
                    if privacy_domain_blocklist is NOT_GIVEN
                    else to_wire(privacy_domain_blocklist, "list[dict[str, Any]]")
                ),
                "upload.provider": (
                    NOT_GIVEN if upload_provider is NOT_GIVEN else to_wire(upload_provider, "str")
                ),
                "upload.filesystem.upload_path": (
                    NOT_GIVEN
                    if upload_filesystem_upload_path is NOT_GIVEN
                    else to_wire(upload_filesystem_upload_path, "str")
                ),
                "upload.filesystem.upload_uri": (
                    NOT_GIVEN
                    if upload_filesystem_upload_uri is NOT_GIVEN
                    else to_wire(upload_filesystem_upload_uri, "str")
                ),
                "upload.s3.url": (
                    NOT_GIVEN if upload_s3_url is NOT_GIVEN else to_wire(upload_s3_url, "str")
                ),
                "upload.s3.public_url": (
                    NOT_GIVEN
                    if upload_s3_public_url is NOT_GIVEN
                    else to_wire(upload_s3_public_url, "str")
                ),
                "upload.s3.aws_access_key_id": (
                    NOT_GIVEN
                    if upload_s3_aws_access_key_id is NOT_GIVEN
                    else to_wire(upload_s3_aws_access_key_id, "str")
                ),
                "upload.s3.aws_default_region": (
                    NOT_GIVEN
                    if upload_s3_aws_default_region is NOT_GIVEN
                    else to_wire(upload_s3_aws_default_region, "str")
                ),
                "upload.s3.bucket": (
                    NOT_GIVEN if upload_s3_bucket is NOT_GIVEN else to_wire(upload_s3_bucket, "str")
                ),
                "upload.s3.bucket_domain": (
                    NOT_GIVEN
                    if upload_s3_bucket_domain is NOT_GIVEN
                    else to_wire(upload_s3_bucket_domain, "str")
                ),
                "upload.s3.bucket_path": (
                    NOT_GIVEN
                    if upload_s3_bucket_path is NOT_GIVEN
                    else to_wire(upload_s3_bucket_path, "str")
                ),
                "upload.s3.bucket_type": (
                    NOT_GIVEN
                    if upload_s3_bucket_type is NOT_GIVEN
                    else to_wire(upload_s3_bucket_type, "str")
                ),
                "upload.s3.expiry": (
                    NOT_GIVEN if upload_s3_expiry is NOT_GIVEN else to_wire(upload_s3_expiry, "str")
                ),
                "smtp": (NOT_GIVEN if smtp is NOT_GIVEN else to_wire(smtp, "SMTPSettings")),
                "messengers": (
                    NOT_GIVEN
                    if messengers is NOT_GIVEN
                    else to_wire(messengers, "list[dict[str, Any]]")
                ),
                "bounce.enabled": (
                    NOT_GIVEN if bounce_enabled is NOT_GIVEN else to_wire(bounce_enabled, "bool")
                ),
                "bounce.webhooks_enabled": (
                    NOT_GIVEN
                    if bounce_webhooks_enabled is NOT_GIVEN
                    else to_wire(bounce_webhooks_enabled, "bool")
                ),
                "bounce.count": (
                    NOT_GIVEN if bounce_count is NOT_GIVEN else to_wire(bounce_count, "int")
                ),
                "bounce.action": (
                    NOT_GIVEN if bounce_action is NOT_GIVEN else to_wire(bounce_action, "str")
                ),
                "bounce.ses_enabled": (
                    NOT_GIVEN
                    if bounce_ses_enabled is NOT_GIVEN
                    else to_wire(bounce_ses_enabled, "bool")
                ),
                "bounce.azure.enabled": (
                    NOT_GIVEN
                    if bounce_azure_enabled is NOT_GIVEN
                    else to_wire(bounce_azure_enabled, "bool")
                ),
                "bounce.azure.shared_secret": (
                    NOT_GIVEN
                    if bounce_azure_shared_secret is NOT_GIVEN
                    else to_wire(bounce_azure_shared_secret, "str")
                ),
                "bounce.azure.shared_secret_header": (
                    NOT_GIVEN
                    if bounce_azure_shared_secret_header is NOT_GIVEN
                    else to_wire(bounce_azure_shared_secret_header, "str")
                ),
                "bounce.sendgrid_enabled": (
                    NOT_GIVEN
                    if bounce_sendgrid_enabled is NOT_GIVEN
                    else to_wire(bounce_sendgrid_enabled, "bool")
                ),
                "bounce.sendgrid_key": (
                    NOT_GIVEN
                    if bounce_sendgrid_key is NOT_GIVEN
                    else to_wire(bounce_sendgrid_key, "str")
                ),
                "bounce.forwardemail_enabled": (
                    NOT_GIVEN
                    if bounce_forwardemail_enabled is NOT_GIVEN
                    else to_wire(bounce_forwardemail_enabled, "bool")
                ),
                "bounce.forwardemail_key": (
                    NOT_GIVEN
                    if bounce_forwardemail_key is NOT_GIVEN
                    else to_wire(bounce_forwardemail_key, "str")
                ),
                "bounce.postmark_enabled": (
                    NOT_GIVEN
                    if bounce_postmark_enabled is NOT_GIVEN
                    else to_wire(bounce_postmark_enabled, "bool")
                ),
                "bounce.postmark_username": (
                    NOT_GIVEN
                    if bounce_postmark_username is NOT_GIVEN
                    else to_wire(bounce_postmark_username, "str")
                ),
                "bounce.postmark_password": (
                    NOT_GIVEN
                    if bounce_postmark_password is NOT_GIVEN
                    else to_wire(bounce_postmark_password, "str")
                ),
                "bounce.mailboxes": (
                    NOT_GIVEN
                    if bounce_mailboxes is NOT_GIVEN
                    else to_wire(bounce_mailboxes, "MailBoxBounces")
                ),
                "appearance.admin.custom_css": (
                    NOT_GIVEN
                    if appearance_admin_custom_css is NOT_GIVEN
                    else to_wire(appearance_admin_custom_css, "str")
                ),
                "appearance.admin.custom_js": (
                    NOT_GIVEN
                    if appearance_admin_custom_js is NOT_GIVEN
                    else to_wire(appearance_admin_custom_js, "str")
                ),
                "appearance.public.custom_css": (
                    NOT_GIVEN
                    if appearance_public_custom_css is NOT_GIVEN
                    else to_wire(appearance_public_custom_css, "str")
                ),
                "appearance.public.custom_js": (
                    NOT_GIVEN
                    if appearance_public_custom_js is NOT_GIVEN
                    else to_wire(appearance_public_custom_js, "str")
                ),
            }
        ),
        operation_id="update_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateSettingsResponse"), UpdateSettingsResponse
    )


__all__ = [
    "get_settings",
    "get_settings_sync",
    "update_settings",
    "update_settings_sync",
]
