# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import TestSMTPSettingsResponse
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def test_smtp_settings(
    _client_config: ClientConfig,
    uuid: str | NotGiven = NOT_GIVEN,
    enabled: bool | NotGiven = NOT_GIVEN,
    host: str | NotGiven = NOT_GIVEN,
    hello_hostname: str | NotGiven = NOT_GIVEN,
    port: int | NotGiven = NOT_GIVEN,
    auth_protocol: str | NotGiven = NOT_GIVEN,
    username: str | NotGiven = NOT_GIVEN,
    email_headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    max_conns: int | NotGiven = NOT_GIVEN,
    max_msg_retries: int | NotGiven = NOT_GIVEN,
    idle_timeout: str | NotGiven = NOT_GIVEN,
    wait_timeout: str | NotGiven = NOT_GIVEN,
    tls_type: str | NotGiven = NOT_GIVEN,
    tls_skip_verify: bool | NotGiven = NOT_GIVEN,
    str_email_headers: str | NotGiven = NOT_GIVEN,
    password: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TestSMTPSettingsResponse:
    """Tests SMTP settings using the supplied SMTP configuration values. Provide any
    settings to test in the request body; all listed fields are optional.

    test smtp settings

    Args:
        uuid: Optional `string` value serialized in the `uuid` wire field.
        enabled: Optional `boolean` value serialized in the `enabled` wire field.
        host: Optional `string` value serialized in the `host` wire field.
        hello_hostname: Optional `string` value serialized in the `hello_hostname` wire field.
        port: Optional `integer` value serialized in the `port` wire field.
        auth_protocol: Optional `string` value serialized in the `auth_protocol` wire field.
        username: Optional `string` value serialized in the `username` wire field.
        email_headers: Optional array value serialized in the `email_headers` wire field.
        max_conns: Optional `integer` value serialized in the `max_conns` wire field.
        max_msg_retries: Optional `integer` value serialized in the `max_msg_retries` wire field.
        idle_timeout: Optional `string` value serialized in the `idle_timeout` wire field.
        wait_timeout: Optional `string` value serialized in the `wait_timeout` wire field.
        tls_type: Optional `string` value serialized in the `tls_type` wire field.
        tls_skip_verify: Optional `boolean` value serialized in the `tls_skip_verify` wire field.
        str_email_headers: Optional `string` value serialized in the `strEmailHeaders` wire field.
        password: Optional `string` value serialized in the `password` wire field.
        email: Optional `string` value serialized in the `email` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/settings/smtp/test",
        json=omit_unset(
            {
                "uuid": (NOT_GIVEN if uuid is NOT_GIVEN else to_wire(uuid, "str")),
                "enabled": (NOT_GIVEN if enabled is NOT_GIVEN else to_wire(enabled, "bool")),
                "host": (NOT_GIVEN if host is NOT_GIVEN else to_wire(host, "str")),
                "hello_hostname": (
                    NOT_GIVEN if hello_hostname is NOT_GIVEN else to_wire(hello_hostname, "str")
                ),
                "port": (NOT_GIVEN if port is NOT_GIVEN else to_wire(port, "int")),
                "auth_protocol": (
                    NOT_GIVEN if auth_protocol is NOT_GIVEN else to_wire(auth_protocol, "str")
                ),
                "username": (NOT_GIVEN if username is NOT_GIVEN else to_wire(username, "str")),
                "email_headers": (
                    NOT_GIVEN
                    if email_headers is NOT_GIVEN
                    else to_wire(email_headers, "list[dict[str, Any]]")
                ),
                "max_conns": (NOT_GIVEN if max_conns is NOT_GIVEN else to_wire(max_conns, "int")),
                "max_msg_retries": (
                    NOT_GIVEN if max_msg_retries is NOT_GIVEN else to_wire(max_msg_retries, "int")
                ),
                "idle_timeout": (
                    NOT_GIVEN if idle_timeout is NOT_GIVEN else to_wire(idle_timeout, "str")
                ),
                "wait_timeout": (
                    NOT_GIVEN if wait_timeout is NOT_GIVEN else to_wire(wait_timeout, "str")
                ),
                "tls_type": (NOT_GIVEN if tls_type is NOT_GIVEN else to_wire(tls_type, "str")),
                "tls_skip_verify": (
                    NOT_GIVEN if tls_skip_verify is NOT_GIVEN else to_wire(tls_skip_verify, "bool")
                ),
                "strEmailHeaders": (
                    NOT_GIVEN
                    if str_email_headers is NOT_GIVEN
                    else to_wire(str_email_headers, "str")
                ),
                "password": (NOT_GIVEN if password is NOT_GIVEN else to_wire(password, "str")),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
            }
        ),
        operation_id="test_smtp_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TestSMTPSettingsResponse"), TestSMTPSettingsResponse
    )


def test_smtp_settings_sync(
    _client_config: ClientConfig,
    uuid: str | NotGiven = NOT_GIVEN,
    enabled: bool | NotGiven = NOT_GIVEN,
    host: str | NotGiven = NOT_GIVEN,
    hello_hostname: str | NotGiven = NOT_GIVEN,
    port: int | NotGiven = NOT_GIVEN,
    auth_protocol: str | NotGiven = NOT_GIVEN,
    username: str | NotGiven = NOT_GIVEN,
    email_headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN,
    max_conns: int | NotGiven = NOT_GIVEN,
    max_msg_retries: int | NotGiven = NOT_GIVEN,
    idle_timeout: str | NotGiven = NOT_GIVEN,
    wait_timeout: str | NotGiven = NOT_GIVEN,
    tls_type: str | NotGiven = NOT_GIVEN,
    tls_skip_verify: bool | NotGiven = NOT_GIVEN,
    str_email_headers: str | NotGiven = NOT_GIVEN,
    password: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TestSMTPSettingsResponse:
    """Tests SMTP settings using the supplied SMTP configuration values. Provide any
    settings to test in the request body; all listed fields are optional.

    test smtp settings

    Args:
        uuid: Optional `string` value serialized in the `uuid` wire field.
        enabled: Optional `boolean` value serialized in the `enabled` wire field.
        host: Optional `string` value serialized in the `host` wire field.
        hello_hostname: Optional `string` value serialized in the `hello_hostname` wire field.
        port: Optional `integer` value serialized in the `port` wire field.
        auth_protocol: Optional `string` value serialized in the `auth_protocol` wire field.
        username: Optional `string` value serialized in the `username` wire field.
        email_headers: Optional array value serialized in the `email_headers` wire field.
        max_conns: Optional `integer` value serialized in the `max_conns` wire field.
        max_msg_retries: Optional `integer` value serialized in the `max_msg_retries` wire field.
        idle_timeout: Optional `string` value serialized in the `idle_timeout` wire field.
        wait_timeout: Optional `string` value serialized in the `wait_timeout` wire field.
        tls_type: Optional `string` value serialized in the `tls_type` wire field.
        tls_skip_verify: Optional `boolean` value serialized in the `tls_skip_verify` wire field.
        str_email_headers: Optional `string` value serialized in the `strEmailHeaders` wire field.
        password: Optional `string` value serialized in the `password` wire field.
        email: Optional `string` value serialized in the `email` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/settings/smtp/test",
        json=omit_unset(
            {
                "uuid": (NOT_GIVEN if uuid is NOT_GIVEN else to_wire(uuid, "str")),
                "enabled": (NOT_GIVEN if enabled is NOT_GIVEN else to_wire(enabled, "bool")),
                "host": (NOT_GIVEN if host is NOT_GIVEN else to_wire(host, "str")),
                "hello_hostname": (
                    NOT_GIVEN if hello_hostname is NOT_GIVEN else to_wire(hello_hostname, "str")
                ),
                "port": (NOT_GIVEN if port is NOT_GIVEN else to_wire(port, "int")),
                "auth_protocol": (
                    NOT_GIVEN if auth_protocol is NOT_GIVEN else to_wire(auth_protocol, "str")
                ),
                "username": (NOT_GIVEN if username is NOT_GIVEN else to_wire(username, "str")),
                "email_headers": (
                    NOT_GIVEN
                    if email_headers is NOT_GIVEN
                    else to_wire(email_headers, "list[dict[str, Any]]")
                ),
                "max_conns": (NOT_GIVEN if max_conns is NOT_GIVEN else to_wire(max_conns, "int")),
                "max_msg_retries": (
                    NOT_GIVEN if max_msg_retries is NOT_GIVEN else to_wire(max_msg_retries, "int")
                ),
                "idle_timeout": (
                    NOT_GIVEN if idle_timeout is NOT_GIVEN else to_wire(idle_timeout, "str")
                ),
                "wait_timeout": (
                    NOT_GIVEN if wait_timeout is NOT_GIVEN else to_wire(wait_timeout, "str")
                ),
                "tls_type": (NOT_GIVEN if tls_type is NOT_GIVEN else to_wire(tls_type, "str")),
                "tls_skip_verify": (
                    NOT_GIVEN if tls_skip_verify is NOT_GIVEN else to_wire(tls_skip_verify, "bool")
                ),
                "strEmailHeaders": (
                    NOT_GIVEN
                    if str_email_headers is NOT_GIVEN
                    else to_wire(str_email_headers, "str")
                ),
                "password": (NOT_GIVEN if password is NOT_GIVEN else to_wire(password, "str")),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
            }
        ),
        operation_id="test_smtp_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TestSMTPSettingsResponse"), TestSMTPSettingsResponse
    )


__all__ = [
    "test_smtp_settings",
    "test_smtp_settings_sync",
]
