# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import (
    CampaignContentRequestListsItem,
    CampaignRequestSendAt,
    CreateCampaignContentByIdResponse,
    TestCampaignByIdResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def create_campaign_content_by_id(
    _client_config: ClientConfig,
    id: int,
    id_2: int | NotGiven = NOT_GIVEN,
    created_at: str | NotGiven = NOT_GIVEN,
    updated_at: str | NotGiven = NOT_GIVEN,
    campaign_id: int | NotGiven = NOT_GIVEN,
    views: int | NotGiven = NOT_GIVEN,
    clicks: int | NotGiven = NOT_GIVEN,
    lists: list[CampaignContentRequestListsItem] | NotGiven = NOT_GIVEN,
    started_at: str | NotGiven = NOT_GIVEN,
    to_send: int | NotGiven = NOT_GIVEN,
    sent: int | NotGiven = NOT_GIVEN,
    uuid: str | NotGiven = NOT_GIVEN,
    type: Literal["regular", "optin"] | str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    send_at: str | NotGiven = NOT_GIVEN,
    status: str | NotGiven = NOT_GIVEN,
    content_type: Literal["richtext", "html", "markdown", "plain"] | str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    template_id: int | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    from_: str | NotGiven = NOT_GIVEN,
    to: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateCampaignContentByIdResponse:
    """Submits updated content for a campaign and converts it to the campaign's content
    format. Use the campaign identifier in the path and provide any campaign content
    fields you want to submit.

    handles campaign content (body) format conversions.

    Args:
        id: ID of campaign that you choose to create content
        id_2: Optional `integer` value serialized in the `id` wire field.
        created_at: Optional `string` value serialized in the `created_at` wire field.
        updated_at: Optional `string` value serialized in the `updated_at` wire field.
        campaign_id: Optional `integer` value serialized in the `CampaignID` wire field.
        views: Optional `integer` value serialized in the `views` wire field.
        clicks: Optional `integer` value serialized in the `clicks` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        started_at: Optional `string` value serialized in the `started_at` wire field.
        to_send: Optional `integer` value serialized in the `to_send` wire field.
        sent: Optional `integer` value serialized in the `sent` wire field.
        uuid: Optional `string` value serialized in the `uuid` wire field.
        type: Optional enumerated value serialized in the `type` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        body: Optional `string` value serialized in the `body` wire field.
        send_at: Optional `string` value serialized in the `send_at` wire field.
        status: Optional `string` value serialized in the `status` wire field.
        content_type: Optional enumerated value serialized in the `content_type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        template_id: Optional `integer` value serialized in the `template_id` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        from_: Optional `string` value serialized in the `from` wire field.
        to: Optional `string` value serialized in the `to` wire field.
    """

    _resp = await sdk_request(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/content",
        json=omit_unset(
            {
                "id": (NOT_GIVEN if id_2 is NOT_GIVEN else to_wire(id_2, "int")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "str")
                ),
                "updated_at": (
                    NOT_GIVEN if updated_at is NOT_GIVEN else to_wire(updated_at, "str")
                ),
                "CampaignID": (
                    NOT_GIVEN if campaign_id is NOT_GIVEN else to_wire(campaign_id, "int")
                ),
                "views": (NOT_GIVEN if views is NOT_GIVEN else to_wire(views, "int")),
                "clicks": (NOT_GIVEN if clicks is NOT_GIVEN else to_wire(clicks, "int")),
                "lists": (
                    NOT_GIVEN
                    if lists is NOT_GIVEN
                    else to_wire(lists, "CampaignContentRequestListsItem")
                ),
                "started_at": (
                    NOT_GIVEN if started_at is NOT_GIVEN else to_wire(started_at, "str")
                ),
                "to_send": (NOT_GIVEN if to_send is NOT_GIVEN else to_wire(to_send, "int")),
                "sent": (NOT_GIVEN if sent is NOT_GIVEN else to_wire(sent, "int")),
                "uuid": (NOT_GIVEN if uuid is NOT_GIVEN else to_wire(uuid, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["regular", "optin"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
                "send_at": (NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "str")),
                "status": (NOT_GIVEN if status is NOT_GIVEN else to_wire(status, "str")),
                "content_type": (
                    NOT_GIVEN
                    if content_type is NOT_GIVEN
                    else to_wire(
                        content_type, 'Literal["richtext", "html", "markdown", "plain"] | str'
                    )
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "from": (NOT_GIVEN if from_ is NOT_GIVEN else to_wire(from_, "str")),
                "to": (NOT_GIVEN if to is NOT_GIVEN else to_wire(to, "str")),
            }
        ),
        operation_id="create_campaign_content_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateCampaignContentByIdResponse"),
        CreateCampaignContentByIdResponse,
    )


def create_campaign_content_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    id_2: int | NotGiven = NOT_GIVEN,
    created_at: str | NotGiven = NOT_GIVEN,
    updated_at: str | NotGiven = NOT_GIVEN,
    campaign_id: int | NotGiven = NOT_GIVEN,
    views: int | NotGiven = NOT_GIVEN,
    clicks: int | NotGiven = NOT_GIVEN,
    lists: list[CampaignContentRequestListsItem] | NotGiven = NOT_GIVEN,
    started_at: str | NotGiven = NOT_GIVEN,
    to_send: int | NotGiven = NOT_GIVEN,
    sent: int | NotGiven = NOT_GIVEN,
    uuid: str | NotGiven = NOT_GIVEN,
    type: Literal["regular", "optin"] | str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    send_at: str | NotGiven = NOT_GIVEN,
    status: str | NotGiven = NOT_GIVEN,
    content_type: Literal["richtext", "html", "markdown", "plain"] | str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    template_id: int | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    from_: str | NotGiven = NOT_GIVEN,
    to: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateCampaignContentByIdResponse:
    """Submits updated content for a campaign and converts it to the campaign's content
    format. Use the campaign identifier in the path and provide any campaign content
    fields you want to submit.

    handles campaign content (body) format conversions.

    Args:
        id: ID of campaign that you choose to create content
        id_2: Optional `integer` value serialized in the `id` wire field.
        created_at: Optional `string` value serialized in the `created_at` wire field.
        updated_at: Optional `string` value serialized in the `updated_at` wire field.
        campaign_id: Optional `integer` value serialized in the `CampaignID` wire field.
        views: Optional `integer` value serialized in the `views` wire field.
        clicks: Optional `integer` value serialized in the `clicks` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        started_at: Optional `string` value serialized in the `started_at` wire field.
        to_send: Optional `integer` value serialized in the `to_send` wire field.
        sent: Optional `integer` value serialized in the `sent` wire field.
        uuid: Optional `string` value serialized in the `uuid` wire field.
        type: Optional enumerated value serialized in the `type` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        body: Optional `string` value serialized in the `body` wire field.
        send_at: Optional `string` value serialized in the `send_at` wire field.
        status: Optional `string` value serialized in the `status` wire field.
        content_type: Optional enumerated value serialized in the `content_type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        template_id: Optional `integer` value serialized in the `template_id` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        from_: Optional `string` value serialized in the `from` wire field.
        to: Optional `string` value serialized in the `to` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/content",
        json=omit_unset(
            {
                "id": (NOT_GIVEN if id_2 is NOT_GIVEN else to_wire(id_2, "int")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "str")
                ),
                "updated_at": (
                    NOT_GIVEN if updated_at is NOT_GIVEN else to_wire(updated_at, "str")
                ),
                "CampaignID": (
                    NOT_GIVEN if campaign_id is NOT_GIVEN else to_wire(campaign_id, "int")
                ),
                "views": (NOT_GIVEN if views is NOT_GIVEN else to_wire(views, "int")),
                "clicks": (NOT_GIVEN if clicks is NOT_GIVEN else to_wire(clicks, "int")),
                "lists": (
                    NOT_GIVEN
                    if lists is NOT_GIVEN
                    else to_wire(lists, "CampaignContentRequestListsItem")
                ),
                "started_at": (
                    NOT_GIVEN if started_at is NOT_GIVEN else to_wire(started_at, "str")
                ),
                "to_send": (NOT_GIVEN if to_send is NOT_GIVEN else to_wire(to_send, "int")),
                "sent": (NOT_GIVEN if sent is NOT_GIVEN else to_wire(sent, "int")),
                "uuid": (NOT_GIVEN if uuid is NOT_GIVEN else to_wire(uuid, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["regular", "optin"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
                "send_at": (NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "str")),
                "status": (NOT_GIVEN if status is NOT_GIVEN else to_wire(status, "str")),
                "content_type": (
                    NOT_GIVEN
                    if content_type is NOT_GIVEN
                    else to_wire(
                        content_type, 'Literal["richtext", "html", "markdown", "plain"] | str'
                    )
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "from": (NOT_GIVEN if from_ is NOT_GIVEN else to_wire(from_, "str")),
                "to": (NOT_GIVEN if to is NOT_GIVEN else to_wire(to, "str")),
            }
        ),
        operation_id="create_campaign_content_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateCampaignContentByIdResponse"),
        CreateCampaignContentByIdResponse,
    )


async def test_campaign_by_id(
    _client_config: ClientConfig,
    id: int,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    lists: list[float] | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    send_later: bool | NotGiven = NOT_GIVEN,
    send_at: CampaignRequestSendAt | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TestCampaignByIdResponse:
    """Submits a test campaign message to selected subscribers. Provide the campaign
    identifier and a request body with the test message configuration; the body can use
    JSON or form-encoded data.

    handles sending of campaign message to arbitrary subscribers for testing

    Args:
        id: ID of campaign that you want to test
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        send_later: Optional `boolean` value serialized in the `send_later` wire field.
        send_at: Optional object value serialized in the `send_at` wire field.
    """

    _resp = await sdk_request(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/test",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[float]")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "send_later": (
                    NOT_GIVEN if send_later is NOT_GIVEN else to_wire(send_later, "bool")
                ),
                "send_at": (
                    NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "CampaignRequestSendAt")
                ),
            }
        ),
        operation_id="test_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TestCampaignByIdResponse"), TestCampaignByIdResponse
    )


def test_campaign_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    lists: list[float] | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    send_later: bool | NotGiven = NOT_GIVEN,
    send_at: CampaignRequestSendAt | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TestCampaignByIdResponse:
    """Submits a test campaign message to selected subscribers. Provide the campaign
    identifier and a request body with the test message configuration; the body can use
    JSON or form-encoded data.

    handles sending of campaign message to arbitrary subscribers for testing

    Args:
        id: ID of campaign that you want to test
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        send_later: Optional `boolean` value serialized in the `send_later` wire field.
        send_at: Optional object value serialized in the `send_at` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/test",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[float]")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "send_later": (
                    NOT_GIVEN if send_later is NOT_GIVEN else to_wire(send_later, "bool")
                ),
                "send_at": (
                    NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "CampaignRequestSendAt")
                ),
            }
        ),
        operation_id="test_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TestCampaignByIdResponse"), TestCampaignByIdResponse
    )


async def test_campaign_by_id_form(
    _client_config: ClientConfig,
    id: int,
    template_id: int | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TestCampaignByIdResponse:
    """Submits a test campaign message to selected subscribers. Provide the campaign
    identifier and a request body with the test message configuration; the body can use
    JSON or form-encoded data.

    handles sending of campaign message to arbitrary subscribers for testing

    Args:
        id: ID of campaign that you want to test
        template_id: template id
    """

    _resp = await sdk_request(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/test",
        json=omit_unset(
            {
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="test_campaign_by_id_form",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TestCampaignByIdResponse"), TestCampaignByIdResponse
    )


def test_campaign_by_id_form_sync(
    _client_config: ClientConfig,
    id: int,
    template_id: int | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> TestCampaignByIdResponse:
    """Submits a test campaign message to selected subscribers. Provide the campaign
    identifier and a request body with the test message configuration; the body can use
    JSON or form-encoded data.

    handles sending of campaign message to arbitrary subscribers for testing

    Args:
        id: ID of campaign that you want to test
        template_id: template id
    """

    _resp = sdk_request_sync(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/test",
        json=omit_unset(
            {
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="test_campaign_by_id_form",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "TestCampaignByIdResponse"), TestCampaignByIdResponse
    )


__all__ = [
    "create_campaign_content_by_id",
    "create_campaign_content_by_id_sync",
    "test_campaign_by_id",
    "test_campaign_by_id_form",
    "test_campaign_by_id_form_sync",
    "test_campaign_by_id_sync",
]
