# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from listmonk_unofficial_sdk.types import (
    GetCampaignAnalyticsResponse,
    GetRunningCampaignStatsResponse,
    UpdateCampaignArchiveByIdResponse,
    UpdateCampaignStatusByIdResponse,
)
from listmonk_unofficial_sdk.validation import validate_date
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_running_campaign_stats(
    _client_config: ClientConfig,
    campaign_id: float,
    *,
    request_options: RequestOptions | None = None,
) -> GetRunningCampaignStatsResponse:
    """Lists statistics for the campaign identified by `campaign_id`. Supply the campaign
    ID as a number to retrieve its running campaign statistics. The response contains
    statistics for the requested campaign.

    returns stats of a given set of campaign IDs.

    Args:
        campaign_id: Campaign IDs to get stats for.
    """

    _resp = await sdk_request(
        "GET",
        "/campaigns/running/stats",
        params=serialize_query([("campaign_id", campaign_id, "form", True)]),
        operation_id="get_running_campaign_stats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetRunningCampaignStatsResponse"),
        GetRunningCampaignStatsResponse,
    )


def get_running_campaign_stats_sync(
    _client_config: ClientConfig,
    campaign_id: float,
    *,
    request_options: RequestOptions | None = None,
) -> GetRunningCampaignStatsResponse:
    """Lists statistics for the campaign identified by `campaign_id`. Supply the campaign
    ID as a number to retrieve its running campaign statistics. The response contains
    statistics for the requested campaign.

    returns stats of a given set of campaign IDs.

    Args:
        campaign_id: Campaign IDs to get stats for.
    """

    _resp = sdk_request_sync(
        "GET",
        "/campaigns/running/stats",
        params=serialize_query([("campaign_id", campaign_id, "form", True)]),
        operation_id="get_running_campaign_stats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetRunningCampaignStatsResponse"),
        GetRunningCampaignStatsResponse,
    )


async def get_campaign_analytics(
    _client_config: ClientConfig,
    type: Literal["links", "views", "clicks", "bounces"] | str,
    from_: datetime.date,
    to: str,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> GetCampaignAnalyticsResponse:
    """Retrieves campaign analytics for the requested statistic type and date range. Use
    `type` to select links, views, clicks, or bounces, and provide `from`, `to`, and
    `id` to scope the results. The response contains counts over time for the specified
    campaign ID or IDs.

    retrieves view counts for a campaign.

    Args:
        type: type of stats, either links, view, click or bounce
        from_: start value of date range
        to: end value of date range
        id: campaign id/s to retrive view counts
    """

    validate_date("from", from_)

    _resp = await sdk_request(
        "GET",
        f"/campaigns/analytics/{encode_path_segment(type)}",
        params=serialize_query(
            [("from", from_, "form", True), ("to", to, "form", True), ("id", id, "form", True)]
        ),
        operation_id="get_campaign_analytics",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCampaignAnalyticsResponse"),
        GetCampaignAnalyticsResponse,
    )


def get_campaign_analytics_sync(
    _client_config: ClientConfig,
    type: Literal["links", "views", "clicks", "bounces"] | str,
    from_: datetime.date,
    to: str,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> GetCampaignAnalyticsResponse:
    """Retrieves campaign analytics for the requested statistic type and date range. Use
    `type` to select links, views, clicks, or bounces, and provide `from`, `to`, and
    `id` to scope the results. The response contains counts over time for the specified
    campaign ID or IDs.

    retrieves view counts for a campaign.

    Args:
        type: type of stats, either links, view, click or bounce
        from_: start value of date range
        to: end value of date range
        id: campaign id/s to retrive view counts
    """

    validate_date("from", from_)

    _resp = sdk_request_sync(
        "GET",
        f"/campaigns/analytics/{encode_path_segment(type)}",
        params=serialize_query(
            [("from", from_, "form", True), ("to", to, "form", True), ("id", id, "form", True)]
        ),
        operation_id="get_campaign_analytics",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCampaignAnalyticsResponse"),
        GetCampaignAnalyticsResponse,
    )


async def preview_campaign_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Retrieves the rendered HTML preview of a campaign's body. Supply the campaign's
    integer `id` to select the campaign whose preview you want to view.

    renders the HTML preview of a campaign body

    Args:
        id: The id value of the campaign you want to get the preview of
    """

    _resp = await sdk_request(
        "GET",
        f"/campaigns/{encode_path_segment(id)}/preview",
        operation_id="preview_campaign_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


def preview_campaign_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Retrieves the rendered HTML preview of a campaign's body. Supply the campaign's
    integer `id` to select the campaign whose preview you want to view.

    renders the HTML preview of a campaign body

    Args:
        id: The id value of the campaign you want to get the preview of
    """

    _resp = sdk_request_sync(
        "GET",
        f"/campaigns/{encode_path_segment(id)}/preview",
        operation_id="preview_campaign_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


async def update_preview_campaign_by_id(
    _client_config: ClientConfig,
    id: int,
    template_id: int | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Renders an HTML preview of a campaign using the supplied template and content
    fields. Use `id` to identify the campaign and provide the preview inputs as
    form-encoded fields. The request body fields are optional in the schema.

    renders the HTML preview of a campaign body

    Args:
        id: The id value of the campaign you want to get the preview of
        template_id: template id
        content_type: content type
        body: template body
    """

    _resp = await sdk_request(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/preview",
        json=omit_unset(
            {
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="update_preview_campaign_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


def update_preview_campaign_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    template_id: int | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Renders an HTML preview of a campaign using the supplied template and content
    fields. Use `id` to identify the campaign and provide the preview inputs as
    form-encoded fields. The request body fields are optional in the schema.

    renders the HTML preview of a campaign body

    Args:
        id: The id value of the campaign you want to get the preview of
        template_id: template id
        content_type: content type
        body: template body
    """

    _resp = sdk_request_sync(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/preview",
        json=omit_unset(
            {
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="update_preview_campaign_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


async def preview_campaign_text_by_id(
    _client_config: ClientConfig,
    id: int,
    template_id: int | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Renders a text preview of a campaign using the supplied template and content fields.
    Use `id` to identify the campaign and provide the preview inputs as form-encoded
    fields. The request body fields are optional in the schema.

    renders the HTML preview of a campaign body

    Args:
        id: The id value of the campaign you want to get the preview of
        template_id: template id
        content_type: content type
        body: campaign body
    """

    _resp = await sdk_request(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/text",
        json=omit_unset(
            {
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="preview_campaign_text_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


def preview_campaign_text_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    template_id: int | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Renders a text preview of a campaign using the supplied template and content fields.
    Use `id` to identify the campaign and provide the preview inputs as form-encoded
    fields. The request body fields are optional in the schema.

    renders the HTML preview of a campaign body

    Args:
        id: The id value of the campaign you want to get the preview of
        template_id: template id
        content_type: content type
        body: campaign body
    """

    _resp = sdk_request_sync(
        "POST",
        f"/campaigns/{encode_path_segment(id)}/text",
        json=omit_unset(
            {
                "template_id": (
                    NOT_GIVEN if template_id is NOT_GIVEN else to_wire(template_id, "int")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="preview_campaign_text_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


async def update_campaign_status_by_id(
    _client_config: ClientConfig,
    id: int,
    status: Literal["scheduled", "running", "paused", "cancelled"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateCampaignStatusByIdResponse:
    """Replaces the status of a campaign. Set `status` to `scheduled`, `running`, `paused`,
    or `cancelled` when you want to change the campaign's state.

    handles campaign status modification

    Args:
        id: The id value of the campaign you want to get the preview of
    """

    _resp = await sdk_request(
        "PUT",
        f"/campaigns/{encode_path_segment(id)}/status",
        json=omit_unset(
            {
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["scheduled", "running", "paused", "cancelled"] | str'
                    )
                ),
            }
        ),
        operation_id="update_campaign_status_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateCampaignStatusByIdResponse"),
        UpdateCampaignStatusByIdResponse,
    )


def update_campaign_status_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    status: Literal["scheduled", "running", "paused", "cancelled"] | str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateCampaignStatusByIdResponse:
    """Replaces the status of a campaign. Set `status` to `scheduled`, `running`, `paused`,
    or `cancelled` when you want to change the campaign's state.

    handles campaign status modification

    Args:
        id: The id value of the campaign you want to get the preview of
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/campaigns/{encode_path_segment(id)}/status",
        json=omit_unset(
            {
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["scheduled", "running", "paused", "cancelled"] | str'
                    )
                ),
            }
        ),
        operation_id="update_campaign_status_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateCampaignStatusByIdResponse"),
        UpdateCampaignStatusByIdResponse,
    )


async def update_campaign_archive_by_id(
    _client_config: ClientConfig,
    id: int,
    archive: bool | NotGiven = NOT_GIVEN,
    archive_template_id: int | NotGiven = NOT_GIVEN,
    archive_meta: dict[str, Any] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateCampaignArchiveByIdResponse:
    """Replaces the archive settings for a campaign. Use `archive` to set the archive state
    and `archive_template_id` or `archive_meta` to provide related archive
    configuration.

    handles campaign status modification

    Args:
        id: The id value of the campaign you want to get the preview of
    """

    _resp = await sdk_request(
        "PUT",
        f"/campaigns/{encode_path_segment(id)}/archive",
        json=omit_unset(
            {
                "archive": (NOT_GIVEN if archive is NOT_GIVEN else to_wire(archive, "bool")),
                "archive_template_id": (
                    NOT_GIVEN
                    if archive_template_id is NOT_GIVEN
                    else to_wire(archive_template_id, "int")
                ),
                "archive_meta": (
                    NOT_GIVEN
                    if archive_meta is NOT_GIVEN
                    else to_wire(archive_meta, "dict[str, Any]")
                ),
            }
        ),
        operation_id="update_campaign_archive_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateCampaignArchiveByIdResponse"),
        UpdateCampaignArchiveByIdResponse,
    )


def update_campaign_archive_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    archive: bool | NotGiven = NOT_GIVEN,
    archive_template_id: int | NotGiven = NOT_GIVEN,
    archive_meta: dict[str, Any] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateCampaignArchiveByIdResponse:
    """Replaces the archive settings for a campaign. Use `archive` to set the archive state
    and `archive_template_id` or `archive_meta` to provide related archive
    configuration.

    handles campaign status modification

    Args:
        id: The id value of the campaign you want to get the preview of
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/campaigns/{encode_path_segment(id)}/archive",
        json=omit_unset(
            {
                "archive": (NOT_GIVEN if archive is NOT_GIVEN else to_wire(archive, "bool")),
                "archive_template_id": (
                    NOT_GIVEN
                    if archive_template_id is NOT_GIVEN
                    else to_wire(archive_template_id, "int")
                ),
                "archive_meta": (
                    NOT_GIVEN
                    if archive_meta is NOT_GIVEN
                    else to_wire(archive_meta, "dict[str, Any]")
                ),
            }
        ),
        operation_id="update_campaign_archive_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateCampaignArchiveByIdResponse"),
        UpdateCampaignArchiveByIdResponse,
    )


__all__ = [
    "get_campaign_analytics",
    "get_campaign_analytics_sync",
    "get_running_campaign_stats",
    "get_running_campaign_stats_sync",
    "preview_campaign_by_id",
    "preview_campaign_by_id_sync",
    "preview_campaign_text_by_id",
    "preview_campaign_text_by_id_sync",
    "update_campaign_archive_by_id",
    "update_campaign_archive_by_id_sync",
    "update_campaign_status_by_id",
    "update_campaign_status_by_id_sync",
    "update_preview_campaign_by_id",
    "update_preview_campaign_by_id_sync",
]
