# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from listmonk_unofficial_sdk.types import (
    CampaignRequestSendAt,
    CreateCampaignResponse,
    DeleteCampaignByIdResponse,
    GetCampaignByIdResponse,
    GetCampaignsResponse,
    UpdateCampaignByIdResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_campaigns(
    _client_config: ClientConfig,
    status: list[Literal["scheduled", "running", "paused", "cancelled"] | str]
    | NotGiven = NOT_GIVEN,
    no_body: bool | NotGiven = NOT_GIVEN,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    order: Literal["ASC", "DESC"] | str | NotGiven = NOT_GIVEN,
    order_by: Literal["name", "status", "created_at", "updated_at"] | str | NotGiven = NOT_GIVEN,
    query: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetCampaignsResponse:
    """Lists campaigns, with optional filters for status and tags and optional sorting
    controls. Use `query` to apply custom SQL criteria, or use `page` and `per_page` to
    paginate the results. Set `no_body` to true to request a response without body
    content.

    handles retrieval of campaigns

    Args:
        status: Filter campaigns by status. Multiple status values can be specified by repeating
            the parameter
        no_body: When set to true, returns response without body content
        page: Page number for paginated results.
        per_page: Number of items per page. Use an integer for specific page size or 'all' to
            retrieve all results
        tags: Filter campaigns by tags. Multiple tags can be specified by repeating the
            parameter
        order: Determines the sort order of results. ASC for ascending, DESC for descending
            order
        order_by: Specifies the field by which to sort the campaigns. Available options are
            'name', 'status', 'created_at', and 'updated_at'
        query: SQL query expression to filter campaigns by custom criteria
    """

    _resp = await sdk_request(
        "GET",
        "/campaigns",
        params=serialize_query(
            [
                ("status", status, "form", True),
                ("no_body", no_body, "form", True),
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("tags", tags, "form", True),
                ("order", order, "form", True),
                ("order_by", order_by, "form", True),
                ("query", query, "form", True),
            ]
        ),
        operation_id="get_campaigns",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCampaignsResponse"), GetCampaignsResponse
    )


def get_campaigns_sync(
    _client_config: ClientConfig,
    status: list[Literal["scheduled", "running", "paused", "cancelled"] | str]
    | NotGiven = NOT_GIVEN,
    no_body: bool | NotGiven = NOT_GIVEN,
    page: int | NotGiven = NOT_GIVEN,
    per_page: int | Literal["all"] | str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    order: Literal["ASC", "DESC"] | str | NotGiven = NOT_GIVEN,
    order_by: Literal["name", "status", "created_at", "updated_at"] | str | NotGiven = NOT_GIVEN,
    query: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetCampaignsResponse:
    """Lists campaigns, with optional filters for status and tags and optional sorting
    controls. Use `query` to apply custom SQL criteria, or use `page` and `per_page` to
    paginate the results. Set `no_body` to true to request a response without body
    content.

    handles retrieval of campaigns

    Args:
        status: Filter campaigns by status. Multiple status values can be specified by repeating
            the parameter
        no_body: When set to true, returns response without body content
        page: Page number for paginated results.
        per_page: Number of items per page. Use an integer for specific page size or 'all' to
            retrieve all results
        tags: Filter campaigns by tags. Multiple tags can be specified by repeating the
            parameter
        order: Determines the sort order of results. ASC for ascending, DESC for descending
            order
        order_by: Specifies the field by which to sort the campaigns. Available options are
            'name', 'status', 'created_at', and 'updated_at'
        query: SQL query expression to filter campaigns by custom criteria
    """

    _resp = sdk_request_sync(
        "GET",
        "/campaigns",
        params=serialize_query(
            [
                ("status", status, "form", True),
                ("no_body", no_body, "form", True),
                ("page", page, "form", True),
                ("per_page", per_page, "form", True),
                ("tags", tags, "form", True),
                ("order", order, "form", True),
                ("order_by", order_by, "form", True),
                ("query", query, "form", True),
            ]
        ),
        operation_id="get_campaigns",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCampaignsResponse"), GetCampaignsResponse
    )


async def create_campaign(
    _client_config: ClientConfig,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    lists: list[float] | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    send_later: bool | NotGiven = NOT_GIVEN,
    send_at: CampaignRequestSendAt | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateCampaignResponse:
    """Creates a campaign from the campaign details supplied in the request body. Provide
    fields such as `name`, `subject`, and `lists` to define the campaign; all body
    fields are optional in the schema. A successful response contains the new campaign
    object.

    handles campaign creation

    Args:
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        send_later: Optional `boolean` value serialized in the `send_later` wire field.
        send_at: Optional object value serialized in the `send_at` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/campaigns",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[float]")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "send_later": (
                    NOT_GIVEN if send_later is NOT_GIVEN else to_wire(send_later, "bool")
                ),
                "send_at": (
                    NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "CampaignRequestSendAt")
                ),
            }
        ),
        operation_id="create_campaign",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateCampaignResponse"), CreateCampaignResponse
    )


def create_campaign_sync(
    _client_config: ClientConfig,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    lists: list[float] | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    send_later: bool | NotGiven = NOT_GIVEN,
    send_at: CampaignRequestSendAt | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateCampaignResponse:
    """Creates a campaign from the campaign details supplied in the request body. Provide
    fields such as `name`, `subject`, and `lists` to define the campaign; all body
    fields are optional in the schema. A successful response contains the new campaign
    object.

    handles campaign creation

    Args:
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        send_later: Optional `boolean` value serialized in the `send_later` wire field.
        send_at: Optional object value serialized in the `send_at` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/campaigns",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[float]")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "send_later": (
                    NOT_GIVEN if send_later is NOT_GIVEN else to_wire(send_later, "bool")
                ),
                "send_at": (
                    NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "CampaignRequestSendAt")
                ),
            }
        ),
        operation_id="create_campaign",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateCampaignResponse"), CreateCampaignResponse
    )


async def get_campaign_by_id(
    _client_config: ClientConfig,
    id: int,
    no_body: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetCampaignByIdResponse:
    """Retrieves a campaign by its identifier. Use `id` to select the campaign, and set
    `no_body` to true if you want the response without body content.

    handles retrieval of campaigns.

    Args:
        id: The id value of the campaign you want to get.
        no_body: boolean flag for response with/without body
    """

    _resp = await sdk_request(
        "GET",
        f"/campaigns/{encode_path_segment(id)}",
        params=serialize_query([("no_body", no_body, "form", True)]),
        operation_id="get_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCampaignByIdResponse"), GetCampaignByIdResponse
    )


def get_campaign_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    no_body: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetCampaignByIdResponse:
    """Retrieves a campaign by its identifier. Use `id` to select the campaign, and set
    `no_body` to true if you want the response without body content.

    handles retrieval of campaigns.

    Args:
        id: The id value of the campaign you want to get.
        no_body: boolean flag for response with/without body
    """

    _resp = sdk_request_sync(
        "GET",
        f"/campaigns/{encode_path_segment(id)}",
        params=serialize_query([("no_body", no_body, "form", True)]),
        operation_id="get_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCampaignByIdResponse"), GetCampaignByIdResponse
    )


async def update_campaign_by_id(
    _client_config: ClientConfig,
    id: int,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    lists: list[float] | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    send_later: bool | NotGiven = NOT_GIVEN,
    send_at: CampaignRequestSendAt | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateCampaignByIdResponse:
    """Replaces campaign details for the campaign identified by `id`. Supply the campaign
    fields you want to set, such as `name`, `subject`, or `lists`; the schema does not
    require any particular body fields. A successful response contains the updated
    campaign object.

    handle updation of campaign

    Args:
        id: the id value of campaign you want to update
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        send_later: Optional `boolean` value serialized in the `send_later` wire field.
        send_at: Optional object value serialized in the `send_at` wire field.
    """

    _resp = await sdk_request(
        "PUT",
        f"/campaigns/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[float]")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "send_later": (
                    NOT_GIVEN if send_later is NOT_GIVEN else to_wire(send_later, "bool")
                ),
                "send_at": (
                    NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "CampaignRequestSendAt")
                ),
            }
        ),
        operation_id="update_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateCampaignByIdResponse"),
        UpdateCampaignByIdResponse,
    )


def update_campaign_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    name: str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    lists: list[float] | NotGiven = NOT_GIVEN,
    from_email: str | NotGiven = NOT_GIVEN,
    content_type: str | NotGiven = NOT_GIVEN,
    messenger: str | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    send_later: bool | NotGiven = NOT_GIVEN,
    send_at: CampaignRequestSendAt | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateCampaignByIdResponse:
    """Replaces campaign details for the campaign identified by `id`. Supply the campaign
    fields you want to set, such as `name`, `subject`, or `lists`; the schema does not
    require any particular body fields. A successful response contains the updated
    campaign object.

    handle updation of campaign

    Args:
        id: the id value of campaign you want to update
        name: Optional `string` value serialized in the `name` wire field.
        subject: Optional `string` value serialized in the `subject` wire field.
        lists: Optional array value serialized in the `lists` wire field.
        from_email: Optional `string` value serialized in the `from_email` wire field.
        content_type: Optional `string` value serialized in the `content_type` wire field.
        messenger: Optional `string` value serialized in the `messenger` wire field.
        type: Optional `string` value serialized in the `type` wire field.
        tags: Optional array value serialized in the `tags` wire field.
        send_later: Optional `boolean` value serialized in the `send_later` wire field.
        send_at: Optional object value serialized in the `send_at` wire field.
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/campaigns/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "lists": (NOT_GIVEN if lists is NOT_GIVEN else to_wire(lists, "list[float]")),
                "from_email": (
                    NOT_GIVEN if from_email is NOT_GIVEN else to_wire(from_email, "str")
                ),
                "content_type": (
                    NOT_GIVEN if content_type is NOT_GIVEN else to_wire(content_type, "str")
                ),
                "messenger": (NOT_GIVEN if messenger is NOT_GIVEN else to_wire(messenger, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "send_later": (
                    NOT_GIVEN if send_later is NOT_GIVEN else to_wire(send_later, "bool")
                ),
                "send_at": (
                    NOT_GIVEN if send_at is NOT_GIVEN else to_wire(send_at, "CampaignRequestSendAt")
                ),
            }
        ),
        operation_id="update_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateCampaignByIdResponse"),
        UpdateCampaignByIdResponse,
    )


async def delete_campaign_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteCampaignByIdResponse:
    """Deletes the campaign identified by `id`. Use the campaign's integer identifier to
    select the campaign to remove. The response contains a boolean result.

    deletes specified campaign

    Args:
        id: The id value of the campaign you want to get.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/campaigns/{encode_path_segment(id)}",
        operation_id="delete_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteCampaignByIdResponse"),
        DeleteCampaignByIdResponse,
    )


def delete_campaign_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteCampaignByIdResponse:
    """Deletes the campaign identified by `id`. Use the campaign's integer identifier to
    select the campaign to remove. The response contains a boolean result.

    deletes specified campaign

    Args:
        id: The id value of the campaign you want to get.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/campaigns/{encode_path_segment(id)}",
        operation_id="delete_campaign_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteCampaignByIdResponse"),
        DeleteCampaignByIdResponse,
    )


__all__ = [
    "create_campaign",
    "create_campaign_sync",
    "delete_campaign_by_id",
    "delete_campaign_by_id_sync",
    "get_campaign_by_id",
    "get_campaign_by_id_sync",
    "get_campaigns",
    "get_campaigns_sync",
    "update_campaign_by_id",
    "update_campaign_by_id_sync",
]
