# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_date, validate_date_time


class CampaignListsItem(BaseModel):
    """Required object value serialized in the `lists[]` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""


class Campaign(BaseModel):
    """Typed representation of the `Campaign` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    updated_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `updated_at` wire field."""
    campaign_id: int | NotGiven = Field(NOT_GIVEN, alias="CampaignID")
    """Optional `integer` value serialized in the `CampaignID` wire field."""
    views: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `views` wire field."""
    clicks: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `clicks` wire field."""
    lists: list[CampaignListsItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `lists` wire field."""
    started_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `started_at` wire field."""
    to_send: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `to_send` wire field."""
    sent: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `sent` wire field."""
    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    type: Literal["regular", "optin"] | str | NotGiven = NOT_GIVEN
    """Optional enumerated value serialized in the `type` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    subject: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subject` wire field."""
    from_email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `from_email` wire field."""
    body: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `body` wire field."""
    send_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `send_at` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    content_type: Literal["richtext", "html", "markdown", "plain"] | str | NotGiven = NOT_GIVEN
    """Optional enumerated value serialized in the `content_type` wire field."""
    tags: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
    template_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `template_id` wire field."""
    messenger: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `messenger` wire field."""


class CampaignContentRequestListsItem(BaseModel):
    """Required object value serialized in the `lists[]` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""


class CampaignContentRequest(BaseModel):
    """Typed representation of the `CampaignContentRequest` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    updated_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `updated_at` wire field."""
    campaign_id: int | NotGiven = Field(NOT_GIVEN, alias="CampaignID")
    """Optional `integer` value serialized in the `CampaignID` wire field."""
    views: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `views` wire field."""
    clicks: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `clicks` wire field."""
    lists: list[CampaignContentRequestListsItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `lists` wire field."""
    started_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `started_at` wire field."""
    to_send: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `to_send` wire field."""
    sent: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `sent` wire field."""
    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    type: Literal["regular", "optin"] | str | NotGiven = NOT_GIVEN
    """Optional enumerated value serialized in the `type` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    subject: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subject` wire field."""
    from_email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `from_email` wire field."""
    body: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `body` wire field."""
    send_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `send_at` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    content_type: Literal["richtext", "html", "markdown", "plain"] | str | NotGiven = NOT_GIVEN
    """Optional enumerated value serialized in the `content_type` wire field."""
    tags: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
    template_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `template_id` wire field."""
    messenger: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `messenger` wire field."""
    from_: str | NotGiven = Field(NOT_GIVEN, alias="from")
    """Optional `string` value serialized in the `from` wire field."""
    to: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `to` wire field."""


class CampaignRequestSendAt(BaseModel):
    """Optional object value serialized in the `send_at` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `headers` wire field."""
    template_id: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `template_id` wire field."""


class CampaignRequest(BaseModel):
    """Typed representation of the `CampaignRequest` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    subject: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subject` wire field."""
    lists: list[float] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `lists` wire field."""
    from_email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `from_email` wire field."""
    content_type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `content_type` wire field."""
    messenger: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `messenger` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    tags: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
    send_later: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `send_later` wire field."""
    send_at: CampaignRequestSendAt | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `send_at` wire field."""


class CampaignUpdate(BaseModel):
    """Typed representation of the `CampaignUpdate` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    subject: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subject` wire field."""
    lists: list[int] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `lists` wire field."""
    from_email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `from_email` wire field."""
    messenger: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `messenger` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    tags: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
    send_later: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `send_later` wire field."""
    send_at: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `send_at` wire field."""
    headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `headers` wire field."""
    template_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `template_id` wire field."""
    content_type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `content_type` wire field."""
    body: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `body` wire field."""
    altbody: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `altbody` wire field."""
    archive: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `archive` wire field."""
    archive_template_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `archive_template_id` wire field."""
    archive_meta: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `archive_meta` wire field."""


class CampaignStats(BaseModel):
    """Typed representation of the `CampaignStats` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    to_send: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `to_send` wire field."""
    sent: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `sent` wire field."""
    started_at: datetime.date | NotGiven = NOT_GIVEN
    """Optional `date`-formatted value serialized in the `started_at` wire field."""
    updated_at: datetime.date | NotGiven = NOT_GIVEN
    """Optional `date`-formatted value serialized in the `updated_at` wire field."""
    rate: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `rate` wire field."""
    net_rate: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `net_rate` wire field."""

    @field_validator("started_at", mode="before")
    @classmethod
    def _validate_started_at(cls, value):
        validate_date("started_at", value)
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def _validate_updated_at(cls, value):
        validate_date("updated_at", value)
        return value


class CampaignAnalyticsCount(BaseModel):
    """Typed representation of the `CampaignAnalyticsCount` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    campaign_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `campaign_id` wire field."""
    count: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `count` wire field."""
    timestamp: datetime.datetime | NotGiven = NOT_GIVEN
    """Optional `date-time`-formatted value serialized in the `timestamp` wire field."""

    @field_validator("timestamp", mode="before")
    @classmethod
    def _validate_timestamp(cls, value):
        validate_date_time("timestamp", value)
        return value
