# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven
from listmonk_unofficial_sdk.types.campaigns import CampaignUpdate


class CreateCampaignResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: CampaignUpdate | NotGiven = NOT_GIVEN


class CreateCampaignContentByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: str | NotGiven = NOT_GIVEN
