# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven
from listmonk_unofficial_sdk.types.lists import ListModel
from listmonk_unofficial_sdk.types.subscribers import Subscriber
from listmonk_unofficial_sdk.types.templates import Template


class CreateSubscriberResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: Subscriber | NotGiven = NOT_GIVEN


class CreateListResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: ListModel | NotGiven = NOT_GIVEN


class CreateTemplateResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: Template | NotGiven = NOT_GIVEN
