# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class DeleteBouncesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class DeleteBounceByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class DeleteListByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class DeleteMediaByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class DeleteTemplateByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class DeleteGCSubscribersResponseData(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int | NotGiven = NOT_GIVEN


class DeleteGCSubscribersResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: DeleteGCSubscribersResponseData | NotGiven = NOT_GIVEN


class DeleteUnconfirmedSubscriptionsResponseData(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int | NotGiven = NOT_GIVEN


class DeleteUnconfirmedSubscriptionsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: DeleteUnconfirmedSubscriptionsResponseData | NotGiven = NOT_GIVEN
