# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class DeleteCampaignByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class DeleteCampaignAnalyticsByTypeResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN
