# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven
from listmonk_unofficial_sdk.types.campaigns import Campaign, CampaignStats
from listmonk_unofficial_sdk.types.lists import ListModel
from listmonk_unofficial_sdk.types.miscellaneous import LanguagePack, ServerConfig
from listmonk_unofficial_sdk.types.settings import Settings
from listmonk_unofficial_sdk.types.shared import Bounce
from listmonk_unofficial_sdk.types.subscribers import Subscriber
from listmonk_unofficial_sdk.types.templates import Template


class GetHealthCheckResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class GetServerConfigResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: ServerConfig | NotGiven = NOT_GIVEN


class GetI18nLangResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: LanguagePack | NotGiven = NOT_GIVEN


class GetSettingsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: Settings | NotGiven = NOT_GIVEN


class GetLogsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: list[str] | NotGiven = NOT_GIVEN


class GetSubscribersResponseData(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    results: list[Subscriber] | NotGiven = NOT_GIVEN
    query: str | NotGiven = NOT_GIVEN
    total: int | NotGiven = NOT_GIVEN
    per_page: int | NotGiven = NOT_GIVEN
    page: int | NotGiven = NOT_GIVEN


class GetSubscribersResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: GetSubscribersResponseData | NotGiven = NOT_GIVEN


class GetBouncesResponseData(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    results: list[Bounce] | NotGiven = NOT_GIVEN
    query: str | NotGiven = NOT_GIVEN
    total: int | NotGiven = NOT_GIVEN
    per_page: int | NotGiven = NOT_GIVEN
    page: int | NotGiven = NOT_GIVEN


class GetBouncesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: GetBouncesResponseData | NotGiven = NOT_GIVEN


class GetBounceByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: Bounce | NotGiven = NOT_GIVEN


class GetListsResponseData(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    results: list[ListModel] | NotGiven = NOT_GIVEN
    total: int | NotGiven = NOT_GIVEN
    per_page: int | NotGiven = NOT_GIVEN
    page: int | NotGiven = NOT_GIVEN


class GetListsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: GetListsResponseData | NotGiven = NOT_GIVEN


class GetListByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: ListModel | NotGiven = NOT_GIVEN


class GetCampaignsResponseData(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    results: list[Campaign] | NotGiven = NOT_GIVEN
    query: str | NotGiven = NOT_GIVEN
    total: int | NotGiven = NOT_GIVEN
    per_page: int | NotGiven = NOT_GIVEN
    page: int | NotGiven = NOT_GIVEN


class GetCampaignsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: GetCampaignsResponseData | NotGiven = NOT_GIVEN


class GetRunningCampaignStatsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: list[CampaignStats] | NotGiven = NOT_GIVEN


class GetTemplatesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: list[Template] | NotGiven = NOT_GIVEN


class GetTemplateByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: Template | NotGiven = NOT_GIVEN
