# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven
from listmonk_unofficial_sdk.types.shared import Bounce
from listmonk_unofficial_sdk.types.subscribers import Subscriber


class GetSubscriberByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: Subscriber | NotGiven = NOT_GIVEN


class GetSubscriberBouncesByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: list[Bounce] | NotGiven = NOT_GIVEN
