# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class ImportStatusData(BaseModel):
    """Optional object value serialized in the `data` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    total: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total` wire field."""
    imported: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `imported` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""


class ImportStatus(BaseModel):
    """Typed representation of the `ImportStatus` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: ImportStatusData | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""


class ImportSubscribersResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: ImportStatus | NotGiven = NOT_GIVEN
