# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class ListModel(BaseModel):
    """Typed representation of the `ListModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    updated_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `updated_at` wire field."""
    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    optin: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `optin` wire field."""
    tags: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
    subscriber_count: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `subscriber_count` wire field."""
    description: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `description` wire field."""


class NewList(BaseModel):
    """Typed representation of the `NewList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    type: Literal["public", "private"] | str | NotGiven = NOT_GIVEN
    """Optional enumerated value serialized in the `type` wire field."""
    optin: Literal["single", "double"] | str | NotGiven = NOT_GIVEN
    """Optional enumerated value serialized in the `optin` wire field."""
    tags: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
    description: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `description` wire field."""
