# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class MediaFileObject(BaseModel):
    """Typed representation of the `MediaFileObject` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    filename: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `filename` wire field."""
    content_type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `content_type` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    thumb_url: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `thumb_url` wire field."""
    thumb_uri: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `thumb_uri` wire field."""
    provider: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `provider` wire field."""
    meta: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `meta` wire field."""
    url: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `url` wire field."""
    uri: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uri` wire field."""
