# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven
from listmonk_unofficial_sdk.types.import_models import ImportStatus
from listmonk_unofficial_sdk.types.media import MediaFileObject


class ReloadAppResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class SubscriberSendOptinByIdResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class BlocklistSubscribersQueryResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class StopImportSubscribersResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: ImportStatus | NotGiven = NOT_GIVEN


class UploadMediaResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: MediaFileObject | NotGiven = NOT_GIVEN


class TransactWithSubscriberResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: bool | NotGiven = NOT_GIVEN


class HandlePublicSubscriptionResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    has_optin: bool | NotGiven = NOT_GIVEN
