# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class ServerConfigDataLangsItem(BaseModel):
    """Required object value serialized in the `langs[]` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    code: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `code` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""


class ServerConfigData(BaseModel):
    """Optional object value serialized in the `data` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    messengers: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `messengers` wire field."""
    langs: list[ServerConfigDataLangsItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `langs` wire field."""
    lang: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `lang` wire field."""
    update: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `update` wire field."""
    needs_restart: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `needs_restart` wire field."""
    version: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `version` wire field."""


class ServerConfig(BaseModel):
    """Typed representation of the `ServerConfig` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: ServerConfigData | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""


class DashboardChartLinkClicksItem(BaseModel):
    """Required object value serialized in the `link_clicks[]` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `count` wire field."""
    date: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `date` wire field."""


class DashboardChartCampaignViewsItem(BaseModel):
    """Required object value serialized in the `campaign_views[]` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `count` wire field."""
    date: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `date` wire field."""


class DashboardChart(BaseModel):
    """Typed representation of the `DashboardChart` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    link_clicks: list[DashboardChartLinkClicksItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `link_clicks` wire field."""
    campaign_views: list[DashboardChartCampaignViewsItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `campaign_views` wire field."""


class DashboardCountDataSubscribers(BaseModel):
    """Optional object value serialized in the `subscribers` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    total: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total` wire field."""
    blocklisted: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `blocklisted` wire field."""
    orphans: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `orphans` wire field."""


class DashboardCountDataLists(BaseModel):
    """Optional object value serialized in the `lists` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    total: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total` wire field."""
    private: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `private` wire field."""
    public: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `public` wire field."""
    optin_single: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `optin_single` wire field."""
    optin_double: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `optin_double` wire field."""


class DashboardCountDataCampaignsByStatus(BaseModel):
    """Optional object value serialized in the `by_status` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    draft: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `draft` wire field."""


class DashboardCountDataCampaigns(BaseModel):
    """Optional object value serialized in the `campaigns` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    total: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total` wire field."""
    by_status: DashboardCountDataCampaignsByStatus | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `by_status` wire field."""


class DashboardCountData(BaseModel):
    """Optional object value serialized in the `data` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    subscribers: DashboardCountDataSubscribers | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `subscribers` wire field."""
    lists: DashboardCountDataLists | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `lists` wire field."""
    campaigns: DashboardCountDataCampaigns | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `campaigns` wire field."""
    messages: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `messages` wire field."""


class DashboardCount(BaseModel):
    """Typed representation of the `DashboardCount` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: DashboardCountData | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""
