# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class SMTPSettings(BaseModel):
    """Typed representation of the `SMTPSettings` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    enabled: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `enabled` wire field."""
    host: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `host` wire field."""
    hello_hostname: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `hello_hostname` wire field."""
    port: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `port` wire field."""
    auth_protocol: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `auth_protocol` wire field."""
    username: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `username` wire field."""
    email_headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `email_headers` wire field."""
    max_conns: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `max_conns` wire field."""
    max_msg_retries: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `max_msg_retries` wire field."""
    idle_timeout: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `idle_timeout` wire field."""
    wait_timeout: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `wait_timeout` wire field."""
    tls_type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `tls_type` wire field."""
    tls_skip_verify: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `tls_skip_verify` wire field."""


class SMTPTest(BaseModel):
    """Typed representation of the `SMTPTest` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    enabled: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `enabled` wire field."""
    host: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `host` wire field."""
    hello_hostname: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `hello_hostname` wire field."""
    port: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `port` wire field."""
    auth_protocol: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `auth_protocol` wire field."""
    username: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `username` wire field."""
    email_headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `email_headers` wire field."""
    max_conns: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `max_conns` wire field."""
    max_msg_retries: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `max_msg_retries` wire field."""
    idle_timeout: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `idle_timeout` wire field."""
    wait_timeout: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `wait_timeout` wire field."""
    tls_type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `tls_type` wire field."""
    tls_skip_verify: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `tls_skip_verify` wire field."""
    str_email_headers: str | NotGiven = Field(NOT_GIVEN, alias="strEmailHeaders")
    """Optional `string` value serialized in the `strEmailHeaders` wire field."""
    password: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `password` wire field."""
    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""


class MailBoxBounces(BaseModel):
    """Typed representation of the `MailBoxBounces` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    enabled: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `enabled` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    host: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `host` wire field."""
    port: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `port` wire field."""
    auth_protocol: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `auth_protocol` wire field."""
    return_path: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `return_path` wire field."""
    username: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `username` wire field."""
    tls_enabled: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `tls_enabled` wire field."""
    tls_skip_verify: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `tls_skip_verify` wire field."""
    scan_interval: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `scan_interval` wire field."""


class Settings(BaseModel):
    """Typed representation of the `Settings` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    app_site_name: str | NotGiven = Field(NOT_GIVEN, alias="app.site_name")
    """Optional `string` value serialized in the `app.site_name` wire field."""
    app_root_url: str | NotGiven = Field(NOT_GIVEN, alias="app.root_url")
    """Optional `string` value serialized in the `app.root_url` wire field."""
    app_logo_url: str | NotGiven = Field(NOT_GIVEN, alias="app.logo_url")
    """Optional `string` value serialized in the `app.logo_url` wire field."""
    app_favicon_url: str | NotGiven = Field(NOT_GIVEN, alias="app.favicon_url")
    """Optional `string` value serialized in the `app.favicon_url` wire field."""
    app_from_email: str | NotGiven = Field(NOT_GIVEN, alias="app.from_email")
    """Optional `string` value serialized in the `app.from_email` wire field."""
    app_notify_emails: list[str] | NotGiven = Field(NOT_GIVEN, alias="app.notify_emails")
    """Optional array value serialized in the `app.notify_emails` wire field."""
    app_enable_public_subscription_page: bool | NotGiven = Field(
        NOT_GIVEN, alias="app.enable_public_subscription_page"
    )
    """Optional `boolean` value serialized in the `app.enable_public_subscription_page` wire field."""
    app_enable_public_archive: bool | NotGiven = Field(NOT_GIVEN, alias="app.enable_public_archive")
    """Optional `boolean` value serialized in the `app.enable_public_archive` wire field."""
    app_send_optin_confirmation: bool | NotGiven = Field(
        NOT_GIVEN, alias="app.send_optin_confirmation"
    )
    """Optional `boolean` value serialized in the `app.send_optin_confirmation` wire field."""
    app_check_updates: bool | NotGiven = Field(NOT_GIVEN, alias="app.check_updates")
    """Optional `boolean` value serialized in the `app.check_updates` wire field."""
    app_lang: str | NotGiven = Field(NOT_GIVEN, alias="app.lang")
    """Optional `string` value serialized in the `app.lang` wire field."""
    app_batch_size: int | NotGiven = Field(NOT_GIVEN, alias="app.batch_size")
    """Optional `integer` value serialized in the `app.batch_size` wire field."""
    app_concurrency: int | NotGiven = Field(NOT_GIVEN, alias="app.concurrency")
    """Optional `integer` value serialized in the `app.concurrency` wire field."""
    app_max_send_errors: int | NotGiven = Field(NOT_GIVEN, alias="app.max_send_errors")
    """Optional `integer` value serialized in the `app.max_send_errors` wire field."""
    app_message_rate: int | NotGiven = Field(NOT_GIVEN, alias="app.message_rate")
    """Optional `integer` value serialized in the `app.message_rate` wire field."""
    app_message_sliding_window: bool | NotGiven = Field(
        NOT_GIVEN, alias="app.message_sliding_window"
    )
    """Optional `boolean` value serialized in the `app.message_sliding_window` wire field."""
    app_message_sliding_window_duration: str | NotGiven = Field(
        NOT_GIVEN, alias="app.message_sliding_window_duration"
    )
    """Optional `string` value serialized in the `app.message_sliding_window_duration` wire field."""
    app_message_sliding_window_rate: int | NotGiven = Field(
        NOT_GIVEN, alias="app.message_sliding_window_rate"
    )
    """Optional `integer` value serialized in the `app.message_sliding_window_rate` wire field."""
    privacy_individual_tracking: bool | NotGiven = Field(
        NOT_GIVEN, alias="privacy.individual_tracking"
    )
    """Optional `boolean` value serialized in the `privacy.individual_tracking` wire field."""
    privacy_unsubscribe_header: bool | NotGiven = Field(
        NOT_GIVEN, alias="privacy.unsubscribe_header"
    )
    """Optional `boolean` value serialized in the `privacy.unsubscribe_header` wire field."""
    privacy_allow_blocklist: bool | NotGiven = Field(NOT_GIVEN, alias="privacy.allow_blocklist")
    """Optional `boolean` value serialized in the `privacy.allow_blocklist` wire field."""
    privacy_allow_preferences: bool | NotGiven = Field(NOT_GIVEN, alias="privacy.allow_preferences")
    """Optional `boolean` value serialized in the `privacy.allow_preferences` wire field."""
    privacy_allow_export: bool | NotGiven = Field(NOT_GIVEN, alias="privacy.allow_export")
    """Optional `boolean` value serialized in the `privacy.allow_export` wire field."""
    privacy_allow_wipe: bool | NotGiven = Field(NOT_GIVEN, alias="privacy.allow_wipe")
    """Optional `boolean` value serialized in the `privacy.allow_wipe` wire field."""
    privacy_exportable: list[str] | NotGiven = Field(NOT_GIVEN, alias="privacy.exportable")
    """Optional array value serialized in the `privacy.exportable` wire field."""
    privacy_domain_blocklist: list[dict[str, Any]] | NotGiven = Field(
        NOT_GIVEN, alias="privacy.domain_blocklist"
    )
    """Optional array value serialized in the `privacy.domain_blocklist` wire field."""
    upload_provider: str | NotGiven = Field(NOT_GIVEN, alias="upload.provider")
    """Optional `string` value serialized in the `upload.provider` wire field."""
    upload_filesystem_upload_path: str | NotGiven = Field(
        NOT_GIVEN, alias="upload.filesystem.upload_path"
    )
    """Optional `string` value serialized in the `upload.filesystem.upload_path` wire field."""
    upload_filesystem_upload_uri: str | NotGiven = Field(
        NOT_GIVEN, alias="upload.filesystem.upload_uri"
    )
    """Optional `string` value serialized in the `upload.filesystem.upload_uri` wire field."""
    upload_s3_url: str | NotGiven = Field(NOT_GIVEN, alias="upload.s3.url")
    """Optional `string` value serialized in the `upload.s3.url` wire field."""
    upload_s3_public_url: str | NotGiven = Field(NOT_GIVEN, alias="upload.s3.public_url")
    """Optional `string` value serialized in the `upload.s3.public_url` wire field."""
    upload_s3_aws_access_key_id: str | NotGiven = Field(
        NOT_GIVEN, alias="upload.s3.aws_access_key_id"
    )
    """Optional `string` value serialized in the `upload.s3.aws_access_key_id` wire field."""
    upload_s3_aws_default_region: str | NotGiven = Field(
        NOT_GIVEN, alias="upload.s3.aws_default_region"
    )
    """Optional `string` value serialized in the `upload.s3.aws_default_region` wire field."""
    upload_s3_bucket: str | NotGiven = Field(NOT_GIVEN, alias="upload.s3.bucket")
    """Optional `string` value serialized in the `upload.s3.bucket` wire field."""
    upload_s3_bucket_domain: str | NotGiven = Field(NOT_GIVEN, alias="upload.s3.bucket_domain")
    """Optional `string` value serialized in the `upload.s3.bucket_domain` wire field."""
    upload_s3_bucket_path: str | NotGiven = Field(NOT_GIVEN, alias="upload.s3.bucket_path")
    """Optional `string` value serialized in the `upload.s3.bucket_path` wire field."""
    upload_s3_bucket_type: str | NotGiven = Field(NOT_GIVEN, alias="upload.s3.bucket_type")
    """Optional `string` value serialized in the `upload.s3.bucket_type` wire field."""
    upload_s3_expiry: str | NotGiven = Field(NOT_GIVEN, alias="upload.s3.expiry")
    """Optional `string` value serialized in the `upload.s3.expiry` wire field."""
    smtp: list[SMTPSettings] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `smtp` wire field."""
    messengers: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `messengers` wire field."""
    bounce_enabled: bool | NotGiven = Field(NOT_GIVEN, alias="bounce.enabled")
    """Optional `boolean` value serialized in the `bounce.enabled` wire field."""
    bounce_webhooks_enabled: bool | NotGiven = Field(NOT_GIVEN, alias="bounce.webhooks_enabled")
    """Optional `boolean` value serialized in the `bounce.webhooks_enabled` wire field."""
    bounce_count: int | NotGiven = Field(NOT_GIVEN, alias="bounce.count")
    """Optional `integer` value serialized in the `bounce.count` wire field."""
    bounce_action: str | NotGiven = Field(NOT_GIVEN, alias="bounce.action")
    """Optional `string` value serialized in the `bounce.action` wire field."""
    bounce_ses_enabled: bool | NotGiven = Field(NOT_GIVEN, alias="bounce.ses_enabled")
    """Optional `boolean` value serialized in the `bounce.ses_enabled` wire field."""
    bounce_azure_enabled: bool | NotGiven = Field(NOT_GIVEN, alias="bounce.azure.enabled")
    """Optional `boolean` value serialized in the `bounce.azure.enabled` wire field."""
    bounce_azure_shared_secret: str | NotGiven = Field(
        NOT_GIVEN, alias="bounce.azure.shared_secret"
    )
    """Optional `string` value serialized in the `bounce.azure.shared_secret` wire field."""
    bounce_azure_shared_secret_header: str | NotGiven = Field(
        NOT_GIVEN, alias="bounce.azure.shared_secret_header"
    )
    """Optional `string` value serialized in the `bounce.azure.shared_secret_header` wire field."""
    bounce_sendgrid_enabled: bool | NotGiven = Field(NOT_GIVEN, alias="bounce.sendgrid_enabled")
    """Optional `boolean` value serialized in the `bounce.sendgrid_enabled` wire field."""
    bounce_sendgrid_key: str | NotGiven = Field(NOT_GIVEN, alias="bounce.sendgrid_key")
    """Optional `string` value serialized in the `bounce.sendgrid_key` wire field."""
    bounce_forwardemail_enabled: bool | NotGiven = Field(
        NOT_GIVEN, alias="bounce.forwardemail_enabled"
    )
    """Optional `boolean` value serialized in the `bounce.forwardemail_enabled` wire field."""
    bounce_forwardemail_key: str | NotGiven = Field(NOT_GIVEN, alias="bounce.forwardemail_key")
    """Optional `string` value serialized in the `bounce.forwardemail_key` wire field."""
    bounce_postmark_enabled: bool | NotGiven = Field(NOT_GIVEN, alias="bounce.postmark_enabled")
    """Optional `boolean` value serialized in the `bounce.postmark_enabled` wire field."""
    bounce_postmark_username: str | NotGiven = Field(NOT_GIVEN, alias="bounce.postmark_username")
    """Optional `string` value serialized in the `bounce.postmark_username` wire field."""
    bounce_postmark_password: str | NotGiven = Field(NOT_GIVEN, alias="bounce.postmark_password")
    """Optional `string` value serialized in the `bounce.postmark_password` wire field."""
    bounce_mailboxes: list[MailBoxBounces] | NotGiven = Field(NOT_GIVEN, alias="bounce.mailboxes")
    """Optional array value serialized in the `bounce.mailboxes` wire field."""
    appearance_admin_custom_css: str | NotGiven = Field(
        NOT_GIVEN, alias="appearance.admin.custom_css"
    )
    """Optional `string` value serialized in the `appearance.admin.custom_css` wire field."""
    appearance_admin_custom_js: str | NotGiven = Field(
        NOT_GIVEN, alias="appearance.admin.custom_js"
    )
    """Optional `string` value serialized in the `appearance.admin.custom_js` wire field."""
    appearance_public_custom_css: str | NotGiven = Field(
        NOT_GIVEN, alias="appearance.public.custom_css"
    )
    """Optional `string` value serialized in the `appearance.public.custom_css` wire field."""
    appearance_public_custom_js: str | NotGiven = Field(
        NOT_GIVEN, alias="appearance.public.custom_js"
    )
    """Optional `string` value serialized in the `appearance.public.custom_js` wire field."""
