# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class BounceResultsItemCampaign(BaseModel):
    """Optional object value serialized in the `campaign` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""


class BounceResultsItem(BaseModel):
    """Required object value serialized in the `results[]` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    source: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `source` wire field."""
    meta: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `meta` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    subscriber_uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subscriber_uuid` wire field."""
    subscriber_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `subscriber_id` wire field."""
    campaign: BounceResultsItemCampaign | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `campaign` wire field."""
    campaign_uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `campaign_uuid` wire field."""
    total: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total` wire field."""


class Bounce(BaseModel):
    """Typed representation of the `Bounce` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    results: list[BounceResultsItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `results` wire field."""
