# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class SubscriberProfile(BaseModel):
    """Typed representation of the `SubscriberProfile` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `attribs` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    updated_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `updated_at` wire field."""


class Subscriptions(BaseModel):
    """Typed representation of the `Subscriptions` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    subscription_status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subscription_status` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""


class SubscriberData(BaseModel):
    """Typed representation of the `SubscriberData` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    profile: list[SubscriberProfile] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `profile` wire field."""
    subscriptions: list[Subscriptions] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `subscriptions` wire field."""
    campaign_views: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `campaign_views` wire field."""
    link_clicks: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `link_clicks` wire field."""


class SubscriberListsItem(BaseModel):
    """Required object value serialized in the `lists[]` wire field."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    subscription_status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subscription_status` wire field."""
    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    tags: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    updated_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `updated_at` wire field."""


class Subscriber(BaseModel):
    """Typed representation of the `Subscriber` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    updated_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `updated_at` wire field."""
    uuid: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `uuid` wire field."""
    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `attribs` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    lists: list[SubscriberListsItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `lists` wire field."""


class NewSubscriber(BaseModel):
    """Typed representation of the `NewSubscriber` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    lists: list[int] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `lists` wire field."""
    list_uuids: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `list_uuids` wire field."""
    preconfirm_subscriptions: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `preconfirm_subscriptions` wire field."""
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `attribs` wire field."""


class UpdateSubscriber(BaseModel):
    """Typed representation of the `UpdateSubscriber` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    lists: list[int] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `lists` wire field."""
    list_uuids: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `list_uuids` wire field."""
    preconfirm_subscriptions: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `preconfirm_subscriptions` wire field."""
    attribs: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `attribs` wire field."""


class SubscriberQueryRequest(BaseModel):
    """Typed representation of the `SubscriberQueryRequest` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    query: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `query` wire field."""
    ids: list[int] | NotGiven = NOT_GIVEN
    """The ids of the subscribers to be modified."""
    action: Literal["add", "remove", "unsubscribe"] | str | NotGiven = NOT_GIVEN
    """Whether to add, remove, or unsubscribe the users."""
    target_list_ids: int | NotGiven = NOT_GIVEN
    """The ids of the lists to be modified."""
    status: Literal["confirmed", "unconfirmed", "unsubscribed"] | str | NotGiven = NOT_GIVEN
    """confirmed, unconfirmed, or unsubscribed status."""
