# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, model_validator

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_required


class Template(BaseModel):
    """Typed representation of the `Template` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    updated_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `updated_at` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    body: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `body` wire field."""
    body_source: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `body_source` wire field."""
    subject: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subject` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    is_default: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_default` wire field."""


class NewTemplate(BaseModel):
    """Typed representation of the `NewTemplate` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str
    """Name of the template"""
    type: Literal["campaign", "campaign_visual", "tx"] | str
    """Type of the template"""
    body: str
    """HTML body of the template"""
    subject: str | NotGiven = NOT_GIVEN
    """Subject line for the template (only for tx)"""
    body_source: str | NotGiven = NOT_GIVEN
    """JSON source for the email-builder template (only for campaign_visual)"""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "type", "body"])
        return value


class UpdateTemplate(BaseModel):
    """Typed representation of the `UpdateTemplate` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """Name of the template"""
    type: Literal["campaign", "campaign_visual", "tx"] | str | NotGiven = NOT_GIVEN
    """Type of the template"""
    subject: str | NotGiven = NOT_GIVEN
    """Subject line for the template (only for tx)"""
    body_source: str | NotGiven = NOT_GIVEN
    """JSON source for the email-builder template (only for campaign_visual)"""
    body: str | NotGiven = NOT_GIVEN
    """HTML body of the template"""
