# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from listmonk_unofficial_sdk.client import NOT_GIVEN, NotGiven


class TransactionalMessage(BaseModel):
    """Typed representation of the `TransactionalMessage` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    subscriber_email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `subscriber_email` wire field."""
    subscriber_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `subscriber_id` wire field."""
    template_id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `template_id` wire field."""
    from_email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `from_email` wire field."""
    data: dict[str, Any] | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""
    headers: list[dict[str, Any]] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `headers` wire field."""
    messenger: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `messenger` wire field."""
    content_type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `content_type` wire field."""
