# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from ..client import ClientConfig, LoggingConfig
from .admin import _AdminNamespace
from .bounces import _BouncesNamespace
from .campaigns import _CampaignsNamespace
from .import_ import _ImportNamespace
from .lists import _ListsNamespace
from .logs import _LogsNamespace
from .maintenance import _MaintenanceNamespace
from .media import _MediaNamespace
from .miscellaneous import _MiscellaneousNamespace
from .public import _PublicNamespace
from .settings import _SettingsNamespace
from .subscribers import _SubscribersNamespace
from .templates import _TemplatesNamespace
from .transactional import _TransactionalNamespace


class Listmonk:
    def __init__(self, config: ClientConfig) -> None:
        self._config = config
        self.miscellaneous = _MiscellaneousNamespace(config)
        self.settings = _SettingsNamespace(config)
        self.admin = _AdminNamespace(config)
        self.logs = _LogsNamespace(config)
        self.subscribers = _SubscribersNamespace(config)
        self.bounces = _BouncesNamespace(config)
        self.lists = _ListsNamespace(config)
        self.import_ = _ImportNamespace(config)
        self.campaigns = _CampaignsNamespace(config)
        self.media = _MediaNamespace(config)
        self.templates = _TemplatesNamespace(config)
        self.transactional = _TransactionalNamespace(config)
        self.maintenance = _MaintenanceNamespace(config)
        self.public = _PublicNamespace(config)

    def set_logging_config(
        self, config: LoggingConfig | None = None, **fields: Any
    ) -> LoggingConfig:
        """Turn SDK logging on and configure it.

        Logging is OFF by default — this SDK reports nothing until you call this
        (or construct the client with logging enabled). Reports go to the endpoint
        this build was generated with, or to the endpoint you pass; with neither,
        nothing is sent. Pass enabled=False to turn logging back off.
        """
        if self._config.logging is None:
            self._config.logging = LoggingConfig()
        current = self._config.logging
        if config is not None:
            for key, value in vars(config).items():
                if key != "enabled":
                    setattr(current, key, value)
        current.enabled = True
        for key, value in fields.items():
            if not hasattr(current, key):
                raise TypeError(f"LoggingConfig has no field {key!r}")
            setattr(current, key, value)
        return current


__all__ = ["Listmonk"]
