# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.admin import reload_app, reload_app_sync


class _AdminNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.reload_app = partial(reload_app, config)
        self.reload_app.__doc__ = reload_app.__doc__
        self.reload_app_sync = partial(reload_app_sync, config)
        self.reload_app_sync.__doc__ = reload_app_sync.__doc__
