# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.bounces import (
    delete_bounce_by_id,
    delete_bounce_by_id_sync,
    delete_bounces,
    delete_bounces_sync,
    get_bounce_by_id,
    get_bounce_by_id_sync,
    get_bounces,
    get_bounces_sync,
)


class _BouncesNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_bounces, config)
        self.get.__doc__ = get_bounces.__doc__
        self.get_sync = partial(get_bounces_sync, config)
        self.get_sync.__doc__ = get_bounces_sync.__doc__
        self.delete = partial(delete_bounces, config)
        self.delete.__doc__ = delete_bounces.__doc__
        self.delete_sync = partial(delete_bounces_sync, config)
        self.delete_sync.__doc__ = delete_bounces_sync.__doc__
        self.get_by_id = partial(get_bounce_by_id, config)
        self.get_by_id.__doc__ = get_bounce_by_id.__doc__
        self.get_by_id_sync = partial(get_bounce_by_id_sync, config)
        self.get_by_id_sync.__doc__ = get_bounce_by_id_sync.__doc__
        self.delete_by_id = partial(delete_bounce_by_id, config)
        self.delete_by_id.__doc__ = delete_bounce_by_id.__doc__
        self.delete_by_id_sync = partial(delete_bounce_by_id_sync, config)
        self.delete_by_id_sync.__doc__ = delete_bounce_by_id_sync.__doc__
