# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.campaigns import (
    create_campaign,
    create_campaign_content_by_id,
    create_campaign_content_by_id_sync,
    create_campaign_sync,
    delete_campaign_by_id,
    delete_campaign_by_id_sync,
    get_campaign_analytics,
    get_campaign_analytics_sync,
    get_campaign_by_id,
    get_campaign_by_id_sync,
    get_campaigns,
    get_campaigns_sync,
    get_running_campaign_stats,
    get_running_campaign_stats_sync,
    preview_campaign_by_id,
    preview_campaign_by_id_sync,
    preview_campaign_text_by_id,
    preview_campaign_text_by_id_sync,
    test_campaign_by_id,
    test_campaign_by_id_form,
    test_campaign_by_id_form_sync,
    test_campaign_by_id_sync,
    update_campaign_archive_by_id,
    update_campaign_archive_by_id_sync,
    update_campaign_by_id,
    update_campaign_by_id_sync,
    update_campaign_status_by_id,
    update_campaign_status_by_id_sync,
    update_preview_campaign_by_id,
    update_preview_campaign_by_id_sync,
)


class _CampaignsNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_campaigns, config)
        self.get.__doc__ = get_campaigns.__doc__
        self.get_sync = partial(get_campaigns_sync, config)
        self.get_sync.__doc__ = get_campaigns_sync.__doc__
        self.create = partial(create_campaign, config)
        self.create.__doc__ = create_campaign.__doc__
        self.create_sync = partial(create_campaign_sync, config)
        self.create_sync.__doc__ = create_campaign_sync.__doc__
        self.get_by_id = partial(get_campaign_by_id, config)
        self.get_by_id.__doc__ = get_campaign_by_id.__doc__
        self.get_by_id_sync = partial(get_campaign_by_id_sync, config)
        self.get_by_id_sync.__doc__ = get_campaign_by_id_sync.__doc__
        self.update_by_id = partial(update_campaign_by_id, config)
        self.update_by_id.__doc__ = update_campaign_by_id.__doc__
        self.update_by_id_sync = partial(update_campaign_by_id_sync, config)
        self.update_by_id_sync.__doc__ = update_campaign_by_id_sync.__doc__
        self.delete_by_id = partial(delete_campaign_by_id, config)
        self.delete_by_id.__doc__ = delete_campaign_by_id.__doc__
        self.delete_by_id_sync = partial(delete_campaign_by_id_sync, config)
        self.delete_by_id_sync.__doc__ = delete_campaign_by_id_sync.__doc__
        self.get_running_stats = partial(get_running_campaign_stats, config)
        self.get_running_stats.__doc__ = get_running_campaign_stats.__doc__
        self.get_running_stats_sync = partial(get_running_campaign_stats_sync, config)
        self.get_running_stats_sync.__doc__ = get_running_campaign_stats_sync.__doc__
        self.get_analytics = partial(get_campaign_analytics, config)
        self.get_analytics.__doc__ = get_campaign_analytics.__doc__
        self.get_analytics_sync = partial(get_campaign_analytics_sync, config)
        self.get_analytics_sync.__doc__ = get_campaign_analytics_sync.__doc__
        self.preview_by_id = partial(preview_campaign_by_id, config)
        self.preview_by_id.__doc__ = preview_campaign_by_id.__doc__
        self.preview_by_id_sync = partial(preview_campaign_by_id_sync, config)
        self.preview_by_id_sync.__doc__ = preview_campaign_by_id_sync.__doc__
        self.update_preview_by_id = partial(update_preview_campaign_by_id, config)
        self.update_preview_by_id.__doc__ = update_preview_campaign_by_id.__doc__
        self.update_preview_by_id_sync = partial(update_preview_campaign_by_id_sync, config)
        self.update_preview_by_id_sync.__doc__ = update_preview_campaign_by_id_sync.__doc__
        self.preview_text_by_id = partial(preview_campaign_text_by_id, config)
        self.preview_text_by_id.__doc__ = preview_campaign_text_by_id.__doc__
        self.preview_text_by_id_sync = partial(preview_campaign_text_by_id_sync, config)
        self.preview_text_by_id_sync.__doc__ = preview_campaign_text_by_id_sync.__doc__
        self.update_status_by_id = partial(update_campaign_status_by_id, config)
        self.update_status_by_id.__doc__ = update_campaign_status_by_id.__doc__
        self.update_status_by_id_sync = partial(update_campaign_status_by_id_sync, config)
        self.update_status_by_id_sync.__doc__ = update_campaign_status_by_id_sync.__doc__
        self.update_archive_by_id = partial(update_campaign_archive_by_id, config)
        self.update_archive_by_id.__doc__ = update_campaign_archive_by_id.__doc__
        self.update_archive_by_id_sync = partial(update_campaign_archive_by_id_sync, config)
        self.update_archive_by_id_sync.__doc__ = update_campaign_archive_by_id_sync.__doc__
        self.create_content_by_id = partial(create_campaign_content_by_id, config)
        self.create_content_by_id.__doc__ = create_campaign_content_by_id.__doc__
        self.create_content_by_id_sync = partial(create_campaign_content_by_id_sync, config)
        self.create_content_by_id_sync.__doc__ = create_campaign_content_by_id_sync.__doc__
        self.test_by_id = partial(test_campaign_by_id, config)
        self.test_by_id.__doc__ = test_campaign_by_id.__doc__
        self.test_by_id_sync = partial(test_campaign_by_id_sync, config)
        self.test_by_id_sync.__doc__ = test_campaign_by_id_sync.__doc__
        self.test_by_id_form = partial(test_campaign_by_id_form, config)
        self.test_by_id_form.__doc__ = test_campaign_by_id_form.__doc__
        self.test_by_id_form_sync = partial(test_campaign_by_id_form_sync, config)
        self.test_by_id_form_sync.__doc__ = test_campaign_by_id_form_sync.__doc__
