# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.import_ import (
    get_import_subscriber_logs,
    get_import_subscriber_logs_sync,
    get_import_subscribers,
    get_import_subscribers_sync,
    import_subscribers,
    import_subscribers_sync,
    stop_import_subscribers,
    stop_import_subscribers_sync,
)


class _ImportNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get_subscribers = partial(get_import_subscribers, config)
        self.get_subscribers.__doc__ = get_import_subscribers.__doc__
        self.get_subscribers_sync = partial(get_import_subscribers_sync, config)
        self.get_subscribers_sync.__doc__ = get_import_subscribers_sync.__doc__
        self.subscribers = partial(import_subscribers, config)
        self.subscribers.__doc__ = import_subscribers.__doc__
        self.subscribers_sync = partial(import_subscribers_sync, config)
        self.subscribers_sync.__doc__ = import_subscribers_sync.__doc__
        self.stop_subscribers = partial(stop_import_subscribers, config)
        self.stop_subscribers.__doc__ = stop_import_subscribers.__doc__
        self.stop_subscribers_sync = partial(stop_import_subscribers_sync, config)
        self.stop_subscribers_sync.__doc__ = stop_import_subscribers_sync.__doc__
        self.get_subscriber_logs = partial(get_import_subscriber_logs, config)
        self.get_subscriber_logs.__doc__ = get_import_subscriber_logs.__doc__
        self.get_subscriber_logs_sync = partial(get_import_subscriber_logs_sync, config)
        self.get_subscriber_logs_sync.__doc__ = get_import_subscriber_logs_sync.__doc__
