# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.lists import (
    create_list,
    create_list_sync,
    delete_list_by_id,
    delete_list_by_id_sync,
    get_list_by_id,
    get_list_by_id_sync,
    get_lists,
    get_lists_sync,
    update_list_by_id,
    update_list_by_id_sync,
)


class _ListsNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_lists, config)
        self.get.__doc__ = get_lists.__doc__
        self.get_sync = partial(get_lists_sync, config)
        self.get_sync.__doc__ = get_lists_sync.__doc__
        self.create = partial(create_list, config)
        self.create.__doc__ = create_list.__doc__
        self.create_sync = partial(create_list_sync, config)
        self.create_sync.__doc__ = create_list_sync.__doc__
        self.get_by_id = partial(get_list_by_id, config)
        self.get_by_id.__doc__ = get_list_by_id.__doc__
        self.get_by_id_sync = partial(get_list_by_id_sync, config)
        self.get_by_id_sync.__doc__ = get_list_by_id_sync.__doc__
        self.update_by_id = partial(update_list_by_id, config)
        self.update_by_id.__doc__ = update_list_by_id.__doc__
        self.update_by_id_sync = partial(update_list_by_id_sync, config)
        self.update_by_id_sync.__doc__ = update_list_by_id_sync.__doc__
        self.delete_by_id = partial(delete_list_by_id, config)
        self.delete_by_id.__doc__ = delete_list_by_id.__doc__
        self.delete_by_id_sync = partial(delete_list_by_id_sync, config)
        self.delete_by_id_sync.__doc__ = delete_list_by_id_sync.__doc__
