# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.logs import get_logs, get_logs_sync


class _LogsNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_logs, config)
        self.get.__doc__ = get_logs.__doc__
        self.get_sync = partial(get_logs_sync, config)
        self.get_sync.__doc__ = get_logs_sync.__doc__
