# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.maintenance import (
    delete_campaign_analytics_by_type,
    delete_campaign_analytics_by_type_sync,
    delete_gc_subscribers,
    delete_gc_subscribers_sync,
    delete_unconfirmed_subscriptions,
    delete_unconfirmed_subscriptions_sync,
)


class _MaintenanceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.delete_gc_subscribers = partial(delete_gc_subscribers, config)
        self.delete_gc_subscribers.__doc__ = delete_gc_subscribers.__doc__
        self.delete_gc_subscribers_sync = partial(delete_gc_subscribers_sync, config)
        self.delete_gc_subscribers_sync.__doc__ = delete_gc_subscribers_sync.__doc__
        self.delete_campaign_analytics_by_type = partial(delete_campaign_analytics_by_type, config)
        self.delete_campaign_analytics_by_type.__doc__ = delete_campaign_analytics_by_type.__doc__
        self.delete_campaign_analytics_by_type_sync = partial(
            delete_campaign_analytics_by_type_sync, config
        )
        self.delete_campaign_analytics_by_type_sync.__doc__ = (
            delete_campaign_analytics_by_type_sync.__doc__
        )
        self.delete_unconfirmed_subscriptions = partial(delete_unconfirmed_subscriptions, config)
        self.delete_unconfirmed_subscriptions.__doc__ = delete_unconfirmed_subscriptions.__doc__
        self.delete_unconfirmed_subscriptions_sync = partial(
            delete_unconfirmed_subscriptions_sync, config
        )
        self.delete_unconfirmed_subscriptions_sync.__doc__ = (
            delete_unconfirmed_subscriptions_sync.__doc__
        )
