# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.media import (
    delete_media_by_id,
    delete_media_by_id_sync,
    get_media,
    get_media_by_id,
    get_media_by_id_sync,
    get_media_sync,
    upload_media,
    upload_media_sync,
)


class _MediaNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_media, config)
        self.get.__doc__ = get_media.__doc__
        self.get_sync = partial(get_media_sync, config)
        self.get_sync.__doc__ = get_media_sync.__doc__
        self.upload = partial(upload_media, config)
        self.upload.__doc__ = upload_media.__doc__
        self.upload_sync = partial(upload_media_sync, config)
        self.upload_sync.__doc__ = upload_media_sync.__doc__
        self.get_by_id = partial(get_media_by_id, config)
        self.get_by_id.__doc__ = get_media_by_id.__doc__
        self.get_by_id_sync = partial(get_media_by_id_sync, config)
        self.get_by_id_sync.__doc__ = get_media_by_id_sync.__doc__
        self.delete_by_id = partial(delete_media_by_id, config)
        self.delete_by_id.__doc__ = delete_media_by_id.__doc__
        self.delete_by_id_sync = partial(delete_media_by_id_sync, config)
        self.delete_by_id_sync.__doc__ = delete_media_by_id_sync.__doc__
