# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.miscellaneous import (
    get_dashboard_charts,
    get_dashboard_charts_sync,
    get_dashboard_counts,
    get_dashboard_counts_sync,
    get_health_check,
    get_health_check_sync,
    get_i18n_lang,
    get_i18n_lang_sync,
    get_server_config,
    get_server_config_sync,
)


class _MiscellaneousNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get_health_check = partial(get_health_check, config)
        self.get_health_check.__doc__ = get_health_check.__doc__
        self.get_health_check_sync = partial(get_health_check_sync, config)
        self.get_health_check_sync.__doc__ = get_health_check_sync.__doc__
        self.get_server_config = partial(get_server_config, config)
        self.get_server_config.__doc__ = get_server_config.__doc__
        self.get_server_config_sync = partial(get_server_config_sync, config)
        self.get_server_config_sync.__doc__ = get_server_config_sync.__doc__
        self.get_i18n_lang = partial(get_i18n_lang, config)
        self.get_i18n_lang.__doc__ = get_i18n_lang.__doc__
        self.get_i18n_lang_sync = partial(get_i18n_lang_sync, config)
        self.get_i18n_lang_sync.__doc__ = get_i18n_lang_sync.__doc__
        self.get_dashboard_charts = partial(get_dashboard_charts, config)
        self.get_dashboard_charts.__doc__ = get_dashboard_charts.__doc__
        self.get_dashboard_charts_sync = partial(get_dashboard_charts_sync, config)
        self.get_dashboard_charts_sync.__doc__ = get_dashboard_charts_sync.__doc__
        self.get_dashboard_counts = partial(get_dashboard_counts, config)
        self.get_dashboard_counts.__doc__ = get_dashboard_counts.__doc__
        self.get_dashboard_counts_sync = partial(get_dashboard_counts_sync, config)
        self.get_dashboard_counts_sync.__doc__ = get_dashboard_counts_sync.__doc__
