# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.public import (
    get_public_lists,
    get_public_lists_sync,
    handle_public_subscription,
    handle_public_subscription_sync,
)


class _PublicNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get_lists = partial(get_public_lists, config)
        self.get_lists.__doc__ = get_public_lists.__doc__
        self.get_lists_sync = partial(get_public_lists_sync, config)
        self.get_lists_sync.__doc__ = get_public_lists_sync.__doc__
        self.handle_subscription = partial(handle_public_subscription, config)
        self.handle_subscription.__doc__ = handle_public_subscription.__doc__
        self.handle_subscription_sync = partial(handle_public_subscription_sync, config)
        self.handle_subscription_sync.__doc__ = handle_public_subscription_sync.__doc__
