# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.settings import (
    get_settings,
    get_settings_sync,
    test_smtp_settings,
    test_smtp_settings_sync,
    update_settings,
    update_settings_sync,
)


class _SettingsNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_settings, config)
        self.get.__doc__ = get_settings.__doc__
        self.get_sync = partial(get_settings_sync, config)
        self.get_sync.__doc__ = get_settings_sync.__doc__
        self.update = partial(update_settings, config)
        self.update.__doc__ = update_settings.__doc__
        self.update_sync = partial(update_settings_sync, config)
        self.update_sync.__doc__ = update_settings_sync.__doc__
        self.test_smtp = partial(test_smtp_settings, config)
        self.test_smtp.__doc__ = test_smtp_settings.__doc__
        self.test_smtp_sync = partial(test_smtp_settings_sync, config)
        self.test_smtp_sync.__doc__ = test_smtp_settings_sync.__doc__
