# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.subscribers import (
    blocklist_subscribers_query,
    blocklist_subscribers_query_sync,
    blocklist_subscribers_query_text,
    blocklist_subscribers_query_text_sync,
    create_subscriber,
    create_subscriber_sync,
    delete_subscriber_bounces_by_id,
    delete_subscriber_bounces_by_id_sync,
    delete_subscriber_by_id,
    delete_subscriber_by_id_sync,
    delete_subscriber_by_list,
    delete_subscriber_by_list_sync,
    delete_subscriber_by_query,
    delete_subscriber_by_query_sync,
    delete_subscriber_by_query_text,
    delete_subscriber_by_query_text_sync,
    export_subscriber_data_by_id,
    export_subscriber_data_by_id_sync,
    get_subscriber_bounces_by_id,
    get_subscriber_bounces_by_id_sync,
    get_subscriber_by_id,
    get_subscriber_by_id_sync,
    get_subscribers,
    get_subscribers_sync,
    manage_blocklist_by_subscriber_list,
    manage_blocklist_by_subscriber_list_sync,
    manage_blocklist_subscribers_by_id,
    manage_blocklist_subscribers_by_id_sync,
    manage_subscriber_list_by_id,
    manage_subscriber_list_by_id_sync,
    manage_subscriber_lists,
    manage_subscriber_lists_by_query,
    manage_subscriber_lists_by_query_sync,
    manage_subscriber_lists_by_query_text,
    manage_subscriber_lists_by_query_text_sync,
    manage_subscriber_lists_sync,
    subscriber_send_optin_by_id,
    subscriber_send_optin_by_id_sync,
    update_subscriber_by_id,
    update_subscriber_by_id_sync,
)


class _SubscribersNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_subscribers, config)
        self.get.__doc__ = get_subscribers.__doc__
        self.get_sync = partial(get_subscribers_sync, config)
        self.get_sync.__doc__ = get_subscribers_sync.__doc__
        self.create = partial(create_subscriber, config)
        self.create.__doc__ = create_subscriber.__doc__
        self.create_sync = partial(create_subscriber_sync, config)
        self.create_sync.__doc__ = create_subscriber_sync.__doc__
        self.delete_by_list = partial(delete_subscriber_by_list, config)
        self.delete_by_list.__doc__ = delete_subscriber_by_list.__doc__
        self.delete_by_list_sync = partial(delete_subscriber_by_list_sync, config)
        self.delete_by_list_sync.__doc__ = delete_subscriber_by_list_sync.__doc__
        self.get_by_id = partial(get_subscriber_by_id, config)
        self.get_by_id.__doc__ = get_subscriber_by_id.__doc__
        self.get_by_id_sync = partial(get_subscriber_by_id_sync, config)
        self.get_by_id_sync.__doc__ = get_subscriber_by_id_sync.__doc__
        self.update_by_id = partial(update_subscriber_by_id, config)
        self.update_by_id.__doc__ = update_subscriber_by_id.__doc__
        self.update_by_id_sync = partial(update_subscriber_by_id_sync, config)
        self.update_by_id_sync.__doc__ = update_subscriber_by_id_sync.__doc__
        self.delete_by_id = partial(delete_subscriber_by_id, config)
        self.delete_by_id.__doc__ = delete_subscriber_by_id.__doc__
        self.delete_by_id_sync = partial(delete_subscriber_by_id_sync, config)
        self.delete_by_id_sync.__doc__ = delete_subscriber_by_id_sync.__doc__
        self.manage_lists = partial(manage_subscriber_lists, config)
        self.manage_lists.__doc__ = manage_subscriber_lists.__doc__
        self.manage_lists_sync = partial(manage_subscriber_lists_sync, config)
        self.manage_lists_sync.__doc__ = manage_subscriber_lists_sync.__doc__
        self.manage_list_by_id = partial(manage_subscriber_list_by_id, config)
        self.manage_list_by_id.__doc__ = manage_subscriber_list_by_id.__doc__
        self.manage_list_by_id_sync = partial(manage_subscriber_list_by_id_sync, config)
        self.manage_list_by_id_sync.__doc__ = manage_subscriber_list_by_id_sync.__doc__
        self.manage_blocklist_by_list = partial(manage_blocklist_by_subscriber_list, config)
        self.manage_blocklist_by_list.__doc__ = manage_blocklist_by_subscriber_list.__doc__
        self.manage_blocklist_by_list_sync = partial(
            manage_blocklist_by_subscriber_list_sync, config
        )
        self.manage_blocklist_by_list_sync.__doc__ = (
            manage_blocklist_by_subscriber_list_sync.__doc__
        )
        self.manage_blocklist_by_id = partial(manage_blocklist_subscribers_by_id, config)
        self.manage_blocklist_by_id.__doc__ = manage_blocklist_subscribers_by_id.__doc__
        self.manage_blocklist_by_id_sync = partial(manage_blocklist_subscribers_by_id_sync, config)
        self.manage_blocklist_by_id_sync.__doc__ = manage_blocklist_subscribers_by_id_sync.__doc__
        self.export_data_by_id = partial(export_subscriber_data_by_id, config)
        self.export_data_by_id.__doc__ = export_subscriber_data_by_id.__doc__
        self.export_data_by_id_sync = partial(export_subscriber_data_by_id_sync, config)
        self.export_data_by_id_sync.__doc__ = export_subscriber_data_by_id_sync.__doc__
        self.get_bounces_by_id = partial(get_subscriber_bounces_by_id, config)
        self.get_bounces_by_id.__doc__ = get_subscriber_bounces_by_id.__doc__
        self.get_bounces_by_id_sync = partial(get_subscriber_bounces_by_id_sync, config)
        self.get_bounces_by_id_sync.__doc__ = get_subscriber_bounces_by_id_sync.__doc__
        self.delete_bounces_by_id = partial(delete_subscriber_bounces_by_id, config)
        self.delete_bounces_by_id.__doc__ = delete_subscriber_bounces_by_id.__doc__
        self.delete_bounces_by_id_sync = partial(delete_subscriber_bounces_by_id_sync, config)
        self.delete_bounces_by_id_sync.__doc__ = delete_subscriber_bounces_by_id_sync.__doc__
        self.send_optin_by_id = partial(subscriber_send_optin_by_id, config)
        self.send_optin_by_id.__doc__ = subscriber_send_optin_by_id.__doc__
        self.send_optin_by_id_sync = partial(subscriber_send_optin_by_id_sync, config)
        self.send_optin_by_id_sync.__doc__ = subscriber_send_optin_by_id_sync.__doc__
        self.delete_by_query = partial(delete_subscriber_by_query, config)
        self.delete_by_query.__doc__ = delete_subscriber_by_query.__doc__
        self.delete_by_query_sync = partial(delete_subscriber_by_query_sync, config)
        self.delete_by_query_sync.__doc__ = delete_subscriber_by_query_sync.__doc__
        self.delete_by_query_text = partial(delete_subscriber_by_query_text, config)
        self.delete_by_query_text.__doc__ = delete_subscriber_by_query_text.__doc__
        self.delete_by_query_text_sync = partial(delete_subscriber_by_query_text_sync, config)
        self.delete_by_query_text_sync.__doc__ = delete_subscriber_by_query_text_sync.__doc__
        self.blocklist_query = partial(blocklist_subscribers_query, config)
        self.blocklist_query.__doc__ = blocklist_subscribers_query.__doc__
        self.blocklist_query_sync = partial(blocklist_subscribers_query_sync, config)
        self.blocklist_query_sync.__doc__ = blocklist_subscribers_query_sync.__doc__
        self.blocklist_query_text = partial(blocklist_subscribers_query_text, config)
        self.blocklist_query_text.__doc__ = blocklist_subscribers_query_text.__doc__
        self.blocklist_query_text_sync = partial(blocklist_subscribers_query_text_sync, config)
        self.blocklist_query_text_sync.__doc__ = blocklist_subscribers_query_text_sync.__doc__
        self.manage_lists_by_query = partial(manage_subscriber_lists_by_query, config)
        self.manage_lists_by_query.__doc__ = manage_subscriber_lists_by_query.__doc__
        self.manage_lists_by_query_sync = partial(manage_subscriber_lists_by_query_sync, config)
        self.manage_lists_by_query_sync.__doc__ = manage_subscriber_lists_by_query_sync.__doc__
        self.manage_lists_by_query_text = partial(manage_subscriber_lists_by_query_text, config)
        self.manage_lists_by_query_text.__doc__ = manage_subscriber_lists_by_query_text.__doc__
        self.manage_lists_by_query_text_sync = partial(
            manage_subscriber_lists_by_query_text_sync, config
        )
        self.manage_lists_by_query_text_sync.__doc__ = (
            manage_subscriber_lists_by_query_text_sync.__doc__
        )
