# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.templates import (
    create_template,
    create_template_sync,
    delete_template_by_id,
    delete_template_by_id_sync,
    get_template_by_id,
    get_template_by_id_sync,
    get_templates,
    get_templates_sync,
    preview_template,
    preview_template_by_id,
    preview_template_by_id_sync,
    preview_template_sync,
    set_default_template_by_id,
    set_default_template_by_id_sync,
    update_template_by_id,
    update_template_by_id_sync,
)


class _TemplatesNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_templates, config)
        self.get.__doc__ = get_templates.__doc__
        self.get_sync = partial(get_templates_sync, config)
        self.get_sync.__doc__ = get_templates_sync.__doc__
        self.create = partial(create_template, config)
        self.create.__doc__ = create_template.__doc__
        self.create_sync = partial(create_template_sync, config)
        self.create_sync.__doc__ = create_template_sync.__doc__
        self.get_by_id = partial(get_template_by_id, config)
        self.get_by_id.__doc__ = get_template_by_id.__doc__
        self.get_by_id_sync = partial(get_template_by_id_sync, config)
        self.get_by_id_sync.__doc__ = get_template_by_id_sync.__doc__
        self.update_by_id = partial(update_template_by_id, config)
        self.update_by_id.__doc__ = update_template_by_id.__doc__
        self.update_by_id_sync = partial(update_template_by_id_sync, config)
        self.update_by_id_sync.__doc__ = update_template_by_id_sync.__doc__
        self.delete_by_id = partial(delete_template_by_id, config)
        self.delete_by_id.__doc__ = delete_template_by_id.__doc__
        self.delete_by_id_sync = partial(delete_template_by_id_sync, config)
        self.delete_by_id_sync.__doc__ = delete_template_by_id_sync.__doc__
        self.preview = partial(preview_template, config)
        self.preview.__doc__ = preview_template.__doc__
        self.preview_sync = partial(preview_template_sync, config)
        self.preview_sync.__doc__ = preview_template_sync.__doc__
        self.preview_by_id = partial(preview_template_by_id, config)
        self.preview_by_id.__doc__ = preview_template_by_id.__doc__
        self.preview_by_id_sync = partial(preview_template_by_id_sync, config)
        self.preview_by_id_sync.__doc__ = preview_template_by_id_sync.__doc__
        self.set_default_by_id = partial(set_default_template_by_id, config)
        self.set_default_by_id.__doc__ = set_default_template_by_id.__doc__
        self.set_default_by_id_sync = partial(set_default_template_by_id_sync, config)
        self.set_default_by_id_sync.__doc__ = set_default_template_by_id_sync.__doc__
