# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.transactional import transact_with_subscriber, transact_with_subscriber_sync


class _TransactionalNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.transact_with_subscriber = partial(transact_with_subscriber, config)
        self.transact_with_subscriber.__doc__ = transact_with_subscriber.__doc__
        self.transact_with_subscriber_sync = partial(transact_with_subscriber_sync, config)
        self.transact_with_subscriber_sync.__doc__ = transact_with_subscriber_sync.__doc__
