# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from listmonk_unofficial_sdk.types import (
    CreateTemplateResponse,
    DeleteTemplateByIdResponse,
    GetTemplateByIdResponse,
    GetTemplatesResponse,
    UpdateTemplateByIdResponse,
)
from listmonk_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_templates(
    _client_config: ClientConfig,
    no_body: bool,
    *,
    request_options: RequestOptions | None = None,
) -> GetTemplatesResponse:
    """Lists templates. Set `no_body` to control whether template bodies are included in
    the response.

    handles retrieval of templates

    Args:
        no_body: boolean flag for response with/without body
    """

    _resp = await sdk_request(
        "GET",
        "/templates",
        params=serialize_query([("no_body", no_body, "form", True)]),
        operation_id="get_templates",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetTemplatesResponse"), GetTemplatesResponse
    )


def get_templates_sync(
    _client_config: ClientConfig,
    no_body: bool,
    *,
    request_options: RequestOptions | None = None,
) -> GetTemplatesResponse:
    """Lists templates. Set `no_body` to control whether template bodies are included in
    the response.

    handles retrieval of templates

    Args:
        no_body: boolean flag for response with/without body
    """

    _resp = sdk_request_sync(
        "GET",
        "/templates",
        params=serialize_query([("no_body", no_body, "form", True)]),
        operation_id="get_templates",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetTemplatesResponse"), GetTemplatesResponse
    )


async def create_template(
    _client_config: ClientConfig,
    name: str,
    type: Literal["campaign", "campaign_visual", "tx"] | str,
    body: str,
    subject: str | NotGiven = NOT_GIVEN,
    body_source: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateTemplateResponse:
    """Creates a new template. Supply `name`, `type`, and `body`; choose `type` from
    `campaign`, `campaign_visual`, or `tx`, and include `subject` or `body_source` when
    relevant to that template type.

    handles template creation

    Args:
        name: Name of the template
        type: Type of the template
        body: HTML body of the template
        subject: Subject line for the template (only for tx)
        body_source: JSON source for the email-builder template (only for campaign_visual)
    """

    _resp = await sdk_request(
        "POST",
        "/templates",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["campaign", "campaign_visual", "tx"] | str')
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "body_source": (
                    NOT_GIVEN if body_source is NOT_GIVEN else to_wire(body_source, "str")
                ),
            }
        ),
        operation_id="create_template",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateTemplateResponse"), CreateTemplateResponse
    )


def create_template_sync(
    _client_config: ClientConfig,
    name: str,
    type: Literal["campaign", "campaign_visual", "tx"] | str,
    body: str,
    subject: str | NotGiven = NOT_GIVEN,
    body_source: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateTemplateResponse:
    """Creates a new template. Supply `name`, `type`, and `body`; choose `type` from
    `campaign`, `campaign_visual`, or `tx`, and include `subject` or `body_source` when
    relevant to that template type.

    handles template creation

    Args:
        name: Name of the template
        type: Type of the template
        body: HTML body of the template
        subject: Subject line for the template (only for tx)
        body_source: JSON source for the email-builder template (only for campaign_visual)
    """

    _resp = sdk_request_sync(
        "POST",
        "/templates",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["campaign", "campaign_visual", "tx"] | str')
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "body_source": (
                    NOT_GIVEN if body_source is NOT_GIVEN else to_wire(body_source, "str")
                ),
            }
        ),
        operation_id="create_template",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateTemplateResponse"), CreateTemplateResponse
    )


async def get_template_by_id(
    _client_config: ClientConfig,
    id: int,
    no_body: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetTemplateByIdResponse:
    """Retrieves a template by its identifier. Use the `no_body` query parameter to request
    a response with or without the template body.

    handles retrieval of templates

    Args:
        id: The id value of the template you want to get.
        no_body: boolean flag for response with/without body
    """

    _resp = await sdk_request(
        "GET",
        f"/templates/{encode_path_segment(id)}",
        params=serialize_query([("no_body", no_body, "form", True)]),
        operation_id="get_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetTemplateByIdResponse"), GetTemplateByIdResponse
    )


def get_template_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    no_body: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> GetTemplateByIdResponse:
    """Retrieves a template by its identifier. Use the `no_body` query parameter to request
    a response with or without the template body.

    handles retrieval of templates

    Args:
        id: The id value of the template you want to get.
        no_body: boolean flag for response with/without body
    """

    _resp = sdk_request_sync(
        "GET",
        f"/templates/{encode_path_segment(id)}",
        params=serialize_query([("no_body", no_body, "form", True)]),
        operation_id="get_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetTemplateByIdResponse"), GetTemplateByIdResponse
    )


async def update_template_by_id(
    _client_config: ClientConfig,
    id: int,
    name: str | NotGiven = NOT_GIVEN,
    type: Literal["campaign", "campaign_visual", "tx"] | str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    body_source: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateTemplateByIdResponse:
    """Replaces a template's configuration. Supply the template properties you want to set,
    and use `type` to choose campaign, visual campaign, or transactional template
    behavior.

    handles template modification

    Args:
        id: The id value of the template you want to update.
        name: Name of the template
        type: Type of the template
        subject: Subject line for the template (only for tx)
        body_source: JSON source for the email-builder template (only for campaign_visual)
        body: HTML body of the template
    """

    _resp = await sdk_request(
        "PUT",
        f"/templates/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["campaign", "campaign_visual", "tx"] | str')
                ),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "body_source": (
                    NOT_GIVEN if body_source is NOT_GIVEN else to_wire(body_source, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        operation_id="update_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateTemplateByIdResponse"),
        UpdateTemplateByIdResponse,
    )


def update_template_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    name: str | NotGiven = NOT_GIVEN,
    type: Literal["campaign", "campaign_visual", "tx"] | str | NotGiven = NOT_GIVEN,
    subject: str | NotGiven = NOT_GIVEN,
    body_source: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UpdateTemplateByIdResponse:
    """Replaces a template's configuration. Supply the template properties you want to set,
    and use `type` to choose campaign, visual campaign, or transactional template
    behavior.

    handles template modification

    Args:
        id: The id value of the template you want to update.
        name: Name of the template
        type: Type of the template
        subject: Subject line for the template (only for tx)
        body_source: JSON source for the email-builder template (only for campaign_visual)
        body: HTML body of the template
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/templates/{encode_path_segment(id)}",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["campaign", "campaign_visual", "tx"] | str')
                ),
                "subject": (NOT_GIVEN if subject is NOT_GIVEN else to_wire(subject, "str")),
                "body_source": (
                    NOT_GIVEN if body_source is NOT_GIVEN else to_wire(body_source, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        operation_id="update_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UpdateTemplateByIdResponse"),
        UpdateTemplateByIdResponse,
    )


async def delete_template_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteTemplateByIdResponse:
    """Deletes a template by its identifier. Use this operation when you no longer need the
    template; the response indicates whether the deletion succeeded.

    handles deletion of templates

    Args:
        id: The id value of the template you want to delete.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/templates/{encode_path_segment(id)}",
        operation_id="delete_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteTemplateByIdResponse"),
        DeleteTemplateByIdResponse,
    )


def delete_template_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteTemplateByIdResponse:
    """Deletes a template by its identifier. Use this operation when you no longer need the
    template; the response indicates whether the deletion succeeded.

    handles deletion of templates

    Args:
        id: The id value of the template you want to delete.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/templates/{encode_path_segment(id)}",
        operation_id="delete_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "DeleteTemplateByIdResponse"),
        DeleteTemplateByIdResponse,
    )


async def preview_template(
    _client_config: ClientConfig,
    template_type: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Generates an HTML preview from the supplied template parameters. Provide
    `template_type` to identify the template type and `body` to supply the template
    content.

    get the HTML preview of a template.

    Args:
        template_type: type of template
        body: template body
    """

    _resp = await sdk_request(
        "POST",
        "/templates/preview",
        json=omit_unset(
            {
                "template_type": (
                    NOT_GIVEN if template_type is NOT_GIVEN else to_wire(template_type, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="preview_template",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


def preview_template_sync(
    _client_config: ClientConfig,
    template_type: str | NotGiven = NOT_GIVEN,
    body: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Generates an HTML preview from the supplied template parameters. Provide
    `template_type` to identify the template type and `body` to supply the template
    content.

    get the HTML preview of a template.

    Args:
        template_type: type of template
        body: template body
    """

    _resp = sdk_request_sync(
        "POST",
        "/templates/preview",
        json=omit_unset(
            {
                "template_type": (
                    NOT_GIVEN if template_type is NOT_GIVEN else to_wire(template_type, "str")
                ),
                "body": (NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "str")),
            }
        ),
        content_type="application/x-www-form-urlencoded",
        operation_id="preview_template",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


async def preview_template_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Renders an HTML preview for a template identified by its integer ID. Supply
    `template_type` and `body` as form-encoded preview parameters.

    renders the HTML preview of a template.

    Args:
        id: The id value of the template you want to get.
    """

    _resp = await sdk_request(
        "GET",
        f"/templates/{encode_path_segment(id)}/preview",
        operation_id="preview_template_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


def preview_template_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Renders an HTML preview for a template identified by its integer ID. Supply
    `template_type` and `body` as form-encoded preview parameters.

    renders the HTML preview of a template.

    Args:
        id: The id value of the template you want to get.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/templates/{encode_path_segment(id)}/preview",
        operation_id="preview_template_by_id",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


__all__ = [
    "create_template",
    "create_template_sync",
    "delete_template_by_id",
    "delete_template_by_id_sync",
    "get_template_by_id",
    "get_template_by_id_sync",
    "get_templates",
    "get_templates_sync",
    "preview_template",
    "preview_template_by_id",
    "preview_template_by_id_sync",
    "preview_template_sync",
    "update_template_by_id",
    "update_template_by_id_sync",
]
