# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import listmonk_unofficial_sdk.types as _response_types
from listmonk_unofficial_sdk.client import (
    ClientConfig,
    RequestOptions,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
)
from listmonk_unofficial_sdk.types import Template
from listmonk_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def set_default_template_by_id(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> Template:
    """Sets the specified template as the default template. Use the template's integer
    identifier to select which template to make the default.

    handles template modification.

    Args:
        id: The id value of the template you want to set to the default template.
    """

    _resp = await sdk_request(
        "PUT",
        f"/templates/{encode_path_segment(id)}/default",
        operation_id="set_default_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Template"), Template)


def set_default_template_by_id_sync(
    _client_config: ClientConfig,
    id: int,
    *,
    request_options: RequestOptions | None = None,
) -> Template:
    """Sets the specified template as the default template. Use the template's integer
    identifier to select which template to make the default.

    handles template modification.

    Args:
        id: The id value of the template you want to set to the default template.
    """

    _resp = sdk_request_sync(
        "PUT",
        f"/templates/{encode_path_segment(id)}/default",
        operation_id="set_default_template_by_id",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Template"), Template)


__all__ = [
    "set_default_template_by_id",
    "set_default_template_by_id_sync",
]
